const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
const c={window:{},console};vm.createContext(c);for(const n of ['requirements-engine','inspection-plan','role-plans','characteristic-editing'])vm.runInContext(fs.readFileSync('src/'+n+'.js','utf8'),c);const api=c.window.ASMachCharacteristicEditing;
const row=(extra={})=>({id:'a',number:1,type:'Çap',nominalValue:'9',unit:'mm',lowerTolerance:'',upperTolerance:'',lowerLimit:'',upperLimit:'',requirementMode:'auto',comment:'keep',...extra});
const parse=(raw,standard,type,ref)=>({lowerTolerance:'-0.2',upperTolerance:'+0.2',lowerLimit:'8.8',upperLimit:'9.2',toleranceStandard:standard});
test('Interval-only and sample-count edits are independent and preserve unrelated plans',()=>{const r=row({rolePlans:{quality:{...c.window.ASMachRolePlans.blank(),enabled:true,inspectionMethod:'CMM',inspectionFrequency:'EVERY_N_PIECES',frequencyInterval:'10',sampleMode:'manual',sampleCount:'3'},operator:{...c.window.ASMachRolePlans.blank(),enabled:true,inspectionMethod:'CMM'}}});const p=api.prepare([r],{roles:{quality:{frequencyInterval:'25',sampleMode:'manual',sampleCount:'5'},operator:{sampleMode:'none',inspectionFrequency:''}}},parse);assert.equal(p.errors.length,0);assert.equal(p.updates[0].after.rolePlans.quality.inspectionFrequency,'EVERY_N_PIECES');assert.equal(p.updates[0].after.rolePlans.quality.sampleCount,'5');assert.equal(r.rolePlans.quality.sampleCount,'3');assert.equal(p.updates[0].after.rolePlans.quality.frequencyInterval,'25');assert.ok(api.prepare([r],{roles:{quality:{sampleMode:'manual',sampleCount:''}}},parse).errors.length);assert.ok(api.prepare([r],{roles:{operator:{frequencyInterval:'5'}}},parse).errors.length);});
test('General tolerance protects explicit, partial, zero and limit-only values; opt-in replacement is required',()=>{for(const patch of [{toleranceExplicit:true},{lowerTolerance:'0'},{upperTolerance:0},{lowerLimit:'8.8'}]){assert.ok(api.general(row(patch),'ISO 2768-mK',parse).reason);assert.equal(api.general(row(patch),'ISO 2768-mK',parse,0,true).patch.toleranceExplicit,false);}assert.ok(api.general(row({unit:'in'}),'ISO 2768-mK',parse).reason);for(const type of ['GD&T','Diş','Geçme','Not'])assert.ok(api.general(row({type}),'ISO 2768-mK',parse).reason);});
test('Angular reference and parsed type are passed without mutating source',()=>{const r=row({type:'Açı',unit:'°',nominalValue:'45'});assert.ok(api.general(r,'ISO 2768-mK',parse).reason);let args;assert.ok(api.general(r,'ISO 2768-mK',(...a)=>{args=a;return parse();},25).patch);assert.equal(args[2],'Açı');assert.equal(args[3],25);assert.equal(r.lowerTolerance,'');});
test('Empty edits and protected-only tolerance runs are no-ops; mixed edits preserve untouched data and manual text',()=>{const r=row(),locked=row({id:'b',number:2,lowerTolerance:'-0.05',upperTolerance:'0',requirementMode:'manual',requirement:'manual'});assert.equal(api.prepare([r],{},parse).updates.length,0);assert.equal(api.prepare([locked],{standard:'ISO 2768-mK'},parse).updates.length,0);const p=api.prepare([r,locked],{standard:'ISO 2768-mK',fields:{zone:'F2'}},parse);assert.equal(p.updates.length,2);assert.equal(p.skips.length,1);assert.equal(p.updates[1].after.requirement,'manual');assert.equal(p.updates[1].after.lowerTolerance,'-0.05');assert.equal(p.updates[0].after.comment,'keep');assert.equal(r.zone,undefined);});
test('Role patches preserve other role and sample metadata; every-part aligns sampling with 100%',()=>{const r=row({rolePlans:{operator:{enabled:true,inspectionMethod:'CMM',inspectionFrequency:'PER_SHIFT'},quality:{enabled:true,inspectionMethod:'CALIPER',inspectionFrequency:'PER_LOT',sampleMode:'table',sampleLevel:'G2',operation:'OP10'}}});const p=api.prepare([r],{roles:{quality:{inspectionFrequency:'EACH_PART'}}},parse);assert.equal(p.updates[0].after.rolePlans.quality.sampleMode,'all');assert.equal(p.updates[0].after.rolePlans.quality.operation,'OP10');assert.equal(JSON.stringify(p.updates[0].after.rolePlans.operator),JSON.stringify(r.rolePlans.operator));const invalid=api.prepare([r],{roles:{quality:{inspectionFrequency:'EVERY_N_PIECES',frequencyInterval:'0'}}},parse);assert.ok(invalid.errors.length);});
