'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),crypto=require('node:crypto'),{Readable}=require('node:stream');
const {createReleases}=require('../license-manager/releases.cjs');
function fixture(){const root=fs.mkdtempSync(path.join(os.tmpdir(),'asmach-release-test-'));fs.mkdirSync(path.join(root,'.release-admin'));fs.mkdirSync(path.join(root,'src-tauri'));const pair=crypto.generateKeyPairSync('ed25519');fs.writeFileSync(path.join(root,'.release-admin/update-private.pem'),pair.privateKey.export({type:'pkcs8',format:'pem'}));fs.writeFileSync(path.join(root,'src-tauri/updater-config.json'),JSON.stringify({url:'https://publisher.example/update.json',public_key:Buffer.from(pair.publicKey.export({format:'jwk'}).x,'base64url').toString('base64')}));const bytes=Buffer.alloc(1024);bytes.write('MZ');bytes.writeUInt32LE(64,60);bytes.write('PE\0\0',64);bytes.writeUInt16LE(0x14c,68);return{root,bytes,pair,api:createReleases(root),close(){fs.rmSync(root,{recursive:true,force:true});}};}
test('Setup validation, signing, remote hash checks and publication use only fixture data',async()=>{
 const f=fixture(),original=global.fetch;let published=false;
 global.fetch=async(url,options)=>{let result;if(url.endsWith('/admin/ping'))result={service:'asmach-publisher-v1'};else if(url.includes('/admin/artifact/'))result={size:options.body.length,sha256:crypto.createHash('sha256').update(options.body).digest('hex')};else if(options.method==='GET')result={version:null,etag:null};else{const body=JSON.parse(options.body),payload=Buffer.from(body.envelope.payload,'base64');assert.equal(crypto.verify(null,payload,f.pair.publicKey,Buffer.from(body.envelope.signature,'base64')),true);result={version:JSON.parse(payload).version};published=true;}return{ok:true,json:async()=>result};};
 try{await f.api.configure({url:'https://publisher.example',token:'x'.repeat(32)});assert.equal(f.api.info().token,undefined);await assert.rejects(()=>f.api.upload(Readable.from([Buffer.from('bad')]),{version:'2.1.0',name:'a.exe',variant:'online',channel:'test'}));const draft=await f.api.upload(Readable.from([f.bytes]),{version:'2.1.0',name:'setup.exe',variant:'online',channel:'test'});assert.equal(draft.status,'draft');await assert.rejects(()=>f.api.publish({id:draft.id}));assert.equal(published,false);const out=await f.api.publish({id:draft.id,confirm:'YAYINLA',verified:true});assert.equal(out.status,'published');assert.equal(f.api.info().items.length,1);await assert.rejects(()=>f.api.publish({id:draft.id,confirm:'YAYINLA',verified:true}));}finally{global.fetch=original;f.close();}
});
test('Altered local setup cannot be published; credentials never appear in status',async()=>{const f=fixture();try{const d=await f.api.upload(Readable.from([f.bytes]),{version:'2.1.0',name:'setup.exe',variant:'offline',channel:'stable'});fs.appendFileSync(path.join(f.root,'.release-admin', 'releases',d.id+'.exe'),'changed');await assert.rejects(()=>f.api.publish({id:d.id,confirm:'YAYINLA',verified:true}));assert.equal(f.api.info().items[0].status,'failed');assert.equal(f.api.info().busy,false);}finally{f.close();}});
