const{test}=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto'),fs=require('node:fs');
test('device discovery requires fresh key proof and returns only signed matching license',async()=>{
 const{default:w}=await import('data:text/javascript;base64,'+Buffer.from(fs.readFileSync('licensing-service/worker.js','utf8').replace(/^export \{LicenseActivation\}[^\n]*\n/,'')).toString('base64'));
 const signing=crypto.generateKeyPairSync('ed25519'),device=crypto.generateKeyPairSync('ec',{namedCurve:'prime256v1'}),jwk=device.publicKey.export({format:'jwk'}),pub=Buffer.concat([Buffer.from([69,67,83,49,32,0,0,0]),Buffer.from(jwk.x,'base64url'),Buffer.from(jwk.y,'base64url')]),deviceId=crypto.createHash('sha256').update(pub).digest('hex'),data=new Map();
 const env={ADMIN_TOKEN:'a'.repeat(64),STATUS_PRIVATE_KEY:signing.privateKey.export({format:'pem',type:'pkcs8'}),REVOCATIONS:{get:async k=>data.get(k),list:async()=>({list_complete:true,keys:[...data.keys()].filter(k=>k.startsWith('license:')).map(name=>({name}))})}};
 const call=(route,body)=>w.fetch(new Request('https://test'+route,{method:'POST',body:JSON.stringify(body)}),env);
 const ticket=await(await call('/discover-challenge',{deviceId})).json(),body={deviceId,ticket,publicKey:pub.toString('base64'),proof:crypto.sign('sha256',Buffer.from(ticket.challenge,'base64'),{key:device.privateKey,dsaEncoding:'ieee-p1363'}).toString('base64')};
 assert.equal((await call('/discover',{...body,deviceId:'b'.repeat(64)})).status,403);assert.equal((await call('/discover',{...body,proof:Buffer.alloc(64).toString('base64')})).status,403);
 const read=async()=>{const r=await call('/discover',body);assert.equal(r.status,200);const e=await r.json();assert.ok(crypto.verify(null,Buffer.from(e.payload,'base64'),signing.publicKey,Buffer.from(e.signature,'base64')));return JSON.parse(Buffer.from(e.payload,'base64'));};assert.equal((await read()).status,'inactive');
 const p={version:2,binding:'tpm-cng-v1',deviceId,licenseId:crypto.randomUUID(),issuedAt:100,expiresAt:9999999999},bytes=Buffer.from(JSON.stringify(p)),envelope={payload:bytes.toString('base64'),signature:crypto.sign(null,bytes,signing.privateKey).toString('base64')};data.set('license:'+p.licenseId,JSON.stringify(envelope));assert.equal((await read()).licenseUpdate.payload,envelope.payload);data.set('device:'+deviceId,p.licenseId);assert.equal((await read()).licenseId,p.licenseId);data.set('revoked:'+p.licenseId,'1');assert.equal((await read()).status,'revoked');assert.equal((await read()).licenseUpdate,undefined);
 const expired={deviceId,challenge:ticket.challenge,expiresAt:1},payload=Buffer.from(JSON.stringify(expired)).toString('base64');assert.equal((await call('/discover',{...body,ticket:{payload,signature:crypto.createHmac('sha256',env.ADMIN_TOKEN).update(payload).digest('base64')}})).status,403);
});
