const{test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),crypto=require('node:crypto');
const{createStore}=require('../license-manager/store.cjs'),{start}=require('../license-manager/server.cjs');
function fixture(){const root=fs.mkdtempSync(path.join(os.tmpdir(),'asmach-manager-test-'));fs.mkdirSync(path.join(root,'.license-admin'));fs.mkdirSync(path.join(root,'src-tauri'));const{privateKey,publicKey}=crypto.generateKeyPairSync('ed25519');fs.writeFileSync(path.join(root,'.license-admin/license.pem'),privateKey.export({type:'pkcs8',format:'pem'}));fs.writeFileSync(path.join(root,'src-tauri/license-config.json'),JSON.stringify({licensePublicKey:Buffer.from(publicKey.export({format:'jwk'}).x,'base64url').toString('base64')}));return{root,publicKey};}
const input=()=>({customer:'Deneme <script> firma',deviceId:'a'.repeat(64),startsAt:new Date(Date.now()-1000).toISOString(),expiresAt:new Date(Date.now()+86400000).toISOString(),note:'Test notu'});
function cleanup(root){if(!path.resolve(root).startsWith(path.join(os.tmpdir(),'asmach-manager-test-')))throw Error('Unsafe test cleanup');fs.rmSync(root,{recursive:true,force:true});}
test('issue, download, preserve, renew, pending revocation and audit',()=>{const f=fixture();let s=createStore(f.root);try{const p=s.issue(input());assert.equal(s.list().length,1);const e=JSON.parse(s.exportLicense(p.licenseId).text);assert.ok(crypto.verify(null,Buffer.from(e.payload,'base64'),f.publicKey,Buffer.from(e.signature,'base64')));assert.equal(JSON.parse(Buffer.from(e.payload,'base64')).deviceId,'a'.repeat(64));assert.equal(s.saveLicense(p.licenseId).path,s.saveLicense(p.licenseId).path);assert.throws(()=>s.issue({...input(),deviceId:'bad'}));assert.throws(()=>s.issue({...input(),expiresAt:'2000-01-01'}));assert.throws(()=>s.issue({...input(),renewedFrom:p.licenseId,deviceId:'b'.repeat(64)}));const renewed=s.issue({...input(),renewedFrom:p.licenseId,expiresAt:new Date(Date.now()+86400000*3).toISOString()});assert.notEqual(renewed.licenseId,p.licenseId);s.revoke(p.licenseId);assert.equal(s.list().find(r=>r.licenseId===p.licenseId).status,'İptal bekliyor');assert.equal(s.revocations()[0].key,'revoked:'+p.licenseId);assert.ok(s.history().length>=5);s.close();s=createStore(f.root);assert.equal(s.list().length,2);assert.equal(s.list().find(r=>r.licenseId===p.licenseId).revocationRequested,true);}finally{s.close();cleanup(f.root);}});
test('HTTP API denies missing token, cross-origin requests, host rebinding and file traversal',async()=>{const f=fixture(),a=await start(f.root);try{assert.equal((await fetch(a.origin+'/api/list')).status,401);const headers={Authorization:'Bearer '+a.token};assert.equal((await fetch(a.origin+'/api/list',{headers})).status,200);assert.equal((await fetch(a.origin+'/api/list',{headers:{...headers,Origin:'https://evil.example'}})).status,403);
 const rebound=await new Promise((resolve,reject)=>{require('node:http').get(a.origin+'/api/list',{headers:{...headers,Host:'evil.example'}},r=>{r.resume();resolve(r.statusCode);}).on('error',reject);});assert.equal(rebound,403);
 assert.equal((await fetch(a.origin+'/.license-admin/license.pem')).status,404);assert.equal((await fetch(a.origin+'/api/issue',{method:'POST',headers,body:'{}'})).status,415);const r=await fetch(a.origin+'/api/issue',{method:'POST',headers:{...headers,'Content-Type':'application/json'},body:JSON.stringify(input())});assert.equal(r.status,200);assert.ok((await r.json()).licenseId);}finally{await new Promise(r=>a.server.close(r));cleanup(f.root);}});
module.exports={fixture,cleanup};
test('first-device keys and public numbers survive amendments and reopening',()=>{const f=fixture();let s=createStore(f.root);try{const p=s.issue({...input(),deviceId:'',binding:'first-device'});assert.match(p.activationKey,/^[A-F0-9]{8}-[A-F0-9]{4}-4[A-F0-9]{3}-[89AB][A-F0-9]{3}-[A-F0-9]{12}$/);assert.match(p.licenseNumber,/^ASM-/);assert.equal(p.deviceId,'');assert.equal(p.binding,'tpm-cng-v1');s.amend(p.licenseId,new Date(Date.now()+86400000*3).toISOString());s.close();s=createStore(f.root);const r=s.list()[0];assert.equal(r.activationKey,p.activationKey);assert.equal(r.licenseNumber,p.licenseNumber);assert.equal(r.licenseId,p.licenseId);assert.equal(r.revision,2);const e=JSON.parse(s.exportLicense(p.licenseId).text);assert.equal(JSON.parse(Buffer.from(e.payload,'base64')).activationKey,undefined);}finally{s.close();cleanup(f.root);}});
test('user details preserve licenses and scope both history views',()=>{const f=fixture(),s=createStore(f.root);try{const a=s.issue(input()),b=s.issue({...input(),deviceId:'b'.repeat(64)}),other=s.issue({...input(),customer:'Other'});const d=s.detail(a.licenseId);assert.equal(d.licenses.length,2);assert.equal(s.detail(b.licenseId).user.id,d.user.id);s.updateUser(d.user.id,{email:'owner@example.com',company:'Firma',notes:'Not'});const next=s.detail(a.licenseId);assert.equal(next.user.email,'owner@example.com');assert.ok(next.userHistory.some(h=>h.action==='Kullanıcı bilgileri güncellendi'));assert.ok(!next.licenseHistory.some(h=>h.action==='Kullanıcı bilgileri güncellendi'));assert.equal(s.detail(other.licenseId).user.email,undefined);assert.equal(next.license.expiresAt,a.expiresAt);assert.throws(()=>s.updateUser('missing',{}));}finally{s.close();cleanup(f.root);}});
test('cloud expiry amendments keep ID and do not create additional license files',async()=>{
 const f=fixture(),store=createStore(f.root);let manager;const received=[];
 const cloud=require('node:http').createServer((req,res)=>{let body='';req.on('data',c=>body+=c);req.on('end',()=>{const data=JSON.parse(body);received.push(data);res.setHeader('Content-Type','application/json');res.end(JSON.stringify({ok:true,licenseId:data.license.licenseId,revision:data.license.revision}));});});
 await new Promise(r=>cloud.listen(0,'127.0.0.1',r));
 try{fs.writeFileSync(path.join(f.root,'.license-admin/cloud.json'),JSON.stringify({url:'http://127.0.0.1:'+cloud.address().port,token:'test-only-token'}));const license=store.issue(input());const file=store.saveLicense(license.licenseId).path,original=fs.readFileSync(file,'utf8'),files=fs.readdirSync(path.dirname(file));manager=await start(f.root);
 for(let days=2;days<=3;days++){const r=await fetch(manager.origin+'/api/amend',{method:'POST',headers:{Authorization:'Bearer '+manager.token,'Content-Type':'application/json'},body:JSON.stringify({id:license.licenseId,expiresAt:new Date(Date.now()+days*86400000).toISOString()})});assert.equal(r.status,200);const result=await r.json();assert.equal(result.published,true);assert.equal(result.licenseId,license.licenseId);assert.equal(result.path,undefined);}
 assert.equal(store.list().length,1);assert.equal(store.list()[0].revision,3);assert.deepEqual(received.map(r=>r.license.licenseId),[license.licenseId,license.licenseId]);assert.deepEqual(fs.readdirSync(path.dirname(file)),files);assert.equal(fs.readFileSync(file,'utf8'),original);
 }finally{if(manager)await new Promise(r=>manager.server.close(r));await new Promise(r=>cloud.close(r));store.close();cleanup(f.root);}
});
test('TPM revisions preserve history and failed cloud revoke does not mark revoked',async()=>{const f=fixture(),s=createStore(f.root);let a;try{const p=s.issue({...input(),binding:'tpm-cng-v1'});assert.equal(p.version,2);const original=s.saveLicense(p.licenseId).path;const changed=s.amend(p.licenseId,new Date(Date.now()+86400000*2).toISOString());assert.equal(changed.license.revision,2);assert.equal(changed.license.deviceId,p.deviceId);assert.notEqual(s.saveLicense(p.licenseId).path,original);assert.ok(fs.existsSync(original));assert.ok(s.history().some(h=>h.action==='Süre değiştirildi'&&h.detail.includes('previous')));a=await start(f.root);const r=await fetch(a.origin+'/api/revoke',{method:'POST',headers:{Authorization:'Bearer '+a.token,'Content-Type':'application/json'},body:JSON.stringify({id:p.licenseId})});assert.equal(r.status,400);assert.equal(s.list()[0].cloudRevoked,false);assert.equal(s.list()[0].revocationRequested,false);}finally{if(a)await new Promise(r=>a.server.close(r));s.close();cleanup(f.root);}});
