const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
function context(){const c={console,performance,window:null};c.window=c;vm.createContext(c);vm.runInContext(fs.readFileSync('src/requirements-engine.js','utf8'),c);vm.runInContext(fs.readFileSync('src/ocr-verifier.js','utf8'),c);return c;}
test('matching engines keep primary fields and do not remove its review flag',()=>{const c=context(),p={text:'M12x1.25-6H',needsReview:true,confidence:80};const result=c.ASMachOcrVerifier._test.combine(p,{text:'M12 x 1.25-6H',score:.97,engine:'PaddleOCR'});assert.equal(result.secondaryEvidence.status,'agreement');assert.equal(result.text,p.text);assert.equal(result.needsReview,true);});
test('different valid readings remain whole alternatives, never mixed numeric fields',()=>{const c=context(),p={text:'M12x1.25-6H',confidence:80};const result=c.ASMachOcrVerifier._test.combine(p,{text:'M10x1.5-6H',score:.99});assert.equal(result.text,p.text);assert.equal(result.needsReview,true);assert.equal(result.alternatives[0].text,'M10x1.5-6H');assert.equal(p.alternatives,undefined);});
test('second engine may propose a complete valid rescue but always requires review',()=>{const c=context(),result=c.ASMachOcrVerifier._test.combine({text:'??',confidence:0},{text:'M10x1.5-6H',score:.98,engine:'PaddleOCR'});assert.equal(result.text,'M10x1.5-6H');assert.equal(result.needsReview,true);assert.equal(result.primaryEvidence.text,'??');});
test('rescued reading never inherits failed primary geometry or confidence',()=>{const c=context(),primary={text:'??',confidence:99,angle:180,layout:{nominal:123},measurementKind:'length',previewImage:'old',error:'unreadable'};const result=c.ASMachOcrVerifier._test.combine(primary,{text:'M10x1.5-6H',score:.98,engine:'PaddleOCR'});assert.equal(result.confidence,null);for(const key of ['angle','layout','measurementKind','previewImage','error'])assert.equal(result[key],undefined,key);assert.equal(result.primaryEvidence.angle,180);assert.equal(result.needsReview,true);});
test('confident primary and GD&T bypass experimental model/engine execution',async()=>{const c=context();let calls=0;c.ASMachOcrVerifier.configure({secondary:{recognize:async()=>{calls++;return{text:'bad'};}}});for(const primary of [{text:'12',confidence:97},{text:'gdt',confidence:50,visualGdt:true}]){const r=await c.ASMachOcrVerifier.recognize('image',{},async()=>primary);assert.equal(r.verificationPerformance.ran,false);}assert.equal(calls,0);});
test('unavailable secondary never destroys the primary reading',async()=>{const c=context();c.ASMachOcrVerifier.configure({secondary:{recognize:async()=>{throw new Error('model missing');}}});const r=await c.ASMachOcrVerifier.recognize('image',{},async()=>({text:'M12x1.25-6H',confidence:80,needsReview:true}));assert.equal(r.text,'M12x1.25-6H');assert.equal(r.secondaryEvidence.status,'unavailable');assert.equal(r.needsReview,true);});
test('production integration is symbol-only and cannot silently rewrite a measurement',()=>{const engine=fs.readFileSync('src/ocr-engine.js','utf8'),verifier=fs.readFileSync('src/ocr-verifier.js','utf8'),build=fs.readFileSync('scripts/build-single.cjs','utf8');assert.match(engine,/skipSymbolVerification/);assert.match(verifier,/\^\[0\.,\+\\-−±ØOR\]\$/);assert.doesNotMatch(verifier,/filter\(s=>\^\\d/);assert.match(build,/ASMachGlyphModel/);assert.match(build,/technical-glyph-model','ocr-verifier/);});
test('rotated source glyphs are not scored by the horizontal-only model',async()=>{const c=context();let calls=0;c.ASMachOcrVerifier.configure({classifier:{inferImage(){calls++;throw new Error('unexpected inference');}}});for(const angle of [90,180,270]){const result=await c.ASMachOcrVerifier.recognize('image',{forceVerification:true},async()=>({text:'12',confidence:50,words:[{angle,symbols:[{text:'1',x:0,y:0,w:.1,h:.5}]}]}));assert.equal(result.glyphEvidence.length,0);assert.equal(result.glyphModelError,undefined);}assert.equal(calls,0);});
