"use strict";
const fs = require("node:fs");
const path = require("node:path");
const vm = require("node:vm");
const assert = require("node:assert/strict");

const root = path.resolve(__dirname, "..");
const template = path.join(root, "src/app.template.html");
const html = fs.readFileSync(fs.existsSync(template) ? template : path.join(root, "ASMach_Teknik_Resim_Balonlama.html"), "utf8");
const context = vm.createContext({ window: {}, console });
const startMatch = /function (?:legacyParseTechnicalRequirement|parseTechnicalRequirementLegacy)\(rawText, generalToleranceStandard = ""\) \{/.exec(html) ||
  /function parseTechnicalRequirement\(rawText, generalToleranceStandard = ""\) \{/.exec(html);
assert.ok(startMatch, "Host legacy parser is available");
const parserName = startMatch[0].match(/function (\w+)/)[1];
const end = html.indexOf("function technicalTextScore(", startMatch.index);
assert.ok(end > startMatch.index, "Host parser helpers are available");
vm.runInContext(html.slice(startMatch.index, end), context);
vm.runInContext(fs.readFileSync(path.join(root, "src/requirements-engine.js"), "utf8"), context);
const api = context.window.ASMachRequirements;
const parse = (text, standard = "") => api.parse(text, standard, context[parserName]);
let checks = 0;
function check(text, expected, standard = "") {
  const actual = parse(text, standard);
  for (const [key, value] of Object.entries(expected)) {
    assert.equal(actual[key], value, `${text}: ${key}; received ${JSON.stringify(actual)}`);
    checks += 1;
  }
  return actual;
}

check("25 ±0.1", { type: "Uzunluk", nominalValue: "25", lowerTolerance: "-0.1", upperTolerance: "+0.1", lowerLimit: "24.9", upperLimit: "25.1" });
for(const text of ['Ø24.5 ±0.05','Ø24.5 ±0.0 5','Ø 2 4 . 5 ± 0 . 0 5','Ø24,5 ±0,0 5'])check(text,{type:'Çap',nominalValue:'24.5',lowerTolerance:'-0.05',upperTolerance:'+0.05',lowerLimit:'24.45',upperLimit:'24.55'});
assert.equal(api.normalize('Ø24.5 ±0.05 35'),'Ø24.5 ±0.05 35','Do not append a separate multi-digit nominal to a decimal tolerance');
check("±0.1 A", {type:"GD&T",gdtSubtype:"unknown",nominalValue:"",lowerTolerance:"0",upperTolerance:"0.1",toleranceExplicit:true}, "ISO 2768-mK");
check("◎ ±0.1|A", {type:"GD&T",gdtSubtype:"concentricity",nominalValue:"",lowerTolerance:"0",upperTolerance:"0.1"}, "ISO 2768-mK");
check("Ø 2 7 . 3 0 -0 . 0 5", {type:"Çap",nominalValue:"27.3",lowerTolerance:"-0.05",upperTolerance:"0",lowerLimit:"27.25",upperLimit:"27.3"});
check("Ø27.3\n0\n-0.05", {type:"Çap",nominalValue:"27.3",lowerTolerance:"-0.05",upperTolerance:"0"});
check("0\nØ27.3\n-0.05", {type:"Çap",nominalValue:"27.3",lowerTolerance:"-0.05",upperTolerance:"0"});
check("Ø27.3 0-0.05", {type:"Çap",nominalValue:"27.3",lowerTolerance:"-0.05",upperTolerance:"0"});
check("Ø 2 7 . 3 + 0 . 0 5 / - 0 . 0 2", {nominalValue:"27.3",lowerTolerance:"-0.02",upperTolerance:"+0.05"});
check("25 +0.2 / -0.1", { nominalValue: "25", lowerTolerance: "-0.1", upperTolerance: "+0.2", lowerLimit: "24.9", upperLimit: "25.2" });
check("25+0.2-0.1", { nominalValue: "25", lowerTolerance: "-0.1", upperTolerance: "+0.2", lowerLimit: "24.9", upperLimit: "25.2" });
check("25 0/+0.1", { nominalValue: "25", lowerTolerance: "0", upperTolerance: "+0.1" });
check("25 -0.2/0", { nominalValue: "25", lowerTolerance: "-0.2", upperTolerance: "0" });
check("25 (+0.2/+0.1)", { lowerTolerance: "+0.1", upperTolerance: "+0.2", lowerLimit: "25.1" });
check("25 (-0.2/-0.1)", { lowerTolerance: "-0.2", upperTolerance: "-0.1", upperLimit: "24.9" });
check("25 +0.2/0", { lowerTolerance: "0", upperTolerance: "+0.2" });
check("25 0/-0.1", { lowerTolerance: "-0.1", upperTolerance: "0" });
check("+0.2\nØ25\n-0.1", { type: "Çap", nominalValue: "25", lowerTolerance: "-0.1", upperTolerance: "+0.2" });
check("25\n+0.2\n-0.1", { nominalValue: "25", lowerLimit: "24.9", upperLimit: "25.2" });
check("∅ 25,00 ± 0,10", { type: "Çap", nominalValue: "25", lowerLimit: "24.9" });
check("24.9 / 25.1", { nominalValue: "25", lowerLimit: "24.9", upperLimit: "25.1" });
check("25.1\n24.9", { nominalValue: "25", lowerLimit: "24.9", upperLimit: "25.1" });
check("MIN 24.9 MAX 25.1", { lowerLimit: "24.9", upperLimit: "25.1" });
check("4x Ø6 ±0.05", { type: "Çap", nominalValue: "6", lowerLimit: "5.95", quantity: 4 });
check("6x M8x1.25-6H", { type: "Diş", nominalValue: "8", threadPitch: "1.25", threadClass: "6H", quantity: 6, lowerTolerance: "", evaluationMethod: "OK_NOT_OK" });
check("1/4-20 UNC-2B", { type: "Diş", nominalValue: "0.25", unit: "in", threadPitch: "20 TPI", threadClass: "2B" });
check("2 x 45°", { type: "Pah", nominalValue: "2", chamferAngle: "45", unit: "mm", lowerTolerance: "", evaluationMethod: "OK_NOT_OK" });
check("2 ±0.1 x 45° ±1°", { type: "Pah", nominalValue: "2", chamferAngle: "45", chamferAngleTolerance: "1", lowerLimit: "1.9", upperLimit: "2.1" });
check("C0.5", { type: "Pah", nominalValue: "0.5", chamferAngle: "" });
check("30° ±0.5°", { type: "Açı", nominalValue: "30", lowerLimit: "29.5", upperLimit: "30.5", unit: "°" });
check("30° ±30′", { type: "Açı", lowerTolerance: "-0.5", upperTolerance: "0.5", lowerLimit: "29.5" });
check("30° 30′", { type: "Açı", nominalValue: "30.5", lowerTolerance: "" });
check("DATUM A", { type: "Datum", datumRefs: "A", nominalValue: "", evaluationMethod: "OK_NOT_OK" });
check("[B]", { type: "Datum", datumRefs: "B" });
check("MALZEME: 42CrMo4", { type: "Malzeme", nominalValue: "", unit: "" });
check("HEAT TREAT 58 HRC", { type: "Proses", nominalValue: "", unit: "" });
check("ÇAPAKLARI 0.2 MM ALIN", { type: "Not", nominalValue: "", evaluationMethod: "OK_NOT_OK" });
check("25 MAX", { nominalValue: "", lowerLimit: "", upperLimit: "25" });
check("MIN 25", { nominalValue: "", lowerLimit: "25", upperLimit: "" });
check("<= 25", { lowerLimit: "", upperLimit: "25", upperInclusive: true });
check("< 25", { upperLimit: "25", upperInclusive: false });
check("Ra ≤3.2", { type: "Yüzey", nominalValue: "3.2", upperLimit: "3.2", lowerLimit: "0", unit: "µm" });
check("Ra 3.2", { type: "Yüzey", nominalValue: "3.2", upperLimit: "", lowerLimit: "" });
check("⌖|Ø0.2Ⓜ|A|BⓂ|C", { type: "GD&T", nominalValue: "", lowerTolerance: "0", upperTolerance: "0.2", lowerLimit: "0", upperLimit: "0.2", datumRefs: "A | BⓂ | C", specialDesignator: "⌖" });
check("POSITION Ø0.2(M) A B C", { type: "GD&T", upperLimit: "0.2", datumRefs: "A | B | C" });
check("⏥|0.1", { type: "GD&T", nominalValue: "", lowerLimit: "0", upperLimit: "0.1", datumRefs: "" });
check("⟂|0.05|A-B", { type: "GD&T", datumRefs: "A-B" });
assert.deepEqual(Array.from(api.gdtCells("⌖|Ø0.2Ⓜ|A|BⓂ|C")), ["⌖", "Ø0.2Ⓜ", "A", "BⓂ", "C"]);
assert.ok(parse("⌖ A B").parseWarnings.length > 0);
assert.equal(parse("Ø20 g6").parseWarnings.length, 0);
assert.ok(parse("Ø20 H7").toleranceStandard.includes("NACHI tablosu"));
check("Ø20 g6", { type: "Çap", lowerLimit: "19.98", upperLimit: "19.993" });
check("Ø20 H7/g6", { type: "Çap", lowerLimit: "", upperLimit: "" });
check("25", { lowerTolerance: "-0.2", upperTolerance: "+0.2", lowerLimit: "24.8", upperLimit: "25.2" }, "ISO 2768-mK");
check("25 ±0.05", { lowerTolerance: "-0.05", upperTolerance: "+0.05" }, "ISO 2768-mK");
check("0.1 in", { lowerTolerance: "", upperTolerance: "", unit: "in" }, "ISO 2768-mK");
check("MALZEME 25", { lowerTolerance: "", upperTolerance: "" }, "ISO 2768-mK");
check("2x45°", { type: "Pah", lowerTolerance: "", upperTolerance: "" }, "ISO 2768-mK");

function evaluation(record, result) {
  assert.equal(api.evaluate(record).result, result, JSON.stringify({ record, evaluated: api.evaluate(record) }));
  checks += 1;
}
evaluation({ ...parse("25 ±0.1"), result: "24.9" }, "pass");
evaluation({ ...parse("25 ±0.1"), result: "25.10001" }, "fail");
evaluation({ ...parse("25 ±0.1"), result: "25,0" }, "pass");
evaluation({ ...parse("25 ±0.1"), result: "" }, "pending");
evaluation({ ...parse("25 ±0.1"), result: "NaN" }, "invalid");
evaluation({ ...parse("25 ±0.1"), result: "Infinity" }, "invalid");
evaluation({ ...parse("25"), result: "25" }, "invalid");
evaluation({ ...parse("Ø25 H7/g6"), evaluationMethod: "VALUE", result: "25" }, "invalid");
evaluation({ ...parse("⌖|Ø0.2|A|B"), result: "0.15" }, "pass");
evaluation({ ...parse("⌖|Ø0.2|A|B"), result: "-0.01" }, "fail");
evaluation({ ...parse("25 MAX"), result: "24.9" }, "pass");
evaluation({ ...parse("25 MAX"), result: "25.1" }, "fail");
evaluation({ ...parse("MIN 25"), result: "25" }, "pass");
evaluation({ ...parse("<25"), result: "25" }, "fail");
evaluation({ ...parse("M6x1-6H"), result: "OK" }, "pass");
evaluation({ ...parse("M6x1-6H"), result: "NOT_OK" }, "fail");
evaluation({ ...parse("M6x1-6H"), result: "25" }, "invalid");
evaluation({ type: "Uzunluk", lowerLimit: "5", upperLimit: "2", result: "3" }, "invalid");
evaluation({ type: "Uzunluk", nominalValue: "0.1", lowerTolerance: "-0.1", upperTolerance: "0.2", result: "0.3" }, "pass");
evaluation({ type: "Uzunluk", lowerLimit: "0", upperLimit: "no", result: "1" }, "invalid");
assert.equal(api.validate({ type: "Uzunluk", requirementText: "25", quantity: 0, lowerLimit: "2", upperLimit: "1" }).valid, false);
assert.equal(api.validate({ type: "GD&T", requirementText: "⏥0.1", ...parse("⏥0.1") }).valid, true);
assert.equal(api.normalizeStatus("ONAYLI"), "approved");
assert.equal(api.normalizeStatus("KONTROL"), "needs_review");
assert.equal(api.normalizeType("dimension"), "Uzunluk");
assert.equal(api.fieldProfile("GD&T").nominal, false);
assert.equal(api.fieldProfile("Malzeme").numeric, false);
assert.equal(api.STATUSES.length, 6);
console.log(`Requirements engine: ${checks} field/evaluation checks and 15 structure/validation checks passed.`);
