'use strict';
// Excel must use the native picker/launcher, never the HTML import grid.
const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
test('version check is informational and contains no installer action',()=>{const c=JSON.parse(fs.readFileSync('src-tauri/updater-config.json')),bridge=fs.readFileSync('src/tauri-bridge.js','utf8'),rust=fs.readFileSync('src-tauri/src/lib.rs','utf8');assert.match(c.url,/^https:\/\/.*\/version\//);assert.ok(!bridge.includes('install_update'));assert.ok(!rust.includes('download_and_install'));assert.ok(!JSON.stringify(JSON.parse(fs.readFileSync('src-tauri/tauri.conf.json'))).includes('createUpdaterArtifacts'));});
function bridge(handler){const calls=[],events=[],root={addEventListener:()=>{},__TAURI__:{core:{invoke:async(name,args)=>{calls.push({name,args});if(name==='desktop_bootstrap')return {preferences:{'asmach.test':'saved'},version:'1.0.0',autostart:false};return handler?.(name,args);}}},dispatchEvent:e=>events.push(e)};vm.runInNewContext(fs.readFileSync('src/tauri-bridge.js','utf8'),{window:root,CustomEvent,Blob,File,Uint8Array,Map,String,Promise,Error,JSON,Object,btoa,atob});return {api:root.ASMachDesktop,root,calls,events};}
test('Excel preview sends workbook bytes and print settings and returns a PDF blob',async()=>{const {api,calls}=bridge(name=>name==='native_excel_preview'?btoa('%PDF-QA'):undefined);await api.ready;const out=await api.excelPrintPreview(new Blob(['PK-QA']),'a3',true);assert.equal(await out.text(),'%PDF-QA');assert.equal(out.type,'application/pdf');const call=calls.find(c=>c.name==='native_excel_preview');assert.equal(atob(call.args.data),'PK-QA');assert.equal(call.args.paper,'a3');assert.equal(call.args.landscape,true);});
test('preferences hydrate from native SQLite and flush through native commands',async()=>{const {api,calls}=bridge();await api.ready;assert.equal(api.preferences.getItem('asmach.test'),'saved');api.preferences.setItem('asmach.test','new');await api.preferences.flush();assert.equal(calls.at(-1).name,'preference_set');assert.equal(calls.at(-1).args.value,'new');});
test('a failed native write stays pending and can be retried',async()=>{let fail=true;const {api}=bridge(name=>{if(name==='preference_set'&&fail)throw Error('Disk full');});await api.ready;api.preferences.setItem('asmach.test','retry');await assert.rejects(api.preferences.flush(),/Disk full/);fail=false;await api.preferences.flush();assert.equal(api.preferences.getItem('asmach.test'),'retry');});
test('native save cancellation never creates a download fallback',async()=>{const {api}=bridge(()=>null);await api.ready;assert.equal((await api.chooseSaveTarget('report.pdf')).cancelled,true);await assert.rejects(api.writeTarget(new Blob(['data']),{}),/hedefi/);});
test('Excel opening uses the native command and preserves cancellation',async()=>{for(const result of [true,false]){const {api,calls}=bridge(name=>name==='native_excel_open'?result:undefined);await api.ready;assert.equal(await api.openExcelTemplate(),result);assert.equal(calls.at(-1).name,'native_excel_open');}});
test('exports pass exact bytes and the selected one-use capability',async()=>{const {api,calls}=bridge(name=>name==='choose_save_target'?'chosen-token':undefined);await api.ready;const target=await api.chooseSaveTarget('ölçüm.pdf');await api.writeTarget(new Blob(['%PDF-test']),target);assert.equal(calls.at(-1).name,'write_target');assert.equal(calls.at(-1).args.token,'chosen-token');assert.equal(atob(calls.at(-1).args.data),'%PDF-test');});
test('open after saving is opt-in and a launch failure does not repeat the successful write',async()=>{const {api,calls,events}=bridge(name=>name==='write_target'?'Saved but could not open':undefined);await api.ready;await api.writeTarget(new Blob(['PK-test']),{nativeToken:'report',openAfter:true});assert.equal(calls.at(-1).args.openAfter,true);assert.equal(calls.filter(c=>c.name==='write_target').length,1);assert.equal(events.length,1);});
test('close is prevented if local recovery cannot be persisted',async()=>{const {api,root,calls,events}=bridge(()=>true);await api.ready;root.ASMachRecovery={dirty:()=>true,flush:async()=>false};await api.close();assert.ok(!calls.some(c=>c.name==='close_application'));assert.ok(events.length);});
test('production frontend contains no dev server and public setup uses the small WebView bootstrapper',()=>{const config=JSON.parse(fs.readFileSync('src-tauri/tauri.conf.json'));assert.equal(config.bundle.windows.webviewInstallMode.type,'embedBootstrapper');assert.equal(config.build.frontendDist,'../dist-desktop');assert.ok(!JSON.stringify(config.app.security).includes("'unsafe-eval'"));assert.ok(config.app.security.csp.includes("object-src 'none'"));});
