'use strict';
const token=location.hash.slice(1);history.replaceState(null,'',location.pathname);const $=id=>document.getElementById(id);let records=[],renewedFrom=null,pendingId=null,messageTimer,cloud={configured:false},amendId,release=null,installations={},versionRequest=0,managerVersion='';
function notify(text,error=false){$('message').textContent=text;$('message').className=error?'error':'';$('message').hidden=false;clearTimeout(messageTimer);messageTimer=setTimeout(()=>$('message').hidden=true,10000);}
async function api(url,data){if(url==='issue')data={...data,binding:renewedFrom?(records.find(r=>r.licenseId===renewedFrom)?.binding||''):$('binding').value};const r=await fetch('/api/'+url,{method:data===undefined?'GET':'POST',headers:{Authorization:'Bearer '+token,...(data!==undefined?{'Content-Type':'application/json'}:{})},body:data===undefined?undefined:JSON.stringify(data)});if(!r.ok){const e=await r.json();throw Error(e.error||'İşlem tamamlanamadı.');}return r.json();}
function localDate(d){return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);}
function addMonths(d,n){const out=new Date(d),day=out.getDate();out.setDate(1);out.setMonth(out.getMonth()+n);out.setDate(Math.min(day,new Date(out.getFullYear(),out.getMonth()+1,0).getDate()));return out;}
function reset(){renewedFrom=null;$('licenseForm').reset();bindingFields();$('binding').disabled=false;$('deviceId').readOnly=false;$('startsAt').value=localDate(new Date());$('expiresAt').value=localDate(addMonths(new Date(),12));$('formTitle').textContent='Yeni lisans';$('create').textContent='Lisans oluştur';}
const date=s=>new Date(s*1000).toLocaleString('tr-TR',{dateStyle:'medium',timeStyle:'short'});
function el(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
function versionParts(value){const m=String(value||'').match(/^(\d+)\.(\d+)\.(\d+)/);return m?m.slice(1).map(Number):null;}
function compareVersions(a,b){const x=versionParts(a),y=versionParts(b);if(!x||!y)return 0;for(let i=0;i<3;i++)if(x[i]!==y[i])return x[i]-y[i];return 0;}
function versionState(r){const seen=installations[r.licenseId];if(!seen?.appVersion)return{label:'Sürüm bilinmiyor',cls:'unknown',detail:seen?.error?'Bulut bilgisi alınamadı':'Sürüm bildiren paketi henüz çalıştırmadı'};if(!release)return{label:'v'+seen.appVersion,cls:'unknown',detail:'Yayın sürümü tanımlı değil'};if(compareVersions(seen.appVersion,release.version)<0)return{label:'Yeni sürüm mevcut',cls:'update',detail:'v'+seen.appVersion+' → v'+release.version};return{label:'Güncel · v'+seen.appVersion,cls:'',detail:'Son bağlantı: '+date(seen.checkedAt)};}
function draw(){const q=$('search').value.toLocaleLowerCase('tr'),status=$('status').value,filtered=records.filter(r=>(!status||r.status===status)&&[r.customer,r.deviceId,r.licenseId,r.licenseNumber,r.activationKey].join(' ').toLocaleLowerCase('tr').includes(q));$('rows').replaceChildren();$('empty').hidden=filtered.length>0;
for(const r of filtered){
 const tr=el('tr'),customer=el('td');customer.append(el('div',r.customer,'customer'));
 const id=el('div',r.deviceId||'Bilgisayar kimliği ilk çevrimiçi etkinleştirmede alınacak','sub');id.title=r.deviceId||'';customer.append(id);
 const lid=el('div',r.licenseId,'sub');lid.title='Lisans kimliği';customer.append(lid,el('div',r.licenseNumber||'','sub'));
 const methods=el('div',undefined,'delivery-methods');
 methods.append(el('span',r.activationKey?'Çevrimiçi anahtar hazır':'Çevrimiçi anahtar yok','method '+(r.activationKey?'ready':'muted')));
 methods.append(el('span',r.deviceId?'Çevrimdışı kod hazır':'Çevrimdışı kod için kimlik gerekli','method '+(r.deviceId?'ready':'muted')));
 methods.append(el('span',r.deviceId?'Lisans dosyası hazır':'Lisans dosyası için kimlik gerekli','method '+(r.deviceId?'ready':'muted')));customer.append(methods);
 if(r.note){const n=el('div',r.note,'sub');n.title=r.note;customer.append(n);}
 const state=el('td');state.append(el('span',r.status,'badge '+(r.revocationRequested?'pending':r.status==='Süresi doldu'?'expired':r.status==='Başlamadı'?'future':'')));
 const version=versionState(r),versionCell=el('td',undefined,'version-cell');versionCell.append(el('span',version.label,'badge '+version.cls),el('div',version.detail,'sub'));
 const actions=el('td'),buttons=el('div',undefined,'actions');
 const choices=[
  {text:'Detay',fn:()=>showDetail(r.licenseId)},
  {text:'Çevrimiçi anahtarı göster',fn:()=>showOnlineKey(r),disabled:!r.activationKey,title:'Bu kayıt çevrimdışı bilgisayar kimliğine bağlı oluşturuldu.'},
  {text:'Çevrimdışı kodu göster',fn:()=>showOfflineCode(r.licenseId),disabled:!r.deviceId,title:'Önce uygulamada gösterilen bilgisayar kimliğine bağlı lisans oluşturun.'},
  {text:'Lisans dosyasını indir',fn:()=>download(r.licenseId),disabled:!r.deviceId,title:'Lisans dosyası için bilgisayar kimliğine bağlı lisans gerekir.'},
  {text:'Lisans dosyasını kaydet',fn:async()=>{const out=await api('save',{id:r.licenseId});notify('Lisans kaydedildi:\n'+out.path);await refresh();},disabled:!r.deviceId,title:'Lisans dosyası için bilgisayar kimliğine bağlı lisans gerekir.'},
  {text:'Yenile',fn:()=>renew(r)},
  {text:'Buluta gönder',fn:async()=>{const out=await api('publish',{id:r.licenseId});notify(out.message);await refresh();},disabled:!cloud.configured||r.cloudRevoked,title:'Önce Bulut ayarlarından hizmeti bağlayın.'},
  {text:'Süreyi değiştir',fn:()=>{amendId=r.licenseId;$('amendOwner').textContent=r.customer;$('amendExpiry').value=localDate(new Date(r.expiresAt*1000));$('amendDialog').showModal();},disabled:r.cloudRevoked},
  {text:'Devre dışı bırak',fn:()=>{pendingId=r.licenseId;$('confirmText').textContent=r.customer+' · '+r.licenseId;$('confirm').showModal();$('cancel').focus();},disabled:!cloud.configured||r.cloudRevoked,title:cloud.configured?'Müşteri başarılı çevrimiçi doğrulamada uygular.':'Önce Bulut ayarlarından hizmeti bağlayın.'}
 ];
 for(const choice of choices){const b=el('button',choice.text);b.disabled=!!choice.disabled;if(b.disabled&&choice.title)b.title=choice.title;b.onclick=()=>Promise.resolve().then(choice.fn).catch(e=>notify(e.message,true));buttons.append(b);}
 actions.append(buttons);tr.append(customer,el('td',date(r.expiresAt)),state,versionCell,actions);$('rows').append(tr);
}
const now=Date.now()/1000;$('total').textContent=records.length;$('active').textContent=records.filter(r=>r.status==='Aktif').length;$('pending').textContent=records.filter(r=>r.cloudRevoked).length;$('soon').textContent=records.filter(r=>r.status==='Aktif'&&r.expiresAt-now<=30*86400).length;
$('outdated').textContent=records.filter(r=>['update','required'].includes(versionState(r).cls)).length;
}
function historyDetail(r){if(r.action==='Kullanıcı bilgileri güncellendi'){try{const d=JSON.parse(r.detail),labels={company:'Firma',contact:'Yetkili',email:'E-posta',phone:'Telefon',notes:'Notlar'};return Object.keys(labels).filter(k=>d.previous[k]!==d.current[k]).map(k=>labels[k]+': '+(d.previous[k]||'—')+' → '+(d.current[k]||'—')).join(' · ')||'Bilgiler tekrar kaydedildi';}catch{}}if(r.action==='Süre değiştirildi'){try{const d=JSON.parse(r.detail);return date(d.previous.expiresAt)+' → '+date(d.current.expiresAt)+' · Revizyon '+d.current.revision;}catch{}}return r.detail;}
async function refreshVersions(){const request=++versionRequest;if(!cloud.configured){release=null;installations={};draw();return;}const data=await api('versions');if(request!==versionRequest)return;release=data.release||null;installations=data.installations||{};draw();$('releaseCurrent').textContent=release?'Duyurulan sürüm: '+release.version+'\nYayın: '+new Date(release.pubDate).toLocaleString('tr-TR'):'Henüz duyurulmuş sürüm yok.';}
async function refresh(){const data=await api('list');records=data.licenses;managerVersion=data.appVersion||managerVersion;cloud=data.cloud||{configured:false};document.querySelector('.offline').textContent=cloud.configured?'● Bulut yapılandırıldı':'● Yerel / çevrimdışı';$('cloudNotice').textContent=cloud.configured?'Bulut yapılandırıldı: '+cloud.url+' · Kullanıcı sürümleri ve güncelleme teslimi çevrimiçi izlenir.':'Bulut bağlı değil. Dosya ile lisans yönetimi çalışır; sürüm bilgileri alınamaz.';$('folder').textContent='Lisans klasörü: '+data.exportsDir;draw();void refreshVersions().catch(e=>notify('Sürüm bilgileri alınamadı: '+e.message,true));const events=await api('history');$('history').replaceChildren();for(const r of events){const row=el('div',undefined,'event');const owner=records.find(l=>l.licenseId===r.license_id)?.customer||'';row.append(el('span',date(r.at)),el('strong',r.action),el('span',owner+' · '+historyDetail(r)));$('history').append(row);}}
function renew(r){if(r.cloudRevoked)throw Error('İptal edilen lisans uzatılamaz.');amendId=r.licenseId;$('amendOwner').textContent=r.customer+' · Aynı lisans kimliği korunacak';$('amendExpiry').value=localDate(addMonths(new Date(Math.max(Date.now(),r.expiresAt*1000)),12));$('amendDialog').showModal();$('amendExpiry').focus();}
function saveBlob(blob,name){const url=URL.createObjectURL(blob),a=el('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);}
function showCode(title,code,detail){$('codeTitle').textContent=title;$('codeValue').value=code;$('codeDetail').textContent=detail;$('codeDialog').showModal();$('codeValue').focus();$('codeValue').select();}
function showOnlineKey(r){showCode('Çevrimiçi lisans anahtarı',r.activationKey,'Lisans: '+r.licenseNumber+' · Bitiş: '+date(r.expiresAt)+'\nBu anahtar ilk bilgisayarda internet üzerinden etkinleştirilir.');}
async function showOfflineCode(id){const out=await api('offline-code',{id});showCode('Çevrimdışı etkinleştirme kodu',out.code,'Lisans: '+out.licenseNumber+' · Bilgisayar: '+out.deviceId+' · Bitiş: '+date(out.expiresAt));}
async function download(id){const r=await fetch('/api/download?id='+encodeURIComponent(id),{headers:{Authorization:'Bearer '+token}});if(!r.ok)throw Error('Lisans indirilemedi.');saveBlob(await r.blob(),'Lisans-'+id+'.asmach-license');}
$('licenseForm').onsubmit=async e=>{e.preventDefault();$('create').disabled=true;try{const result=await api('issue',{customer:$('customer').value,deviceId:$('deviceId').value,startsAt:new Date($('startsAt').value).toISOString(),expiresAt:new Date($('expiresAt').value).toISOString(),note:$('note').value,renewedFrom});reset();document.getElementById('newLicenseDialog')?.close();await refresh();if(result.activationKey){notify('Lisans oluşturuldu.\nNumara: '+result.licenseNumber+'\nAnahtar: '+result.activationKey+'\n'+(result.message||''),!result.published);return;}try{const out=await api('save',{id:result.licenseId});notify('Lisans oluşturuldu ve kaydedildi:\n'+out.path+'\n'+(result.message||''),cloud.configured&&!result.published);await refresh();}catch(err){notify('Lisans oluşturuldu ancak dosya kaydedilemedi. Kayıttan tekrar kaydedebilirsiniz. '+err.message,true);}}catch(err){notify(err.message,true);}finally{$('create').disabled=false;}};
$('reset').onclick=reset;$('search').oninput=draw;$('status').onchange=draw;$('refresh').onclick=()=>refresh().catch(e=>notify(e.message,true));document.querySelectorAll('[data-months]').forEach(b=>b.onclick=()=>{const old=records.find(r=>r.licenseId===renewedFrom);const start=new Date($('startsAt').value);$('expiresAt').value=localDate(addMonths(new Date(Math.max(start.getTime(),old?old.expiresAt*1000:0)),Number(b.dataset.months)));});
$('cancel').onclick=()=>$('confirm').close();$('confirmRevoke').onclick=async()=>{$('confirmRevoke').disabled=true;try{await api('revoke',{id:pendingId});$('confirm').close();await refresh();notify('İptal buluta yayımlandı. Müşteri başarılı çevrimiçi doğrulamada devre dışı kalacak.');}catch(e){notify(e.message,true);}finally{$('confirmRevoke').disabled=false;}};
$('cloudSettings').onclick=()=>{$('cloudUrl').value=cloud.url||'';$('cloudToken').value='';$('cloudDialog').showModal();};$('cloudCancel').onclick=()=>$('cloudDialog').close();$('cloudForm').onsubmit=async e=>{e.preventDefault();$('cloudSave').disabled=true;try{await api('cloud',{url:$('cloudUrl').value,token:$('cloudToken').value});$('cloudToken').value='';$('cloudDialog').close();await refresh();notify('Cloudflare bağlantısı doğrulandı. Güncel uygulama aynı lisansın süre değişikliklerini otomatik alır.');}catch(err){notify(err.message,true);}finally{$('cloudSave').disabled=false;}};
$('releaseSettings').onclick=()=>{if(!cloud.configured){notify('Önce Cloudflare bağlantısını yapılandırın.',true);return;}const suggested=managerVersion||'1.0.0';$('releaseVersion').value=release?.version||suggested;$('releaseNotes').value=release?.notes||'';$('releaseDialog').showModal();};$('releaseCancel').onclick=()=>$('releaseDialog').close();$('releaseForm').onsubmit=async e=>{e.preventDefault();$('releaseSave').disabled=true;try{const result=await api('release',{version:$('releaseVersion').value,minimumVersion:'0.0.0',target:'windows',arch:'x86_64',notes:$('releaseNotes').value,pubDate:new Date().toISOString()});release=result.release;$('releaseDialog').close();await refreshVersions();notify('Sürüm '+release.version+' duyuruldu. Uygulamalar yeni sürüm bilgisini gösterecek; kurulum dosyası otomatik indirilmez.');}catch(err){notify(err.message,true);}finally{$('releaseSave').disabled=false;}};
$('amendCancel').onclick=()=>$('amendDialog').close();$('amendForm').onsubmit=async e=>{e.preventDefault();$('amendSave').disabled=true;try{const result=await api('amend',{id:amendId,expiresAt:new Date($('amendExpiry').value).toISOString()});$('amendDialog').close();await refresh();notify(result.message,!result.published&&cloud.configured);}catch(err){notify(err.message,true);}finally{$('amendSave').disabled=false;}};
$('exportRevocations').hidden=true;$('status').append(el('option','İptal edildi'));
$('exportRevocations').onclick=async()=>{try{saveBlob(new Blob([JSON.stringify(await api('revocations'),null,2)],{type:'application/json'}),'asmach-bekleyen-iptaller.json');notify('Bu dosya yalnızca aktarım içindir; iptaller henüz yayımlanmadı.');}catch(e){notify(e.message,true);}};
$('codeClose').onclick=()=>$('codeDialog').close();$('codeCopy').onclick=async()=>{try{await navigator.clipboard.writeText($('codeValue').value);notify('Kod panoya kopyalandı.');}catch{$('codeValue').focus();$('codeValue').select();notify('Kod seçildi. Ctrl+C ile kopyalayabilirsiniz.',true);}};
$('closeApp').onclick=async()=>{try{await api('close',{});document.body.replaceChildren(el('main','Lisans yönetimi kapatıldı. Bu pencereyi kapatabilirsiniz.'));window.close();}catch(e){notify(e.message,true);}};
setInterval(()=>api('heartbeat',{}).catch(()=>{}),45000);reset();refresh().catch(e=>notify(e.message,true));
const newDialog=el('dialog');newDialog.id='newLicenseDialog';const editor=document.querySelector('.editor'),newClose=el('button','Kapat');newClose.type='button';newClose.onclick=()=>newDialog.close();editor.querySelector('.heading').append(newClose);newDialog.append(editor);document.body.append(newDialog);
const add=el('button','＋ Yeni lisans','primary');add.id='addLicense';add.onclick=()=>{reset();newDialog.showModal();$('customer').focus();};document.querySelector('.records .heading').append(add);
const details=el('dialog');details.id='userDetail';details.innerHTML='<div class="heading"><h2>Kullanıcı ve lisans detayı</h2><button type="button" data-detail-close>Kapat</button></div><div class="detail-body"><h3 data-owner></h3><div data-license-info></div><form id="userForm"><div class="profile-grid"><label>Firma<input name="company" maxlength="200"></label><label>Yetkili kişi<input name="contact" maxlength="200"></label><label>E-posta<input name="email" type="email" maxlength="200"></label><label>Telefon<input name="phone" maxlength="200"></label></div><label>Kullanıcı notları<textarea name="notes" maxlength="2000"></textarea></label><small>İletişim bilgileri yalnızca yönetici bilgisayarında tutulur; otomatik olarak buluta gönderilmez.</small><button class="primary">Kullanıcı bilgilerini kaydet</button></form><h3>Kullanıcının lisansları</h3><div data-user-licenses></div><h3>Buluttaki bilgiler <button type="button" data-cloud-refresh>Buluttan yenile</button></h3><pre data-cloud-info>Henüz sorgulanmadı.</pre><p data-detail-status role="status"></p><h3>Bu lisansın işlem geçmişi</h3><div data-license-history class="detail-history"></div><h3>Kullanıcının tüm işlem geçmişi</h3><div data-user-history class="detail-history"></div></div>';document.body.append(details);details.querySelector('[data-detail-close]').onclick=()=>details.close();let detailId,detailUserId;
function renderHistory(target,items){target.replaceChildren();if(!items.length){target.textContent='Henüz işlem yok.';return;}for(const h of items){const row=el('div',undefined,'event');row.append(el('span',date(h.at)),el('strong',h.action),el('span',historyDetail(h)));target.append(row);}}
async function showDetail(id){detailId=id;const d=await api('detail?id='+encodeURIComponent(id));if(detailId!==id)return;detailUserId=d.user.id;details.querySelector('[data-owner]').textContent=d.user.name;details.querySelector('[data-license-info]').textContent='Lisans: '+id+' · '+d.license.status+' · Revizyon '+d.license.revision+' · Bitiş: '+date(d.license.expiresAt)+' · Bilgisayar: '+d.license.deviceId;for(const field of ['company','contact','email','phone','notes'])$('userForm').elements[field].value=d.user[field]||'';const related=details.querySelector('[data-user-licenses]');related.replaceChildren();for(const l of d.licenses){const b=el('button',l.licenseId.slice(0,8)+' · '+l.status+' · '+date(l.expiresAt));b.onclick=()=>showDetail(l.licenseId).catch(e=>notify(e.message,true));related.append(b);}renderHistory(details.querySelector('[data-license-history]'),d.licenseHistory);renderHistory(details.querySelector('[data-user-history]'),d.userHistory);details.querySelector('[data-detail-status]').textContent='';details.querySelector('[data-cloud-info]').textContent='Bulut sorgulanıyor…';if(!details.open)details.showModal();await refreshCloudDetail(id);}
async function refreshCloudDetail(id=detailId){const box=details.querySelector('[data-cloud-info]');try{const d=await api('cloud-detail',{id});if(detailId!==id)return;const l=d.license,seen=d.lastCheck;installations[id]=seen||null;box.textContent='Sorgu: '+date(d.checkedAt)+'\nDurum: '+({active:'Aktif kayıt',revoked:'İptal edildi',missing:'Bulutta bulunamadı'}[d.status]||d.status)+'\nKurulu uygulama: '+(seen?.appVersion?'v'+seen.appVersion:'Bilinmiyor · sürüm bildiren paketi henüz çalıştırmadı')+'\nGüncelleme durumu: '+versionState({licenseId:id}).label+'\nSon cihaz doğrulaması: '+(seen?date(seen.checkedAt):'Henüz cihaz onayı yok')+(d.status==='revoked'?'\nİptal teslimi: '+(seen?.status==='revoked'?'Cihaz iptali aldı ve kaydetti':'Cihazdan alındı onayı bekleniyor'):'')+'\nKontrol aralığı: 30 dakika · Bağlantı hatasında 5 dakika sonra yeniden deneme'+(l?'\nMüşteri: '+l.customer+'\nLisans: '+l.licenseId+'\nLisans numarası: '+(l.licenseNumber||'—')+'\nBilgisayar: '+(d.activation?.deviceId||l.deviceId||'İlk etkinleştirme bekleniyor')+'\nİlk etkinleştirme: '+(d.activation?.activatedAt?date(d.activation.activatedAt):'Henüz etkinleştirilmedi')+'\nRevizyon: '+l.revision+'\nBaşlangıç: '+date(l.notBefore)+'\nBitiş: '+date(l.expiresAt)+(l.expiresAt<Date.now()/1000?' (Süresi doldu)':''):'');}catch(e){if(detailId===id)box.textContent='Bulut bilgileri alınamadı: '+e.message+'\nYerel kayıtlar değiştirilmedi.';}}
details.querySelector('[data-cloud-refresh]').onclick=()=>refreshCloudDetail();$('userForm').onsubmit=async e=>{e.preventDefault();try{const data=Object.fromEntries(new FormData(e.target));await api('user',{...data,id:detailUserId});await showDetail(detailId);details.querySelector('[data-detail-status]').textContent='Kullanıcı bilgileri kaydedildi; işlem geçmişine eklendi.';await refresh();}catch(err){details.querySelector('[data-detail-status]').textContent=err.message;}};
function bindingFields(){const first=$('binding').value==='first-device';$('deviceId').required=!first;$('deviceId').disabled=first;$('deviceId').closest('label').hidden=first;$('bindingHint').textContent=first?'Çevrimiçi lisans ilk bilgisayarda anahtarla etkinleştirilir. İnternet bağlantısı gerekir.':'Bilgisayar kimliğine bağlı lisans için hem çevrimdışı kod hem de indirilebilir lisans dosyası hazırlanır.';} $('binding').addEventListener('change',bindingFields);bindingFields();
