'use strict';
// Presentation-only detail workspace; existing authenticated APIs remain unchanged.
(()=>{
 const host=document.getElementById('userDetail'),form=document.getElementById('userForm');
 const save=form.querySelector('button'),status=host.querySelector('[data-detail-status]');
 const fields=['company','contact','email','phone','notes'];let current=null,baseline='',sequence=0,cloudSequence=0,saving=false,activeTab='contact';
 const values=()=>Object.fromEntries(fields.map(k=>[k,form.elements[k].value]));
 const dirty=()=>current&&JSON.stringify(values())!==baseline;
 const allowLeave=()=>!dirty()||window.confirm('Kaydedilmemiş müşteri bilgileri var. Değişiklikleri bırakmak istiyor musunuz?');
 host.classList.add('customer-workspace');host.setAttribute('aria-labelledby','customerDetailTitle');
 const header=el('div',undefined,'customer-topbar'),title=el('h2','Müşteri detayı');title.id='customerDetailTitle';const close=el('button','Kapat');close.dataset.detailClose='';const downloadSelected=el('button','Lisans dosyasını indir','primary');downloadSelected.disabled=true;downloadSelected.onclick=async()=>{if(!current)return;const id=current.license.licenseId;downloadSelected.disabled=true;try{await download(id);}catch(e){notify(e.message,true);}finally{downloadSelected.disabled=!current?.license.deviceId;}};const headerActions=el('div',undefined,'customer-topbar-actions');headerActions.append(downloadSelected,close);header.append(title,headerActions);
 const hero=el('div',undefined,'customer-hero'),avatar=el('div',undefined,'customer-avatar'),identity=el('div',undefined,'customer-identity'),name=el('h3'),subtitle=el('p'),badge=el('span');name.dataset.owner='';identity.append(name,subtitle);hero.append(avatar,identity,badge);
 const summary=el('div',undefined,'customer-summary'),tabs=el('div',undefined,'customer-tabs');tabs.setAttribute('role','tablist');tabs.setAttribute('aria-label','Müşteri detay bölümleri');
 const scroll=el('div',undefined,'customer-scroll'),panels={},buttons={};
 for(const [id,label] of [['contact','İletişim'],['licenses','Lisanslar'],['cloud','Bulut ve cihaz'],['history','İşlem geçmişi']]){const b=el('button',label),p=el('section',undefined,'customer-tab-panel');b.id='customer-tab-'+id;b.setAttribute('role','tab');b.setAttribute('aria-controls','customer-panel-'+id);b.onclick=()=>selectTab(id);p.id='customer-panel-'+id;p.setAttribute('role','tabpanel');p.setAttribute('aria-labelledby',b.id);tabs.append(b);scroll.append(p);panels[id]=p;buttons[id]=b;}
 const footer=el('div',undefined,'customer-footer');save.setAttribute('form','userForm');save.type='submit';status.className='customer-save-status';footer.append(status,save);
 const contactHeading=el('div',undefined,'customer-section-heading');contactHeading.append(el('h3','İletişim bilgileri'),el('p','Firma ve yetkili bilgilerini bu müşteri için düzenleyin.'));panels.contact.append(contactHeading,form);
 const licenses=el('div',undefined,'customer-license-list');licenses.dataset.userLicenses='';panels.licenses.append(el('h3','Müşterinin lisansları'),el('p','İncelemek istediğiniz lisansı seçin. Müşteri iletişim bilgileri ortak kalır.','muted'),licenses);
 const cloudHeading=el('div',undefined,'customer-section-heading'),cloudRefresh=el('button','Buluttan yenile');cloudRefresh.dataset.cloudRefresh='';cloudHeading.append(el('h3','Bulut ve cihaz durumu'),cloudRefresh);const cloudBody=el('div');cloudBody.dataset.cloudInfo='';panels.cloud.append(cloudHeading,cloudBody);
 const historySelect=el('select');historySelect.setAttribute('aria-label','Detay geçmiş kapsamı');for(const [v,t] of [['license','Seçili lisansın geçmişi'],['user','Müşterinin tüm geçmişi']]){const o=el('option',t);o.value=v;historySelect.append(o);}const licenseHistory=el('div',undefined,'customer-timeline'),userHistory=el('div',undefined,'customer-timeline');licenseHistory.dataset.licenseHistory='';userHistory.dataset.userHistory='';panels.history.append(el('h3','İşlem geçmişi'),historySelect,licenseHistory,userHistory);historySelect.onchange=()=>{licenseHistory.hidden=historySelect.value!=='license';userHistory.hidden=historySelect.value!=='user';};historySelect.onchange();
 host.replaceChildren(header,hero,summary,tabs,scroll,footer);
 function selectTab(id){activeTab=id;for(const key of Object.keys(panels)){panels[key].hidden=key!==id;buttons[key].setAttribute('aria-selected',String(key===id));buttons[key].tabIndex=key===id?0:-1;}footer.hidden=id!=='contact';scroll.scrollTop=0;}
 tabs.addEventListener('keydown',e=>{const keys=Object.keys(buttons),i=keys.indexOf(activeTab);let n;if(e.key==='ArrowRight')n=(i+1)%keys.length;if(e.key==='ArrowLeft')n=(i+keys.length-1)%keys.length;if(e.key==='Home')n=0;if(e.key==='End')n=keys.length-1;if(n!==undefined){e.preventDefault();selectTab(keys[n]);buttons[keys[n]].focus();}});
 function setStatus(text,error=false){status.textContent=text;status.classList.toggle('error-text',error);}
 form.addEventListener('input',()=>{if(!saving)setStatus(dirty()?'Kaydedilmemiş değişiklikler var.':'Bilgiler güncel.');});
 close.onclick=()=>{if(!saving&&allowLeave())host.close();};host.addEventListener('cancel',e=>{if(saving||!allowLeave())e.preventDefault();});host.addEventListener('close',()=>{sequence++;cloudSequence++;current=null;baseline='';});
 function cell(label,value){const box=el('div',undefined,'customer-metric');box.append(el('span',label),el('strong',value||'—'));return box;}
 function info(label,value,copy=false){const row=el('div',undefined,'customer-info-row'),text=el('span',value||'Bilgi yok');row.append(el('span',label),text);if(copy&&value){text.classList.add('customer-code');const b=el('button','Kopyala');b.setAttribute('aria-label',label+' kopyala');b.onclick=async()=>{try{await navigator.clipboard.writeText(value);b.textContent='Kopyalandı';}catch{notify('Kopyalanamadı. Metni seçip Ctrl+C kullanabilirsiniz.',true);}};row.append(b);}return row;}
 function timeline(target,items){target.replaceChildren();if(!items.length){target.append(el('p','Henüz işlem kaydı yok.','customer-empty'));return;}for(const h of items){const row=el('article',undefined,'customer-history-item');row.append(el('time',date(h.at)),el('h4',h.action),el('p',historyDetail(h)));target.append(row);}}
 function render(data){current=data;const l=data.license,u=data.user;name.textContent=u.company||u.name;subtitle.textContent=u.contact||u.name;avatar.textContent=(u.company||u.name||'?').split(/\s+/).slice(0,2).map(s=>s[0]).join('').toLocaleUpperCase('tr');badge.textContent=l.status;badge.className='badge '+(l.cloudRevoked||l.status==='Süresi doldu'?'expired':l.status==='Başlamadı'?'future':'');summary.replaceChildren(cell('Seçili lisans',l.licenseNumber||l.licenseId.slice(0,8)),cell('Bitiş tarihi',date(l.expiresAt)),cell('Müşterinin lisansları',data.licenses.length+' kayıt · '+data.licenses.filter(r=>r.status==='Aktif').length+' aktif'));
  downloadSelected.disabled=!l.deviceId;downloadSelected.title=l.deviceId?'Seçili lisansın mevcut imzalı dosyasını indirir.':'Dosya indirmek için bilgisayar kimliğine bağlı bir lisans gerekir.';
  for(const k of fields)form.elements[k].value=u[k]||'';baseline=JSON.stringify(values());detailId=l.licenseId;detailUserId=u.id;setStatus('Bilgiler güncel.');
  licenses.replaceChildren();for(const r of data.licenses){const item=el('div',undefined,'customer-license-item'),card=el('button',undefined,'customer-license-card');card.classList.toggle('is-current',r.licenseId===l.licenseId);card.setAttribute('aria-pressed',String(r.licenseId===l.licenseId));const line=el('div'),pill=el('span',r.status,'badge '+(r.cloudRevoked||r.status==='Süresi doldu'?'expired':''));line.append(el('strong',r.licenseNumber||r.licenseId.slice(0,8)),pill);card.append(line,el('span','Bitiş: '+date(r.expiresAt)),el('small',r.licenseId===l.licenseId?'Seçili lisans · Revizyon '+(r.revision||1):'Ayrıntılarını görüntüle'));card.onclick=()=>showDetail(r.licenseId).catch(e=>notify(e.message,true));item.append(card);if(r.deviceId){const file=el('button','Dosyayı indir');file.setAttribute('aria-label',(r.licenseNumber||r.licenseId)+' dosyasını indir');file.onclick=async()=>{file.disabled=true;try{await download(r.licenseId);}catch(e){notify(e.message,true);}finally{file.disabled=false;}};item.append(file);}else item.append(el('small','Dosya için bilgisayar kimliği gerekli.','muted'));licenses.append(item);}
  const technical=el('details',undefined,'customer-technical');technical.append(el('summary','Seçili lisansın teknik bilgileri'),info('Lisans kimliği',l.licenseId,true),info('Bilgisayar kimliği',l.deviceId||'',!!l.deviceId),info('Başlangıç',date(l.notBefore)),info('Revizyon',String(l.revision||1)));licenses.append(technical);
  timeline(licenseHistory,data.licenseHistory);timeline(userHistory,data.userHistory);buttons.licenses.textContent='Lisanslar ('+data.licenses.length+')';
 }
 showDetail=async id=>{if(saving)return;if(current&&!allowLeave())return;const request=++sequence;const wasOpen=host.open;const data=await api('detail?id='+encodeURIComponent(id));if(request!==sequence)return;render(data);if(!wasOpen)selectTab('contact');if(!host.open)host.showModal();void refreshCloudDetail(id);};
 refreshCloudDetail=async(id=detailId)=>{const request=++cloudSequence;cloudBody.replaceChildren(el('p','Bulut bilgileri kontrol ediliyor…','customer-empty'));cloudRefresh.disabled=true;try{
  if(!cloud.configured){cloudBody.replaceChildren(el('div','Bulut bağlantısı yapılandırılmamış. Yerel müşteri bilgilerini düzenlemeye devam edebilirsiniz.','customer-empty'));return;}
  const d=await api('cloud-detail',{id});if(request!==cloudSequence||current?.license.licenseId!==id)return;const l=d.license,seen=d.lastCheck;installations[id]=seen||null;cloudBody.replaceChildren();const grid=el('div',undefined,'customer-cloud-cards');grid.append(cell('Bulut kaydı',({active:'Aktif',revoked:'İptal edildi',missing:'Bulutta bulunamadı'})[d.status]||'Bilinmiyor'),cell('Kurulu uygulama',seen?.appVersion?'v'+seen.appVersion:'Sürüm bilgisi yok'),cell('Son cihaz onayı',seen?.checkedAt?date(seen.checkedAt):'Henüz onay yok'),cell('Son sorgulama',d.checkedAt?date(d.checkedAt):'Bilgi yok'));cloudBody.append(grid,el('p','Cihaz onayı olmaması, bilgisayarın çevrimdışı olduğunu veya güncellemenin uygulandığını göstermez.','muted'));if(d.status==='revoked')cloudBody.append(info('İptal teslimi',seen?.status==='revoked'?'Cihaz iptali onayladı':'Cihaz onayı bekleniyor'));if(l){cloudBody.append(info('Buluttaki bitiş',date(l.expiresAt)),info('Bulut revizyonu',String(l.revision||1)),info('İlk etkinleştirme',d.activation?.activatedAt?date(d.activation.activatedAt):'Bilgi yok'));const tech=el('details',undefined,'customer-technical');tech.append(el('summary','Buluttaki kimlik bilgileri'),info('Lisans kimliği',l.licenseId,true),info('Bilgisayar kimliği',d.activation?.deviceId||l.deviceId||'',true));cloudBody.append(tech);}
  cloudBody.insertBefore(info('Güncelleme durumu',versionState({licenseId:id}).label),cloudBody.children[1]);
  const technical=cloudBody.querySelector('.customer-technical');if(l&&technical)technical.append(info('Buluttaki müşteri',l.customer),info('Lisans numarası',l.licenseNumber),info('Başlangıç',date(l.notBefore)));
  cloudBody.append(el('p','Kontrol aralığı: 30 dakika · Bağlantı hatasında 5 dakika sonra yeniden deneme.','muted'));
 }catch(e){if(request===cloudSequence&&current?.license.licenseId===id)cloudBody.replaceChildren(el('p','Bulut bilgileri alınamadı. '+e.message,'error-text'),el('p','Yerel kayıtlar değiştirilmedi. Yeniden deneyebilirsiniz.','muted'));}finally{if(request===cloudSequence)cloudRefresh.disabled=false;}};
 cloudRefresh.onclick=()=>refreshCloudDetail();
 form.onsubmit=async e=>{e.preventDefault();if(saving||!current)return;const userId=current.user.id,licenseId=current.license.licenseId,payload=values();saving=true;save.disabled=close.disabled=true;for(const c of form.elements)c.disabled=true;setStatus('Kaydediliyor…');try{await api('user',{...payload,id:userId});const data=await api('detail?id='+encodeURIComponent(licenseId));render(data);setStatus('Kullanıcı bilgileri kaydedildi; işlem geçmişine eklendi.');await refresh();}catch(err){setStatus(err.message,true);}finally{saving=false;save.disabled=close.disabled=false;for(const c of form.elements)c.disabled=false;}};
 selectTab('contact');
})();
