'use strict';
// The existing license delivery/activation functions remain the authoritative actions.
const managerState={page:'overview',pageNumber:1,pageSize:20,selected:new Set(),data:{customers:[],history:[],publication:[],requests:[]},ready:false,filter:'all',sort:'expiry',direction:1,columns:{number:true,version:true,sync:true},historyPage:1,knownRequests:new Set()};
try{const saved=JSON.parse(localStorage.getItem('asmach-manager-view')||'{}');if(['all','7','15','30','expired','waiting','failed','outdated'].includes(saved.filter))managerState.filter=saved.filter;if(['expiry','customer','status'].includes(saved.sort))managerState.sort=saved.sort;if([10,20,50].includes(saved.pageSize))managerState.pageSize=saved.pageSize;if(saved.columns)for(const k of Object.keys(managerState.columns))if(typeof saved.columns[k]==='boolean')managerState.columns[k]=saved.columns[k];}catch{}
const persistView=()=>{try{localStorage.setItem('asmach-manager-view',JSON.stringify({filter:managerState.filter,sort:managerState.sort,pageSize:managerState.pageSize,columns:managerState.columns}));}catch{}};
const main=document.querySelector('main'),recordPanel=document.querySelector('.records'),historyPanel=document.querySelector('.history'),statsPanel=document.querySelector('.stats');
const section=(id,title,description)=>{const s=el('section',undefined,'panel workspace-panel');s.id=id;const h=el('div',undefined,'heading');h.append(el('div',undefined,'section-heading'));h.firstChild.append(el('h2',title),el('p',description,'muted'));s.append(h);main.append(s);return s;};
const sidebar=el('nav',undefined,'manager-nav');sidebar.setAttribute('aria-label','Ana menü');sidebar.append(el('div','YÖNETİM','nav-caption'));document.body.insertBefore(sidebar,main);
const pageNames={overview:'Genel bakış',requests:'Lisans talepleri',customers:'Müşteriler',licenses:'Lisanslar',releases:'Sürümler',history:'İşlem geçmişi',settings:'Ayarlar ve yedek'};let requestNavButton;
for(const [key,name] of Object.entries(pageNames)){const b=el('button',name);b.dataset.page=key;b.onclick=()=>navigate(key);if(key==='requests')requestNavButton=b;sidebar.append(b);}
sidebar.append(el('p','ASMach Inspection\nLisans yönetimi','nav-footer'));
const overview=section('overviewPage','Yönetim özeti','Yaklaşan bitişleri ve ilgilenilmesi gereken kayıtları tek yerden takip edin.');
const requestPage=section('requestsPage','Lisans talepleri','Uygulamadan gönderilen veya talep koduyla aktarılan bilgisayar kimlikleri.');const requestTools=el('div',undefined,'filters'),requestImport=el('button','Talep kodunu içe aktar'),requestRefresh=el('button','Talepleri yenile'),requestInfo=el('span',undefined,'muted');requestTools.append(requestImport,requestRefresh,requestInfo);requestPage.append(requestTools);const requestList=el('div',undefined,'request-list');requestPage.append(requestList);
const customerPage=section('customersPage','Müşteriler','Firma, yetkili ve iletişim bilgileri; müşteriye bağlı tüm lisanslar.');
const releasePage=section('releasesPage','Sürüm takibi','Kurulu sürüm bilgisi yalnızca cihazın son bildirimini gösterir.');
const settingsPage=section('settingsPage','Ayarlar ve güvenli yedek','Bulut bağlantısı, şifreli yedek oluşturma ve kontrollü geri yükleme.');
const overviewCards=el('div',undefined,'overview-cards');overview.append(overviewCards);const attention=el('div',undefined,'attention-list');overview.append(attention);
const customerSearch=el('input');customerSearch.placeholder='Firma, yetkili, e-posta veya telefon ara';customerSearch.setAttribute('aria-label','Müşteri ara');customerSearch.oninput=renderCustomers;customerPage.append(customerSearch);const customerList=el('div',undefined,'customer-list');customerPage.append(customerList);
const releaseInfo=el('div',undefined,'content-pad');releasePage.append(releaseInfo);releasePage.append($('releaseSettings'));$('releaseSettings').textContent='Sürüm duyurusu oluştur';
const settingsContent=el('div',undefined,'content-pad');settingsPage.append(settingsContent);settingsContent.append(el('h3','Bulut bağlantısı'),el('p','Yönetici anahtarı yalnızca bu bilgisayarda tutulur. Bağlantı ayarlarını değiştirmek müşterilerin lisanslarını kendiliğinden değiştirmez.'));settingsContent.append($('cloudSettings'));
const backupCard=el('div',undefined,'backup-card');backupCard.append(el('h3','Şifreli yedek'),el('p','Müşteriler, lisanslar, işlem geçmişi ve imzalama anahtarı parola ile şifrelenir. Parolayı kaybederseniz yedek açılamaz. Bulut yönetici anahtarı ve dışa aktarılmış lisans dosyaları bu yedeğe dahil değildir.'));
const backupPassword=el('input');backupPassword.type='password';backupPassword.autocomplete='new-password';backupPassword.placeholder='En az 12 karakter';const passwordLabel=el('label','Yedek parolası');passwordLabel.append(backupPassword);backupCard.append(passwordLabel);
const backupConfirm=el('input');backupConfirm.type='password';backupConfirm.autocomplete='new-password';const confirmLabel=el('label','Parolayı tekrar girin');confirmLabel.append(backupConfirm);backupCard.append(confirmLabel);
const backupButton=el('button','Şifreli yedeği indir','primary');backupButton.onclick=()=>runButton(backupButton,async()=>{if(backupPassword.value!==backupConfirm.value)throw Error('Parolalar eşleşmiyor.');const out=await api('backup',{password:backupPassword.value});saveBlob(new Blob([JSON.stringify(out.archive)],{type:'application/json'}),out.name);backupPassword.value=backupConfirm.value='';notify('Şifreli yedek indirme işlemi başlatıldı. Dosyayı güvenli bir konumda saklayın.');});backupCard.append(backupButton);settingsContent.append(backupCard);
const restoreCard=el('div',undefined,'backup-card');restoreCard.append(el('h3','Yedeği doğrula ve geri yükle'),el('p','Yalnızca mevcut imzalama anahtarıyla uyumlu yedekler yüklenebilir. Önce içerik sayıları gösterilir; onayınızdan önce kayıtlar değişmez. Mevcut iptalleri geri alan yedekler reddedilir. Anahtar kurtarma ve başka bilgisayara taşıma bu işlemin kapsamı dışındadır.'));
const restoreFile=el('input');restoreFile.type='file';restoreFile.accept='.asm-backup';restoreFile.setAttribute('aria-label','Şifreli yedek dosyası');const restorePassword=el('input');restorePassword.type='password';restorePassword.autocomplete='off';restorePassword.setAttribute('aria-label','Yedek parolası');restorePassword.placeholder='Yedeğin parolası';restoreCard.append(restoreFile,restorePassword);const restoreButton=el('button','Yedeği doğrula');restoreCard.append(restoreButton);settingsContent.append(restoreCard);
const quickFilter=el('select');quickFilter.setAttribute('aria-label','Hızlı filtre');for(const [v,t] of [['all','Tüm kayıtlar'],['7','7 gün içinde bitecek'],['15','15 gün içinde bitecek'],['30','30 gün içinde bitecek'],['expired','Süresi dolanlar'],['waiting','Etkinleştirme bekleyen'],['failed','Gönderim hatası olan'],['outdated','Eski sürüm bildiren']]){const o=el('option',t);o.value=v;quickFilter.append(o);}quickFilter.value=managerState.filter;
const sortSelect=el('select');sortSelect.setAttribute('aria-label','Sıralama');for(const [v,t] of [['expiry','Bitiş tarihine göre'],['customer','Müşteriye göre'],['status','Duruma göre']]){const o=el('option',t);o.value=v;sortSelect.append(o);}sortSelect.value=managerState.sort;
const sortDirection=el('button','↑');sortDirection.title='Sıralama yönünü değiştir';sortDirection.setAttribute('aria-label','Sıralama yönünü değiştir');sortDirection.onclick=()=>{managerState.direction*=-1;sortDirection.textContent=managerState.direction===1?'↑':'↓';draw();};
const exportButton=el('button','Listeyi dışa aktar');exportButton.onclick=exportList;
const columnMenu=el('details',undefined,'column-menu');columnMenu.append(el('summary','Sütunlar'));for(const [k,t] of [['number','Lisans numarası'],['version','Uygulama sürümü'],['sync','Gönderim durumu']]){const label=el('label',t),c=el('input');c.type='checkbox';c.checked=managerState.columns[k];c.onchange=()=>{managerState.columns[k]=c.checked;persistView();draw();};label.prepend(c);columnMenu.append(label);}
document.querySelector('.filters').append(quickFilter,sortSelect,sortDirection,columnMenu,exportButton);
quickFilter.onchange=()=>{managerState.filter=quickFilter.value;managerState.pageNumber=1;persistView();draw();};sortSelect.onchange=()=>{managerState.sort=sortSelect.value;persistView();draw();};$('search').oninput=$('status').onchange=()=>{managerState.pageNumber=1;draw();};
const bulkBar=el('div',undefined,'bulk-bar'),selectionText=el('span','0 seçili'),bulkExtend=el('button','Seçilenlerin süresini uzat'),bulkPublish=el('button','Seçilenleri yeniden gönder'),clearSelection=el('button','Seçimi temizle');clearSelection.onclick=()=>{managerState.selected.clear();draw();};bulkExtend.onclick=()=>openBulk('extend');bulkPublish.onclick=()=>openBulk('publish');bulkBar.append(selectionText,bulkExtend,bulkPublish,clearSelection);recordPanel.insertBefore(bulkBar,document.querySelector('.tableWrap'));
const pager=el('div',undefined,'pager'),previous=el('button','Önceki'),next=el('button','Sonraki'),pageText=el('span'),pageSize=el('select');pageSize.setAttribute('aria-label','Sayfa başına kayıt');for(const n of [10,20,50]){const o=el('option',n+' kayıt');o.value=n;pageSize.append(o);}pageSize.value=managerState.pageSize;pageSize.onchange=()=>{managerState.pageSize=Number(pageSize.value);managerState.pageNumber=1;persistView();draw();};previous.onclick=()=>{managerState.pageNumber--;draw();};next.onclick=()=>{managerState.pageNumber++;draw();};pager.append(pageText,previous,next,pageSize);recordPanel.append(pager);
const historyFilters=el('div',undefined,'filters'),historyQuery=el('input'),historyAction=el('select'),historyFrom=el('input'),historyTo=el('input');historyQuery.placeholder='Müşteri veya işlem ara';historyQuery.setAttribute('aria-label','Geçmişte ara');historyAction.setAttribute('aria-label','İşlem türü');for(const [c,label] of [[historyFrom,'Başlangıç tarihi'],[historyTo,'Bitiş tarihi']]){c.type='date';c.setAttribute('aria-label',label);c.title=label;}historyFilters.append(historyQuery,historyAction,historyFrom,historyTo);historyPanel.insertBefore(historyFilters,$('history'));historyPanel.querySelector('.heading span').textContent='Filtrelenebilir işlem kayıtları';for(const c of [historyQuery,historyAction,historyFrom,historyTo])c.oninput=()=>{managerState.historyPage=1;renderManagerHistory();};
const historyPager=el('div',undefined,'pager'),historyPrev=el('button','Önceki'),historyNext=el('button','Sonraki'),historyCount=el('span');historyPrev.onclick=()=>{managerState.historyPage--;renderManagerHistory();};historyNext.onclick=()=>{managerState.historyPage++;renderManagerHistory();};historyPager.append(historyCount,historyPrev,historyNext);historyPanel.append(historyPager);
async function runButton(button,fn){button.disabled=true;try{await fn();}catch(e){notify(e.message,true);}finally{button.disabled=false;}}
function navigate(page){managerState.page=page;for(const b of sidebar.querySelectorAll('button')){b.classList.toggle('selected',b.dataset.page===page);if(b.dataset.page===page)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');}overview.hidden=statsPanel.hidden=page!=='overview';requestPage.hidden=page!=='requests';recordPanel.parentElement.hidden=page!=='licenses';customerPage.hidden=page!=='customers';releasePage.hidden=page!=='releases';historyPanel.hidden=page!=='history';settingsPage.hidden=page!=='settings';document.title=pageNames[page]+' · ASMach Lisans Yönetimi';draw();window.scrollTo(0,0);}
function publicationFor(r){return managerState.data.publication.find(p=>p.license_id===r.licenseId);}
function waiting(r){return r.activationMode==='first-device'&&!installations[r.licenseId]?.deviceId;}
function matchesQuick(r,value){const days=(r.expiresAt-Date.now()/1000)/86400;if(['7','15','30'].includes(value))return r.status==='Aktif'&&days>0&&days<=Number(value);if(value==='expired')return r.status==='Süresi doldu';if(value==='waiting')return waiting(r)&&!r.cloudRevoked;if(value==='failed')return !!publicationFor(r)?.error;if(value==='outdated')return versionState(r).cls==='update';return true;}
function filteredRecords(){const q=$('search').value.toLocaleLowerCase('tr'),s=$('status').value;return records.filter(r=>(!s||r.status===s)&&matchesQuick(r,managerState.filter)&&[r.customer,r.licenseId,r.licenseNumber,r.deviceId].join(' ').toLocaleLowerCase('tr').includes(q)).sort((a,b)=>managerState.direction*(managerState.sort==='expiry'?a.expiresAt-b.expiresAt:String(managerState.sort==='customer'?a.customer:a.status).localeCompare(managerState.sort==='customer'?b.customer:b.status,'tr')));}
function openFiltered(filter){managerState.filter=filter;quickFilter.value=filter;$('search').value='';$('status').value='';managerState.pageNumber=1;persistView();navigate('licenses');}
function syncLabel(r){const p=publicationFor(r);if(p?.error)return {text:'Gönderim başarısız',className:'expired',detail:p.error};if(p&&p.revision>=(r.revision||1))return {text:'Buluta gönderildi',className:'',detail:'Revizyon '+p.revision+' · '+date(p.at)};return {text:p?'Gönderim bekliyor':'Gönderim bilgisi yok',className:'unknown',detail:'Yerel revizyon '+(r.revision||1)+' kayıtlı'};}
function actionButton(text,fn,disabled=false){const b=el('button',text);b.disabled=disabled;b.onclick=()=>runButton(b,fn);return b;}
function modal(title){const d=el('dialog',undefined,'manager-dialog');const head=el('div',undefined,'heading');head.append(el('h2',title));const close=el('button','Kapat');close.onclick=()=>d.close();head.append(close);d.append(head);d.addEventListener('close',()=>d.remove());document.body.append(d);return d;}
function openActions(r){const d=modal(r.customer+' · Lisans işlemleri'),body=el('div',undefined,'action-grid');const run=fn=>async()=>{d.close();await fn();};body.append(
 actionButton('Çevrimiçi anahtarı göster',run(()=>showOnlineKey(r)),!r.activationKey),
 actionButton('Çevrimdışı kodu göster',run(()=>showOfflineCode(r.licenseId)),!r.deviceId||r.cloudRevoked),
 actionButton('Lisans dosyasını indir',run(()=>download(r.licenseId)),!r.deviceId),
 actionButton('Lisans dosyasını kaydet',run(async()=>{const o=await api('save',{id:r.licenseId});notify('Dosya kaydedildi: '+o.path);await refresh();}),!r.deviceId),
 actionButton('Süreyi değiştir',run(()=>{amendId=r.licenseId;$('amendOwner').textContent=r.customer+' · Mevcut bitiş: '+date(r.expiresAt);$('amendExpiry').value=localDate(new Date(r.expiresAt*1000));$('amendDialog').showModal();}),r.cloudRevoked),
 actionButton('Buluta yeniden gönder',run(()=>{managerState.selected=new Set([r.licenseId]);openBulk('publish');}),!cloud.configured||r.cloudRevoked),
 actionButton('Devre dışı bırak',run(()=>{pendingId=r.licenseId;$('confirmText').textContent=r.customer+' · '+r.licenseNumber;$('confirm').showModal();$('cancel').focus();}),!cloud.configured||r.cloudRevoked));d.append(body,el('p','Kapalı seçenekler bu lisansın etkinleştirme yönteminde kullanılamaz.','content-pad'));d.showModal();}
function drawManager(){
 const filtered=filteredRecords(),pages=Math.max(1,Math.ceil(filtered.length/managerState.pageSize));managerState.pageNumber=Math.min(pages,Math.max(1,managerState.pageNumber));const visible=filtered.slice((managerState.pageNumber-1)*managerState.pageSize,managerState.pageNumber*managerState.pageSize);for(const id of managerState.selected)if(!records.some(r=>r.licenseId===id&&!r.cloudRevoked&&!r.revocationRequested))managerState.selected.delete(id);
 const head=document.querySelector('.records thead');head.replaceChildren();const hr=el('tr'),selectCell=el('th'),all=el('input');all.type='checkbox';all.setAttribute('aria-label','Bu sayfadaki uygun lisansları seç');const eligible=visible.filter(r=>!r.cloudRevoked&&!r.revocationRequested);all.checked=eligible.length>0&&eligible.every(r=>managerState.selected.has(r.licenseId));all.indeterminate=!all.checked&&eligible.some(r=>managerState.selected.has(r.licenseId));all.onchange=()=>{for(const r of eligible)if(all.checked)managerState.selected.add(r.licenseId);else managerState.selected.delete(r.licenseId);draw();};selectCell.append(all);hr.append(selectCell,el('th','Müşteri / lisans'),el('th','Bitiş'),el('th','Durum'));if(managerState.columns.version)hr.append(el('th','Uygulama'));if(managerState.columns.sync)hr.append(el('th','Gönderim / cihaz'));hr.append(el('th','İşlemler'));head.append(hr);
 $('rows').replaceChildren();for(const r of visible){const tr=el('tr'),select=el('td'),check=el('input');check.type='checkbox';check.checked=managerState.selected.has(r.licenseId);check.disabled=r.cloudRevoked||r.revocationRequested;check.setAttribute('aria-label',r.customer+' lisansını seç');check.onchange=()=>{if(check.checked)managerState.selected.add(r.licenseId);else managerState.selected.delete(r.licenseId);draw();};select.append(check);const owner=el('td');owner.append(el('div',r.customer,'customer'));if(managerState.columns.number)owner.append(el('div',r.licenseNumber,'sub'));owner.append(el('div',r.activationMode==='first-device'?'Çevrimiçi anahtar':'Cihaza bağlı lisans','sub'));const expiry=el('td');expiry.append(el('div',date(r.expiresAt)),el('div',Math.max(0,Math.ceil((r.expiresAt-Date.now()/1000)/86400))+' gün kaldı','sub'));const status=el('td');status.append(el('span',r.status,'badge '+(r.cloudRevoked||r.status==='Süresi doldu'?'expired':r.revocationRequested?'pending':'')));tr.append(select,owner,expiry,status);
 if(managerState.columns.version){const v=versionState(r),td=el('td');td.append(el('span',v.label,'badge '+v.cls));tr.append(td);}if(managerState.columns.sync){const s=syncLabel(r),td=el('td'),badge=el('span',s.text,'badge '+s.className);badge.title=s.detail;td.append(el('div','Yerel r'+(r.revision||1)+' kayıtlı','sub'),badge);const seen=installations[r.licenseId];td.append(el('div',seen?.checkedAt?'Son cihaz onayı: '+date(seen.checkedAt):seen?.error?'Cihaz bilgisi alınamadı':'Cihaz onayı bilgisi yok','sub'));tr.append(td);}const actions=el('td'),bar=el('div',undefined,'row-actions');bar.append(actionButton('Detay',()=>showDetail(r.licenseId)),actionButton('Uzat',()=>renew(r),r.cloudRevoked),actionButton('•••',()=>openActions(r)));bar.lastChild.setAttribute('aria-label',r.customer+' diğer işlemler');actions.append(bar);tr.append(actions);$('rows').append(tr);}
 $('empty').hidden=filtered.length>0;pageText.textContent=filtered.length+' kayıt · Sayfa '+managerState.pageNumber+' / '+pages;previous.disabled=managerState.pageNumber<=1;next.disabled=managerState.pageNumber>=pages;selectionText.textContent=managerState.selected.size+' seçili';bulkExtend.disabled=!managerState.selected.size;bulkPublish.disabled=!managerState.selected.size||!cloud.configured;
 $('total').textContent=records.length;$('active').textContent=records.filter(r=>r.status==='Aktif').length;$('pending').textContent=records.filter(r=>r.cloudRevoked).length;$('soon').textContent=records.filter(r=>matchesQuick(r,'30')).length;$('outdated').textContent=records.filter(r=>matchesQuick(r,'outdated')).length;
 for(const [index,r] of visible.entries())if(r.deviceId){const bar=$('rows').children[index].querySelector('.row-actions'),file=actionButton('Dosya indir',()=>download(r.licenseId));file.setAttribute('aria-label',(r.licenseNumber||r.licenseId)+' dosyasını indir');bar.insertBefore(file,bar.lastChild);}
 renderOverview();renderRequests();renderCustomers();renderRelease();renderManagerHistory();
}
function requestStatus(value){return {new:'Yeni talep',reviewed:'İnceleniyor',licensed:'Lisans oluşturuldu',rejected:'Reddedildi',delivered:'Teslim edildi',manual:'Kodla aktarıldı'}[value]||value;}
function beginLicenseRequest(r,online=true){reset();$('binding').value='tpm-cng-v1';bindingFields();$('customer').value=r.company;$('deviceId').value=r.deviceId;$('note').value=['Talep: '+r.requestId,r.contact?'İletişim: '+r.contact:'',r.note||''].filter(Boolean).join('\n');window.ASMachPendingLicenseRequest=online?{requestId:r.requestId}:null;showStep(0);newDialog.showModal();$('customer').focus();if(online)void api('request-status',{requestId:r.requestId,status:'reviewed'}).then(loadManagement).catch(e=>notify(e.message,true));}
function renderRequests(){const items=managerState.data.requests||[],open=items.filter(r=>['new','reviewed'].includes(r.status));requestNavButton.textContent='Lisans talepleri'+(open.length?' · '+open.length:'');requestInfo.textContent=managerState.data.requestError?'Talepler alınamadı: '+managerState.data.requestError:items.length+' talep · '+open.length+' bekliyor';requestList.replaceChildren();for(const r of items){const card=el('article',undefined,'request-card'),head=el('div',undefined,'request-head'),info=el('div');info.append(el('h3',r.company),el('p',[r.contact,r.appVersion?'Uygulama '+r.appVersion:''].filter(Boolean).join(' · ')||'İletişim bilgisi yok','muted'));head.append(info,el('span',requestStatus(r.status),'badge '+(r.status==='new'?'pending':r.status==='rejected'?'expired':'')));card.append(head,el('code',r.deviceId),el('p',r.note||'Kullanıcı notu yok','muted'),el('p','Talep: '+r.requestId+' · '+new Date((r.receivedAt||r.createdAt)*1000).toLocaleString('tr-TR'),'muted'));const actions=el('div',undefined,'row-actions');actions.append(actionButton('Bu talepten lisans oluştur',()=>beginLicenseRequest(r,true),!['new','reviewed'].includes(r.status)),actionButton('Teslim edildi',async()=>{await api('request-status',{requestId:r.requestId,status:'delivered',licenseId:r.licenseId||''});await loadManagement();},r.status!=='licensed'),actionButton('Reddet',async()=>{await api('request-status',{requestId:r.requestId,status:'rejected'});await loadManagement();},!['new','reviewed'].includes(r.status)));card.append(actions);requestList.append(card);}if(!items.length)requestList.append(el('p',cloud.configured?'Henüz lisans talebi yok.':'Çevrimiçi talepleri görmek için Bulut ayarlarını bağlayın.','content-pad'));}
function renderOverview(){overviewCards.replaceChildren();for(const [f,title] of [['7','7 gün içinde bitecek'],['15','15 gün içinde bitecek'],['30','30 gün içinde bitecek'],['waiting','Etkinleştirme bilgisi bekleyen'],['failed','Buluta gönderilemeyen'],['expired','Süresi dolan']]){const b=el('button',undefined,'overview-card');b.append(el('strong',records.filter(r=>matchesQuick(r,f)).length),el('span',title));b.onclick=()=>openFiltered(f);overviewCards.append(b);}attention.replaceChildren(el('h3','Yaklaşan bitişler'));for(const r of records.filter(r=>matchesQuick(r,'30')).sort((a,b)=>a.expiresAt-b.expiresAt).slice(0,5)){const row=el('div',undefined,'attention-row');row.append(el('strong',r.customer),el('span',date(r.expiresAt)),actionButton('İncele',()=>showDetail(r.licenseId)));attention.append(row);}if(!attention.querySelector('.attention-row'))attention.append(el('p','Önümüzdeki 30 gün içinde bitecek aktif lisans yok.','muted'));attention.append(el('p','Cihaz onayı bulunmaması cihazın çevrimdışı olduğu anlamına gelmez. İlk etkinleştirme ve son bağlantı ayrıntıları Detay ekranından kontrol edilebilir.','muted'));}
function renderCustomers(){customerList.replaceChildren();const q=customerSearch.value.toLocaleLowerCase('tr');for(const c of managerState.data.customers.filter(c=>[c.name,c.company,c.contact,c.email,c.phone].join(' ').toLocaleLowerCase('tr').includes(q))){const ls=records.filter(r=>r.userId===c.id),row=el('article',undefined,'customer-card');row.append(el('h3',c.company||c.name),el('p',[c.contact,c.email,c.phone].filter(Boolean).join(' · ')||'İletişim bilgisi eklenmemiş','muted'),el('span',ls.length+' lisans · '+ls.filter(l=>l.status==='Aktif').length+' aktif'));if(ls[0])row.append(actionButton('Müşteriyi aç',()=>showDetail(ls[0].licenseId)));customerList.append(row);}if(!customerList.children.length)customerList.append(el('p',managerState.ready?'Müşteri bulunamadı.':'Yükleniyor…'));}
function renderRelease(){releaseInfo.replaceChildren(el('h3',release?'Duyurulan sürüm: '+release.version:'Henüz yayın bilgisi yok'),el('p','Yerel uygulama paketi: '+(managerVersion||'—')));if(release?.notes)releaseInfo.append(el('p',release.notes));releaseInfo.append(el('p',records.filter(r=>versionState(r).cls==='update').length+' lisans eski sürüm bildiriyor. '+records.filter(r=>!installations[r.licenseId]?.appVersion).length+' lisansın sürümü bilinmiyor.'));releaseInfo.append(actionButton('Eski sürüm bildirenleri göster',()=>openFiltered('outdated')),el('p','Duyuru, kurulum dosyasını yüklemez veya müşteriye otomatik kurulum yapmaz.','muted'));}
function renderManagerHistory(){const selected=historyAction.value,actions=[...new Set(managerState.data.history.map(h=>h.action))];if(historyAction.options.length!==actions.length+1){historyAction.replaceChildren(el('option','Tüm işlemler'));historyAction.firstChild.value='';for(const a of actions)historyAction.append(el('option',a));historyAction.value=selected;}const q=historyQuery.value.toLocaleLowerCase('tr'),from=historyFrom.value?new Date(historyFrom.value+'T00:00:00').getTime()/1000:0,to=historyTo.value?new Date(historyTo.value+'T23:59:59').getTime()/1000:Infinity;
 const items=managerState.data.history.filter(h=>{const owner=records.find(r=>r.licenseId===h.license_id)?.customer||managerState.data.customers.find(c=>c.id===h.user_id)?.name||'';return (!historyAction.value||h.action===historyAction.value)&&h.at>=from&&h.at<=to&&[owner,h.action,historyDetail(h)].join(' ').toLocaleLowerCase('tr').includes(q);});const pages=Math.max(1,Math.ceil(items.length/50));managerState.historyPage=Math.min(pages,Math.max(1,managerState.historyPage));$('history').replaceChildren();for(const h of items.slice((managerState.historyPage-1)*50,managerState.historyPage*50)){const row=el('div',undefined,'event'),owner=records.find(r=>r.licenseId===h.license_id)?.customer||managerState.data.customers.find(c=>c.id===h.user_id)?.name||'';row.append(el('span',date(h.at)),el('strong',h.action),el('span',owner+' · '+historyDetail(h)));$('history').append(row);}historyCount.textContent=items.length+' işlem · '+managerState.historyPage+' / '+pages;historyPrev.disabled=managerState.historyPage<=1;historyNext.disabled=managerState.historyPage>=pages;}
function exportList(){const cell=v=>'"'+(/^(?:\s*[=+\-@]|[\t\r\n])/.test(String(v))?"'":'')+String(v??'').replace(/"/g,'""')+'"';const rows=[['Müşteri','Lisans numarası','Durum','Başlangıç','Bitiş','Sürüm','Gönderim'],...filteredRecords().map(r=>[r.customer,r.licenseNumber,r.status,date(r.notBefore),date(r.expiresAt),installations[r.licenseId]?.appVersion||'Bilinmiyor',syncLabel(r).text])];saveBlob(new Blob(['\uFEFF'+rows.map(r=>r.map(cell).join(';')).join('\r\n')],{type:'text/csv;charset=utf-8'}),'ASMach-lisans-listesi.csv');notify('Filtrelenmiş liste dışa aktarıldı. Lisans anahtarları ve özel anahtarlar dahil edilmedi.');}
function openBulk(action){const d=modal(action==='extend'?'Toplu süre uzatma':'Buluta yeniden gönder'),body=el('div',undefined,'content-pad');body.append(el('p',managerState.selected.size+' lisans seçili. Önizlemeden sonra ayrıca onayınız istenir.'));const months=el('select');months.setAttribute('aria-label','Uzatılacak süre');for(const n of [1,3,6,12,24,36]){const o=el('option',n+' ay');o.value=n;months.append(o);}months.value=12;if(action==='extend')body.append(months);const preview=el('button','İşlemi önizle','primary'),result=el('div',undefined,'bulk-results');body.append(preview,result);d.append(body);preview.onclick=()=>runButton(preview,async()=>{const out=await api('bulk-preview',{action,ids:[...managerState.selected],months:Number(months.value)});months.disabled=true;preview.hidden=true;for(const r of out.rows){const row=el('p',r.customer+' · '+date(r.before)+(action==='extend'?' → '+date(r.after):''));result.append(row);}result.append(el('p',out.cloud?'Onaylanan değişiklikler buluta gönderilir. Cihaza uygulandığı ayrıca doğrulanmalıdır.':'Yalnızca yerel kayıt güncellenecek; bulut bağlı değil.'));const commit=el('button','Onayla ve uygula','primary');result.append(commit);commit.onclick=()=>runButton(commit,async()=>{commit.hidden=true;const response=await api('bulk-commit',{planId:out.planId,confirmed:true});result.replaceChildren(el('h3','İşlem sonuçları'));for(const r of response.results){result.append(el('p',r.customer+' · '+(r.saved?'Süre kaydedildi. ':'')+r.message,r.ok?'':'error-text'));if(r.ok||r.saved)managerState.selected.delete(r.id);}await refresh();});});d.showModal();}
restoreButton.onclick=()=>runButton(restoreButton,async()=>{const file=restoreFile.files[0];if(!file||file.size>20000000)throw Error('En fazla 20 MB boyutunda yedek seçin.');const out=await api('restore-preview',{archive:JSON.parse(await file.text()),password:restorePassword.value});restorePassword.value='';const d=modal('Geri yükleme önizlemesi'),body=el('div',undefined,'content-pad');body.append(el('p','Yedek tarihi: '+out.createdAt),el('p','Mevcut: '+out.current.licenses+' lisans / '+out.current.customers+' müşteri / '+out.current.events+' işlem'),el('p','Yedek: '+out.licenses+' lisans / '+out.customers+' müşteri / '+out.events+' işlem'),el('p','Mevcut kayıtlar yedekteki kayıtlarla değiştirilecek. Önce mevcut verilerin şifreli güvenlik yedeği, bu yedeğin parolasıyla alınır. Bulut kayıtları değişmez.','error-text'));const confirm=el('input');confirm.placeholder='GERİ YÜKLE yazın';confirm.setAttribute('aria-label','Geri yükleme onayı');const commit=el('button','Geri yükle','danger');commit.disabled=true;confirm.oninput=()=>commit.disabled=confirm.value!=='GERİ YÜKLE';commit.onclick=()=>runButton(commit,async()=>{commit.hidden=true;const r=await api('restore-commit',{planId:out.planId,confirmation:confirm.value});body.replaceChildren(el('p',r.message),el('p','Güvenlik yedeği: '+r.safetyBackup));managerState.selected.clear();installations={};await refresh();});body.append(confirm,commit);d.append(body);d.showModal();});
// Keep secrets hidden until explicitly requested, and clear them when the dialog closes.
const originalShowCode=showCode;showCode=(title,code,description)=>{originalShowCode(title,code,description);$('codeValue').hidden=true;codeReveal.hidden=false;codeReveal.textContent='Kodu göster';};const codeReveal=el('button','Kodu göster');codeReveal.onclick=()=>{$('codeValue').hidden=!$('codeValue').hidden;codeReveal.textContent=$('codeValue').hidden?'Kodu göster':'Kodu gizle';};$('codeDialog').querySelector('footer').prepend(codeReveal);$('codeDialog').addEventListener('close',()=>{$('codeValue').value='';});
const originalNotify=notify;notify=(text,error=false)=>{let box=$('message');if(!box){box=el('div');box.id='message';box.setAttribute('role','status');box.setAttribute('aria-live','polite');document.body.append(box);}const active=[...document.querySelectorAll('dialog[open]')].at(-1);(active||document.body).append(box);originalNotify(String(text).replace(/\nAnahtar: [^\n]+/g,'\nAnahtar oluşturuldu; kayıt üzerinden gösterebilirsiniz.'),error);};
document.addEventListener('close',()=>{const box=$('message'),owner=box?.closest('dialog');if(owner&&!owner.open){document.body.append(box);box.hidden=true;}},true);
const oldRenew=renew;renew=r=>{oldRenew(r);$('amendOwner').textContent=r.customer+' · Mevcut bitiş: '+date(r.expiresAt)+' · Aynı lisans kimliği korunacak';};
const amendPreview=el('p');$('amendExpiry').closest('label').after(amendPreview);$('amendExpiry').addEventListener('input',()=>{amendPreview.textContent=$('amendExpiry').value?'Yeni bitiş: '+new Date($('amendExpiry').value).toLocaleString('tr-TR'):'';});$('amendDialog').addEventListener('close',()=>amendPreview.textContent='');
// Compact three-step creation flow, preserving the existing issue/save implementation.
const form=$('licenseForm'),steps=[el('div'),el('div'),el('div')],stepLabel=el('p',undefined,'wizard-step');let wizardStep=0;
for(const item of [$('customer').closest('label'),$('binding').closest('label'),$('deviceId').closest('label'),$('bindingHint')])steps[0].append(item);
for(const item of [form.querySelector('.dates'),form.querySelector('.presets'),$('note').closest('label')])steps[1].append(item);
const wizardSummary=el('p',undefined,'wizard-summary');steps[2].append(wizardSummary,$('create'),form.querySelector('.hint'));form.append(stepLabel,...steps);form.noValidate=true;
const template=el('select');template.setAttribute('aria-label','Lisans süre şablonu');for(const [v,t] of [['','Süre şablonu seçin'],['7','7 günlük deneme'],['30','30 günlük deneme'],['365','Yıllık lisans']]){const o=el('option',t);o.value=v;template.append(o);}template.onchange=()=>{if(template.value){const start=new Date($('startsAt').value);const end=new Date(start);end.setDate(end.getDate()+Number(template.value));$('expiresAt').value=localDate(end);}};steps[1].prepend(template);
const wizardBar=el('div',undefined,'wizard-bar'),back=el('button','Geri'),forward=el('button','Devam','primary');back.type=forward.type='button';wizardBar.append(back,forward);form.append(wizardBar);
function showStep(n){wizardStep=n;steps.forEach((s,i)=>s.hidden=i!==n);stepLabel.textContent=(n+1)+' / 3 · '+['Müşteri ve yöntem','Süre ve not','Kontrol ve oluştur'][n];back.hidden=n===0;forward.hidden=n===2;wizardSummary.textContent=$('customer').value+'\n'+$('binding').selectedOptions[0].textContent+'\nBaşlangıç: '+$('startsAt').value.replace('T',' ')+'\nBitiş: '+$('expiresAt').value.replace('T',' ')+'\n'+(cloud.configured?'Oluşturulduktan sonra buluta gönderilir.':'Bulut bağlı değil; yalnızca yerelde oluşturulur.');}
function validateStep(n){if(n===1){const start=new Date($('startsAt').value).getTime(),end=new Date($('expiresAt').value).getTime();$('expiresAt').setCustomValidity(end<=start||end<=Date.now()?'Bitiş, başlangıçtan ve bugünden sonra olmalı.':'');}for(const c of steps[n].querySelectorAll('input,select,textarea'))if(!c.disabled&&!c.checkValidity()){showStep(n);c.reportValidity();return false;}return true;}
back.onclick=()=>showStep(wizardStep-1);forward.onclick=()=>{if(validateStep(wizardStep))showStep(wizardStep+1);};const originalSubmit=form.onsubmit;form.onsubmit=e=>{e.preventDefault();if(wizardStep<2){forward.click();return;}if(validateStep(0)&&validateStep(1))return originalSubmit(e);};const originalReset=reset;reset=()=>{originalReset();template.value='';showStep(0);};showStep(0);
const originalRefresh=refresh;let managementRequest=0;
async function loadManagement(){const request=++managementRequest;const data=await api('management');if(request!==managementRequest)return;const incoming=(data.requests||[]).filter(r=>r.status==='new'&&!managerState.knownRequests.has(r.requestId));managerState.data=data;for(const r of data.requests||[])managerState.knownRequests.add(r.requestId);if(incoming.length)notify(incoming.length+' yeni çevrimdışı lisans talebi var.');managerState.ready=true;draw();}
refresh=async()=>{await originalRefresh();await loadManagement();};draw=drawManager;navigate('overview');loadManagement().catch(e=>notify(e.message,true));
requestRefresh.onclick=()=>loadManagement().catch(e=>notify(e.message,true));requestImport.onclick=()=>{const d=modal('Talep kodunu içe aktar'),body=el('div',undefined,'content-pad'),area=el('textarea');area.rows=8;area.placeholder='ASM-REQ1-...';area.setAttribute('aria-label','Çevrimdışı lisans talep kodu');const load=el('button','Talebi doğrula','primary');load.onclick=()=>runButton(load,async()=>{const out=await api('request-import',{code:area.value});d.close();beginLicenseRequest(out.request,false);notify('TPM imzalı talep doğrulandı. Bilgisayar kimliği lisans formuna aktarıldı.');});body.append(el('p','Kullanıcının uygulamasında oluşan ASM-REQ1 kodunu yapıştırın.'),area,load);d.append(body);d.showModal();};setInterval(()=>loadManagement().catch(()=>{}),30000);
