'use strict';
(()=>{
 const page=$('releasesPage');if(!page)return;
 const old=$('releaseSettings');old.textContent='Eski istemciler için sürüm duyurusu';
 const advanced=document.createElement('details');advanced.className='release-config';const summary=document.createElement('summary');summary.textContent='Bağlantı ve eski sürüm ayarları';advanced.append(summary);page.append(advanced);advanced.append(old);
 const form=document.createElement('form');form.className='release-form';form.innerHTML='<label>Sürüm<input name="version" placeholder="2.0.8" required pattern="[0-9]+\\.[0-9]+\\.[0-9]+"></label><label>Paket<select name="variant"><option value="online">Online setup</option><option value="offline">Offline setup</option></select></label><label>Kanal<select name="channel"><option value="test">Test</option><option value="stable">Kararlı · müşteriler</option></select></label><label class="wide">Kurulum dosyası<input name="file" type="file" accept=".exe" required></label><label class="wide">Sürüm notları<textarea name="notes" maxlength="1000"></textarea></label><div class="wide"><button class="primary" type="submit">Dosyayı al ve kontrol et</button> <span>Henüz müşterilere yayınlanmaz.</span></div>';
 const status=document.createElement('p');status.className='release-status';status.setAttribute('role','status');const list=document.createElement('div');list.className='release-list';page.insertBefore(form,advanced);page.insertBefore(status,advanced);page.insertBefore(list,advanced);
 const urlLabel=document.createElement('label');urlLabel.textContent='Yayın deposu HTTPS adresi';const url=document.createElement('input');url.type='url';urlLabel.append(url);const keyLabel=document.createElement('label');keyLabel.textContent='Yayın deposu anahtarı (kayıtlı olanı korumak için boş bırakın)';const key=document.createElement('input');key.type='password';key.autocomplete='new-password';keyLabel.append(key);const connect=document.createElement('button');connect.textContent='Bağlantıyı sına ve kaydet';advanced.append(urlLabel,keyLabel,connect);if(typeof releaseInfo!=='undefined')advanced.append(releaseInfo);
 let loading=false,items=[];
 async function refresh(){if(loading)return;loading=true;try{const data=await fetch('/api/releases',{headers:{Authorization:'Bearer '+token}}).then(r=>r.json());if(data.error)throw Error(data.error);items=data.items;url.value=data.url;list.replaceChildren();
  if(!items.length){const p=document.createElement('p');p.textContent='Henüz paket yok. EXE dosyasını seçerek başlayın.';list.append(p);}
  for(const item of items){const card=document.createElement('article');card.className='release-item';const title=document.createElement('strong');title.textContent=`${item.version} · ${item.variant==='offline'?'Offline':'Online'} · ${item.channel==='stable'?'Kararlı':'Test'}`;const info=document.createElement('p');info.textContent=`${({draft:'Hazır · yerel',uploading:'Yükleniyor',published:'Yayınlandı',failed:'Başarısız'})[item.status]} · ${(item.size/1048576).toFixed(1)} MB${item.status==='uploading'?' · %'+(item.progress||0):''}`;const error=document.createElement('p');error.textContent=item.error||'';error.className='error-text';const actions=document.createElement('div');actions.className='row-actions';const publish=document.createElement('button');publish.textContent=item.status==='failed'?'Yeniden dene':'Kontrol et ve yayınla';publish.disabled=!data.configured||data.busy||item.status==='published';publish.onclick=()=>publishItem(item,publish);actions.append(publish);const details=document.createElement('details');const s=document.createElement('summary');s.textContent='Dosya ayrıntıları';const detail=document.createElement('p');detail.textContent=item.name+' · SHA-256: '+item.sha256+'\n'+item.warning;details.append(s,detail);card.append(title,info,error,actions,details);list.append(card);}
  status.textContent=data.configured?'Depo bağlı. Test kanalındaki paketler kararlı kanal müşterilerine gösterilmez.':'Depo bağlı değil. Dosyaları yerelde hazırlayabilirsiniz; canlı yayın için bağlantı kurulmalı.';
 }catch(e){status.textContent=e.message;}finally{loading=false;}}
 async function publishItem(item,button){const d=document.createElement('dialog');d.className='manager-dialog';d.innerHTML='<form style="padding:16px"><h2>Yayını onayla</h2><p data-summary></p><label><input type="checkbox" required> Paketin ASMach ürünü, belirtilen sürüm ve x64 hedefi olduğunu; kurulumu test ettiğimi doğruluyorum.</label><label>Onay için YAYINLA yazın<input name="confirm" required pattern="YAYINLA"></label><p data-error role="status"></p><footer><button type="button">Vazgeç</button><button type="submit" class="primary">Yayınla</button></footer></form>';d.querySelector('[data-summary]').textContent=`${item.version} · ${item.channel} · ${url.value}. Dosyalar yüklendikten sonra kanal yayını açılacak.`;d.querySelector('button[type=button]').onclick=()=>d.close();d.onclose=()=>d.remove();d.querySelector('form').onsubmit=async e=>{e.preventDefault();const submit=d.querySelector('button[type=submit]');submit.disabled=true;try{await api('release-publish',{id:item.id,verified:true,confirm:d.querySelector('[name=confirm]').value});d.close();await refresh();}catch(err){d.querySelector('[data-error]').textContent=err.message;submit.disabled=false;}};document.body.append(d);d.showModal();}
 form.onsubmit=e=>{e.preventDefault();const file=form.elements.file.files[0];if(!file)return;const params=new URLSearchParams({version:form.elements.version.value,variant:form.elements.variant.value,channel:form.elements.channel.value,name:file.name,notes:form.elements.notes.value});const xhr=new XMLHttpRequest();const button=form.querySelector('button');button.disabled=true;xhr.open('POST','/api/release-upload?'+params);xhr.setRequestHeader('Authorization','Bearer '+token);xhr.setRequestHeader('Content-Type','application/octet-stream');xhr.upload.onprogress=e=>{status.textContent='Yerel dosya aktarımı: %'+Math.round(e.loaded/(e.total||file.size)*100);};xhr.onload=()=>{button.disabled=false;try{const result=JSON.parse(xhr.responseText);if(xhr.status!==200)throw Error(result.error||'Dosya alınamadı.');form.reset();refresh();}catch(err){status.textContent=err.message;}};xhr.onerror=()=>{button.disabled=false;status.textContent='Dosya aktarımı başarısız. Tekrar deneyebilirsiniz.';};xhr.send(file);};
 connect.onclick=()=>runButton(connect,async()=>{await api('publisher-config',{url:url.value,token:key.value});key.value='';await refresh();});
 for(const channel of ['test','stable']){const b=document.createElement('button');b.textContent=(channel==='test'?'Test':'Kararlı')+' yayınını durdur';b.onclick=()=>{if(!confirm('Yeni indirmeler kapanır; kurulmuş sürümler kaldırılmaz. Devam edilsin mi?'))return;runButton(b,async()=>{await api('release-pause',{channel,confirm:'DURDUR'});await refresh();});};advanced.append(b);}
 refresh();setInterval(()=>{if(!page.hidden)refresh();},4000);
})();
