'use strict';
// Owner-only provisioning. Never print tokens or private keys. No paid-plan operations.
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'..'),cfg=JSON.parse(fs.readFileSync(path.join(root,'licensing-service/wrangler.jsonc'))),vault=path.join(root,'.license-admin');
const authFile=path.join(process.env.APPDATA,'xdg.config/.wrangler/config/default.toml');
function token(){const match=fs.readFileSync(authFile,'utf8').match(/^oauth_token\s*=\s*"([^"]+)"/m);if(!match)throw Error('Cloudflare oturumu bulunamadı.');return match[1];}
async function api(route,method='GET',body){const r=await fetch('https://api.cloudflare.com/client/v4/accounts/'+cfg.account_id+route,{method,headers:{Authorization:'Bearer '+token(),'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body),redirect:'error',signal:AbortSignal.timeout(20000)});const out=await r.json();if(!r.ok||!out.success)throw Error('Cloudflare işlemi başarısız: HTTP '+r.status+' kod '+(out.errors||[]).map(x=>x.code).join(','));return out.result;}
async function main(){const mode=process.argv[2];if(mode==='preflight'){let subscriptions;try{const subs=await api('/subscriptions');subscriptions=subs.map(s=>({id:s.rate_plan?.id,name:s.rate_plan?.public_name,price:s.price}));}catch{subscriptions='Oturumun faturalama bilgilerini okuma yetkisi yok; ücretli abonelik işlemi yapılmaz.';}console.log(JSON.stringify({subscriptions,subdomain:await api('/workers/subdomain'),settings:await api('/workers/account-settings')}));return;}
 if(mode==='secrets'){const adminFile=path.join(vault,'cloud-admin-token');if(!fs.existsSync(adminFile))fs.writeFileSync(adminFile,crypto.randomBytes(32).toString('hex'),{flag:'wx',mode:0o600});const status=fs.readFileSync(path.join(vault,'status.pem'),'utf8'),pub=JSON.parse(fs.readFileSync(path.join(root,'src-tauri/license-config.json'))).statusPublicKey;const key=crypto.createPublicKey(crypto.createPrivateKey(status)).export({format:'jwk'});if(Buffer.from(key.x,'base64url').toString('base64')!==pub)throw Error('Durum anahtarı eşleşmiyor.');for(const[name,text]of[['STATUS_PRIVATE_KEY',status],['ADMIN_TOKEN',fs.readFileSync(adminFile,'utf8').trim()]]){await api('/workers/scripts/'+cfg.name+'/secrets','PUT',{name,text,type:'secret_text'});console.log(name+' güvenli olarak kaydedildi.');}return;}
 if(mode==='connect'){const domain=await api('/workers/subdomain');if(!domain.subdomain)throw Error('Worker alan adı bulunamadı.');const url='https://'+cfg.name+'.'+domain.subdomain+'.workers.dev';const cloud=require('../license-manager/cloud.cjs').cloud(root);const result=await cloud.configure({url,token:fs.readFileSync(path.join(vault,'cloud-admin-token'),'utf8').trim()});console.log(JSON.stringify(result));return;}
 throw Error('Geçerli işlem: preflight, secrets, connect');}
main().catch(e=>{console.error(e.message+(e.cause?.code?' ('+e.cause.code+')':''));process.exitCode=1;});
