/* Inline source-context selection. Drafts never mutate the candidate until Apply. */
(function(root){
 'use strict';
 function mount(host,options){
  const c=options.candidate;
  let disposed=false,revision=0,whole=false,selecting=false,drag=null,region=null,draft=null,read=null,busy=false,zoom=1;
  let pan=null,focusPending=true,autoFocus=true;
  let detailSelection=null,detailDrag=null,detailBaseBox={...c.box};
  let scope='all',readingMode=root.ASMachOcrEnhancement?.mode()||'auto';
  const MAX_ZOOM=64;
  const make=(tag,cls,text)=>{const n=document.createElement(tag);n.className=cls||'';if(text)n.textContent=text;return n;};
  const toolbar=make('div','wf-source-tools'),viewport=make('div','wf-source-viewport'),stage=make('div','wf-source-stage'),canvas=make('canvas'),hint=make('div','wf-source-hint'),form=make('div','wf-source-draft');
  canvas.setAttribute('aria-label','Kaynak çizim — yeni ölçü kutusunu sürükleyerek seçin');canvas.tabIndex=0;hint.setAttribute('role','status');
  const detail=make('div','wf-source-detail'),detailImage=make('img'),detailSurface=make('div','wf-detail-image'),detailOutline=make('div','wf-detail-selection');detailImage.alt='Seçili adayın ölçü görüntüsü';detailImage.draggable=false;detailSurface.tabIndex=0;detailSurface.setAttribute('aria-label','Aday görüntüsünde nominal veya tolerans alanını seçin');detailSurface.append(detailImage,detailOutline);detail.append(detailSurface);detailOutline.hidden=true;
  function exactDetail(sourceBox){if(!c.pageImage||!sourceBox)return'';if(sourceBox.points?.length===4&&root.ASMachSnapshots?._test?.extract){const W=c.pageImage.width,H=c.pageImage.height,p=sourceBox.points.map(v=>({x:v.x*W,y:v.y*H})),cx=p.reduce((s,v)=>s+v.x,0)/4,cy=p.reduce((s,v)=>s+v.y,0)/4,w=Math.hypot(p[1].x-p[0].x,p[1].y-p[0].y),h=Math.hypot(p[3].x-p[0].x,p[3].y-p[0].y),angle=Math.atan2(p[1].y-p[0].y,p[1].x-p[0].x)*180/Math.PI;return root.ASMachSnapshots._test.extract(c.pageImage,{cx,cy,w,h,angle}).toDataURL('image/png');}return root.ASMachSnapshots.cropCanvas(c.pageImage,sourceBox).toDataURL('image/png');}
  function showDetail(snapshot,sourceBox=c.box){host.classList.remove('wf-source-selecting');host.classList.add('wf-source-compact');detail.append(toolbar);detailBaseBox={...(sourceBox||c.box)};detailImage.src=snapshot||c.detailSnapshot||exactDetail(detailBaseBox)||c.snapshot||'';detail.hidden=false;}
  function showDrawing(){host.classList.remove('wf-source-compact');host.classList.add('wf-source-selecting');viewport.after(toolbar);detail.hidden=true;whole=false;autoFocus=true;focusPending=true;draw();requestAnimationFrame(()=>{if(!disposed){layout();focusView();}});}
  function button(label,fn,parent=toolbar){const b=make('button','btn',label);b.type='button';b.onclick=fn;parent.append(b);return b;}
  const near=button('Aday ayrıntısı',()=>{reset();showDetail();}),page=button('Tüm sayfa',()=>{showDrawing();showView(true);});
  const select=button('Yeniden seç',()=>{reset();selecting=true;showDrawing();options.onSelectionChange?.(true);select.setAttribute('aria-pressed','true');canvas.style.cursor='crosshair';cancel.hidden=false;hint.textContent='Ölçü ve toleransları kutuya alın. Esc: iptal.';draw();canvas.focus();});
  const icons=['<path d="M8 3H3v5M16 3h5v5M3 16v5h5M21 16v5h-5"/><rect x="7" y="8" width="10" height="8"/>','<path d="M6 2h8l4 4v16H6zM14 2v5h4"/>'];[near,page].forEach((b,i)=>{b.title=b.textContent;b.setAttribute('aria-label',b.textContent);b.innerHTML='<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" aria-hidden="true">'+icons[i]+'</svg>';});select.title='Yeniden seç';select.setAttribute('aria-label','Yeniden seç');select.replaceChildren();const selectIcon=make('img');selectIcon.src="data:image/svg+xml;charset=utf-8,%3Csvg%20width%3D%22800px%22%20height%3D%22800px%22%20viewBox%3D%220%200%2050.8%2050.8%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%0D%0A%0D%0A%3Cg%20stroke-width%3D%2210.054%22%20transform%3D%22translate(-6.81%20-4.916)%20scale(.31579)%22%3E%0D%0A%0D%0A%3Cg%20fill%3D%22none%22%20fill-opacity%3D%220%22%20stroke%3D%22%23000000%22%20stroke-linecap%3D%22round%22%20stroke-linejoin%3D%22round%22%3E%0D%0A%0D%0A%3Cpath%20d%3D%22M120%20144H40V64h112v16%22%2F%3E%0D%0A%0D%0A%3Cpath%20d%3D%22M96%2088c8.84%200%2016%207.16%2016%2016s-7.16%2016-16%2016-16-7.16-16-16%207.16-16%2016-16zM56%2048h8%22%2F%3E%0D%0A%0D%0A%3Cpath%20stroke-opacity%3D%22.996%22%20d%3D%22M120%2080h16%22%2F%3E%0D%0A%0D%0A%3Cpath%20d%3D%22m136%2096%2024%2032m0-4c2.21%200%204%201.79%204%204s-1.79%204-4%204-4-1.79-4-4%201.79-4%204-4zm-24%200c2.21%200%204%201.79%204%204s-1.79%204-4%204-4-1.79-4-4%201.79-4%204-4zm0%204%2024-32%22%2F%3E%0D%0A%0D%0A%3C%2Fg%3E%0D%0A%0D%0A%3Ccircle%20cx%3D%2265.2%22%20cy%3D%2280%22%20r%3D%226%22%2F%3E%0D%0A%0D%0A%3C%2Fg%3E%0D%0A%0D%0A%3C%2Fsvg%3E";selectIcon.width=18;selectIcon.height=18;selectIcon.alt='';select.append(selectIcon);
  const cancel=button('İptal',()=>{reset();hint.textContent='Seçim iptal edildi. Mevcut ölçü korundu.';});cancel.hidden=true;
  near.remove();page.remove();
  const compareButton=button('Karşılaştır',()=>root.ASMachOcrEnhancement?.preview().catch(e=>{hint.textContent=e.message;}));root.ASMachOcrEnhancement?.decorateTarget(compareButton,'compare','Karşılaştır');
  const zoomTools=make('div','wf-source-tools wf-source-zoom');
  const zoomRange=make('input','wf-source-zoom-range'),zoomValue=make('output','wf-source-zoom-value','100%'),zoomIcon=make('span');zoomRange.type='range';zoomRange.min='-2';zoomRange.max='6';zoomRange.step='.01';zoomRange.value='0';zoomRange.setAttribute('aria-label','Kaynak görüntü yakınlaştırma');zoomRange.oninput=()=>setZoom(2**Number(zoomRange.value));zoomIcon.innerHTML='<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" aria-hidden="true"><circle cx="10" cy="10" r="6"/><path d="m15 15 6 6M7 10h6M10 7v6"/></svg>';zoomTools.append(zoomIcon,zoomRange,zoomValue);
  zoomValue.setAttribute('aria-label','Yakınlaştırma oranı');
  zoomValue.setAttribute('aria-label','Yakınlaştırma oranı');
  const label=make('label','','Seçim sonucu'),input=make('textarea');input.rows=2;input.setAttribute('aria-label','Yeni seçim metni');label.append(input);form.append(label);
  input.placeholder='Örnek: Ø27.3 (0/-0.05)';
  const values=make('div','wf-source-values');values.setAttribute('aria-live','polite');form.append(values);
  const updateValues=()=>{const p=options.parse?.(input.value);if(!p)return;values.textContent=p.toleranceAmbiguous?p.parseWarnings.join(' '):`Nominal: ${p.nominalValue||'—'} · Alt: ${p.lowerTolerance||'—'} · Üst: ${p.upperTolerance||'—'}`;};input.oninput=updateValues;
  const readingEvidence=(result,manuallyEdited=false)=>({rawText:String(result?.rawText??result?.text??''),originalOcrText:String(result?.originalOcrText||result?.rawText||result?.text||c.originalText||c.text||''),needsReview:!manuallyEdited&&!!result?.needsReview,reviewReason:manuallyEdited?'':String(result?.reviewReason||''),reviewConfirmed:manuallyEdited||!!result?.reviewConfirmed,alternatives:Array.isArray(result?.alternatives)?result.alternatives:[]});
  const appliedHint=(result,automatic=true)=>{hint.textContent=result?.needsReview?'Okuma uygulandı; kontrol gerekli. '+(result.reviewReason||'Nominal, tolerans ve işaretleri kaynak görüntüyle karşılaştırın.'):automatic?'Seçilen okuma otomatik uygulandı.':'Ölçü güncellendi.';};
  const actions=make('div','wf-source-tools');form.append(actions);
  const retry=button('Tekrar oku',()=>recognize(),actions),apply=button('Ölçüyü güncelle',()=>{
   if(!draft||busy||!current())return;
   try{const text=input.value.trim();const edit={...draft,...readingEvidence(read,read?.text!==text),text,confidence:read?.text===text?read.confidence:0,source:read?.text===text?read.source:'Kaynak görüntüde elle düzeltildi'};if(draft.scope&&draft.scope!=='all')options.applyPartial(edit);else options.apply(edit);appliedHint(edit,false);}catch(e){hint.textContent=e.message;}
  },actions);apply.classList.add('primary');form.hidden=true;
  const retryIcon='<svg width="18" height="18" viewBox="0 0 16 16" fill="currentColor" aria-hidden="true"><path d="M14.9547098,7.98576084 L15.0711,7.99552 C15.6179,8.07328 15.9981,8.57957 15.9204,9.12636 C15.6826,10.7983 14.9218,12.3522 13.747,13.5654 C12.5721,14.7785 11.0435,15.5888 9.37999,15.8801 C7.7165,16.1714 6.00349,15.9288 4.48631,15.187 C3.77335,14.8385 3.12082,14.3881 2.5472,13.8537 L1.70711,14.6938 C1.07714,15.3238 0,14.8776 0,13.9867 L0,9.99998 L3.98673,9.99998 C4.87763,9.99998 5.3238,11.0771 4.69383,11.7071 L3.9626,12.4383 C4.38006,12.8181 4.85153,13.1394 5.36475,13.3903 C6.50264,13.9466 7.78739,14.1285 9.03501,13.9101 C10.2826,13.6916 11.4291,13.0839 12.3102,12.174 C13.1914,11.2641 13.762,10.0988 13.9403,8.84476 C14.0181,8.29798 14.5244,7.91776 15.0711,7.99552 L14.9547098,7.98576084 Z M11.5137,0.812976 C12.2279,1.16215 12.8814,1.61349 13.4558,2.14905 L14.2929,1.31193 C14.9229,0.681961 16,1.12813 16,2.01904 L16,6.00001 L12.019,6.00001 C11.1281,6.00001 10.6819,4.92287 11.3119,4.29291 L12.0404,3.56441 C11.6222,3.18346 11.1497,2.86125 10.6353,2.60973 C9.49736,2.05342 8.21261,1.87146 6.96499,2.08994 C5.71737,2.30841 4.57089,2.91611 3.68976,3.82599 C2.80862,4.73586 2.23802,5.90125 2.05969,7.15524 C1.98193,7.70202 1.47564,8.08224 0.928858,8.00448 C0.382075,7.92672 0.00185585,7.42043 0.0796146,6.87364 C0.31739,5.20166 1.07818,3.64782 2.25303,2.43465 C3.42788,1.22148 4.95652,0.411217 6.62001,0.119916 C8.2835,-0.171384 9.99651,0.0712178 11.5137,0.812976 Z"/></svg>';
  retry.title=retry.textContent;retry.setAttribute('aria-label',retry.textContent);retry.innerHTML=retryIcon;
  apply.title=apply.textContent;apply.setAttribute('aria-label',apply.textContent);apply.innerHTML='<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="m5 12 4 4L19 6"/></svg>';
  stage.append(canvas);viewport.append(stage);
  if(host.closest('#cwInlineSource')){const preview=make('div','cw-source-preview');preview.append(viewport,toolbar,zoomTools);const grow=host.closest('#cwInlineSource')._sourceGrow;if(grow)preview.append(grow);host.append(preview,hint,form);}else host.append(toolbar,zoomTools,viewport,hint,form);
  viewport.before(detail);
  const modes=make('div','wf-source-tools wf-reading-modes'),targets=make('div','wf-source-tools wf-reading-targets');
  modes.setAttribute('aria-label','OCR okuma yöntemi');
  for(const [value,label] of [['auto','OCR Metin Ayıklama'],['off','Orijinal'],['strong','Güçlü']]){
    const b=button(label,()=>{readingMode=value;root.ASMachOcrEnhancement?.setMode(value);for(const other of modes.children)other.setAttribute('aria-pressed',String(other===b));revision++;busy=false;scope='all';draft={box:c.box,snapshot:c.snapshot,scope,enhancement:readingMode,autoApply:true};read=null;form.hidden=false;recognize();},modes);
    b.dataset.ocrMode=value;b.setAttribute('aria-pressed',String(value===readingMode));
    root.ASMachOcrEnhancement?.decorateTarget(b,{auto:'text',off:'original',strong:'strong'}[value],label);
  }
  function selectedDetailCrop(){if(!detailSelection||!detailImage.naturalWidth||!detailImage.naturalHeight)return null;const b=detailSelection,part=document.createElement('canvas'),W=detailImage.naturalWidth,H=detailImage.naturalHeight,x=Math.floor(b.x*W),y=Math.floor(b.y*H),right=Math.min(W,Math.ceil((b.x+b.w)*W)),bottom=Math.min(H,Math.ceil((b.y+b.h)*H));part.width=Math.max(1,right-x);part.height=Math.max(1,bottom-y);part.getContext('2d').drawImage(detailImage,x,y,part.width,part.height,0,0,part.width,part.height);return{b,part};}
  function refineDetailCrop(picked){if(!root.ASMachAutoSelection?.detect||!root.ASMachSnapshots?._test?.extract)return picked;const part=picked.part,seed={cx:part.width/2,cy:part.height/2,w:Math.max(2,part.width-2),h:Math.max(2,part.height-2),angle:0},detected=root.ASMachAutoSelection.detect(part,seed,{angleHint:0,padding:1});if(!detected?.confident)return picked;const r=root.ASMachSnapshots._test.constrain(detected.rect,part.width,part.height),x=Math.max(0,(r.cx-r.w/2)/part.width),y=Math.max(0,(r.cy-r.h/2)/part.height),right=Math.min(1,(r.cx+r.w/2)/part.width),bottom=Math.min(1,(r.cy+r.h/2)/part.height);if(right-x<=0||bottom-y<=0)return picked;const b={x:picked.b.x+x*picked.b.w,y:picked.b.y+y*picked.b.h,w:(right-x)*picked.b.w,h:(bottom-y)*picked.b.h};return{b,part:root.ASMachSnapshots._test.extract(part,r),sourceTextHeight:Number.isFinite(detected.textHeight)?detected.textHeight:null};}
  function mapDetailCrop(base,b){
   const points=base.points?.length===4?base.points:[{x:base.x,y:base.y},{x:base.x+base.w,y:base.y},{x:base.x+base.w,y:base.y+base.h},{x:base.x,y:base.y+base.h}],at=(u,v)=>({x:points[0].x*(1-u)*(1-v)+points[1].x*u*(1-v)+points[2].x*u*v+points[3].x*(1-u)*v,y:points[0].y*(1-u)*(1-v)+points[1].y*u*(1-v)+points[2].y*u*v+points[3].y*(1-u)*v}),mapped=[at(b.x,b.y),at(b.x+b.w,b.y),at(b.x+b.w,b.y+b.h),at(b.x,b.y+b.h)],x=Math.min(...mapped.map(p=>p.x)),y=Math.min(...mapped.map(p=>p.y));
   return{x,y,w:Math.max(...mapped.map(p=>p.x))-x,h:Math.max(...mapped.map(p=>p.y))-y,points:mapped,rotation:Number(base.rotation)||Math.atan2(points[1].y-points[0].y,points[1].x-points[0].x)*180/Math.PI};
  }
  if(options.applyPartial)for(const [value,label]of [['nominal','Nominal için OCR'],['tolerance','Tolerans için OCR']]){
   const target=button(label,()=>{if(busy||!current())return;const picked=selectedDetailCrop();if(!picked)return;scope=value;draft={box:c.box,snapshot:picked.part.toDataURL(),scope,enhancement:readingMode,autoApply:true};read=null;input.value='';recognize();},targets);target.disabled=true;target.dataset.readTarget=value;
  }
  if(options.crop){const cropTarget=button('Kırp',()=>{if(busy||!current())return;const selected=selectedDetailCrop();if(!selected)return;const picked=refineDetailCrop(selected);options.crop({box:mapDetailCrop(detailBaseBox||c.box,picked.b),snapshot:picked.part.toDataURL('image/png'),sourceTextHeight:Number.isFinite(picked.sourceTextHeight)?picked.sourceTextHeight:c.sourceTextHeight});},targets);cropTarget.disabled=true;cropTarget.title='Seçilen alanı karakteristik kutusu olarak kırp';cropTarget.setAttribute('aria-label','Kırp');cropTarget.innerHTML='<svg width="18" height="18" viewBox="0 0 16 16" fill="currentColor" aria-hidden="true"><path d="M2 6V14L10 14V12L5.41421 12L10 7.41421V6H8.58579L4 10.5858V6H2Z"/><path d="M12 4V16H14V14H16V12H14V2L4 2L4 0H2V2H0V4H12Z"/></svg>';}
  for(const b of targets.querySelectorAll('[data-read-target]'))root.ASMachOcrEnhancement?.decorateTarget(b,b.dataset.readTarget,b.textContent);
  function updateTargets(){for(const b of targets.children)b.disabled=!detailSelection||busy||options.readOnly;}
  function clearDetailSelection(){detailSelection=null;detailDrag=null;detailOutline.hidden=true;updateTargets();}
  function detailMetrics(){const r=detailImage.getBoundingClientRect(),W=detailImage.naturalWidth,H=detailImage.naturalHeight,k=Math.min(r.width/W,r.height/H);return{x:r.left+(r.width-W*k)/2,y:r.top+(r.height-H*k)/2,w:W*k,h:H*k};}
  function detailPoint(e,start=false){const r=detailMetrics();if(!Number.isFinite(r.w)||!r.w||!r.h)return null;const x=(e.clientX-r.x)/r.w,y=(e.clientY-r.y)/r.h;if(start&&(x<0||x>1||y<0||y>1))return null;return{x:Math.max(0,Math.min(1,x)),y:Math.max(0,Math.min(1,y))};}
  function paintDetail(b){const r=detailMetrics(),s=detailSurface.getBoundingClientRect();Object.assign(detailOutline.style,{left:r.x-s.left+b.x*r.w+'px',top:r.y-s.top+b.y*r.h+'px',width:b.w*r.w+'px',height:b.h*r.h+'px'});detailOutline.hidden=false;}
  detailSurface.onpointerdown=e=>{if(e.button!==0||busy||options.readOnly||(!options.applyPartial&&!options.crop))return;clearDetailSelection();const p=detailPoint(e,true);if(!p)return;e.preventDefault();detailSurface.focus({preventScroll:true});detailDrag={start:p,id:e.pointerId};detailSurface.setPointerCapture(e.pointerId);};
  detailSurface.onpointermove=e=>{if(detailDrag?.id!==e.pointerId)return;const p=detailPoint(e);if(p)paintDetail(box(detailDrag.start,p));};
  detailSurface.onpointerup=e=>{if(detailDrag?.id!==e.pointerId)return;const p=detailPoint(e),b=p?box(detailDrag.start,p):null;detailDrag=null;detailSurface.releasePointerCapture(e.pointerId);if(!b||b.w*detailImage.naturalWidth<2||b.h*detailImage.naturalHeight<2){clearDetailSelection();return;}detailSelection=b;paintDetail(b);updateTargets();hint.textContent='Alan seçildi. Nominal, tolerans veya kırpma düğmesini kullanın.';};
  detailSurface.onpointercancel=clearDetailSelection;detailImage.onload=clearDetailSelection;
  detailSurface.onkeydown=e=>{if(e.key==='Escape'){e.preventDefault();e.stopPropagation();clearDetailSelection();hint.textContent='Alan seçimi temizlendi.';}};
  toolbar.append(modes);detail.append(targets);
  viewport.addEventListener('wheel',e=>{if(!e.ctrlKey)return;e.preventDefault();e.stopPropagation();if(!drag)setZoom(zoom*Math.exp(-Math.max(-100,Math.min(100,e.deltaY*(e.deltaMode===1?16:e.deltaMode===2?260:1)))*.003),e);},{passive:false,capture:true});
  host.addEventListener('change',e=>e.stopPropagation());
  const style=make('style');style.textContent=`
   .wf-source-detail{background:#eaf0f5;border:1px solid #bdd3df;padding:2px;text-align:center}.wf-source-detail[hidden]{display:none!important}.wf-detail-label{text-align:left;font:10px Segoe UI;color:#48697c;margin-bottom:0}.wf-source-detail .wf-detail-image>img{display:block;margin:auto;width:100%;height:94px;object-fit:contain}
   .wf-source-detail{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:2px;align-items:center}.wf-source-detail>.wf-detail-image{grid-column:1;grid-row:1;min-width:0}.wf-source-detail>.wf-reading-targets{grid-column:2;grid-row:1;display:flex;flex-direction:column;flex-wrap:nowrap;gap:2px;padding:0;align-self:stretch;margin:0;justify-content:space-between}.wf-source-detail>.wf-reading-targets:empty{display:none}
   html body .wf-source-detail>.wf-source-tools:not(.wf-reading-targets){position:static!important;grid-column:1/-1;grid-row:2;justify-content:flex-start;padding:0;margin:0;gap:2px!important;transform:none!important}
   .wf-source-tools>.wf-reading-modes{display:contents!important}
   html body .cw-source-preview button,html body .wf-source-detail button{width:30px!important;height:30px!important;min-width:30px!important;min-height:30px!important;padding:2px!important;box-sizing:border-box;display:inline-flex!important;align-items:center;justify-content:center;border-radius:4px!important}
   html body .cw-source-preview button[hidden],html body .wf-source-detail button[hidden]{display:none!important}
   html body .cw-source-preview button img,html body .wf-source-detail button img{width:24px!important;height:24px!important;max-width:none!important;max-height:none!important}
   .wf-detail-image{position:relative;touch-action:none;cursor:crosshair;user-select:none}.wf-detail-selection{position:absolute;pointer-events:none;border:1px solid #00a06a;background:#00ba8030;box-sizing:border-box}.wf-detail-selection[hidden]{display:none!important}.wf-reading-targets button:disabled{opacity:.45;cursor:default}
   html body .wf-source-compact .wf-source-viewport,html body .wf-source-compact .wf-source-zoom,html body .wf-source-compact #cwSourceGrow{display:none!important}
   html body .wf-source-compact .cw-source-preview>.wf-source-tools:not(.wf-source-zoom){position:static!important;padding:3px 0;transform:none!important}
   html body #selectionForm.cw-inspector.cw-dense .wf-source-selecting .wf-source-viewport,html body .wf-source-selecting .wf-source-viewport{height:min(440px,55vh)!important}
   .wf-source-tools{display:flex;align-items:center;gap:4px;flex-wrap:wrap}.wf-dashboard .wf-source-tools .btn{min-height:24px;padding:3px 6px;font-size:10px}.wf-source-tools [aria-pressed=true]{background:#ddf5f7;border-color:#0094a8;color:#007b8d}
   .wf-source-viewport{display:block;position:relative;box-sizing:border-box;width:100%;max-width:100%;min-width:0;height:260px;contain:inline-size;background:#eaf1f5;border:1px solid #cbdfe8;border-radius:4px;overflow:auto;scrollbar-gutter:stable;overscroll-behavior:contain}
   .wf-source-stage{position:relative;min-width:100%;min-height:100%}.wf-source-viewport canvas{position:absolute;display:block;max-width:none!important;max-height:none!important;touch-action:none}.wf-source-viewport canvas:focus-visible{outline:2px solid #0096aa;outline-offset:-2px}
   .wf-source-zoom{justify-content:flex-end}.wf-source-zoom .btn{min-width:26px;min-height:24px;padding:3px 6px;font-size:11px}.wf-source-zoom-value{min-width:42px;text-align:center;font-size:10px;color:#557487;font-variant-numeric:tabular-nums}
   #automaticReviewModal .wf-review-grid{grid-template-columns:minmax(0,1fr) clamp(360px,29vw,460px)}
   @media(max-width:1100px){#automaticReviewModal .wf-review-grid{grid-template-columns:minmax(0,1fr) 350px}}
   .wf-source-hint{font-size:10px;line-height:1.4;color:#536f80}.wf-source-draft{display:grid;gap:6px;padding:7px;background:#eaf7fa;border:1px solid #bcdee5;border-radius:4px}.wf-source-draft .wf-source-tools{justify-content:flex-end}
   html body .wf-source-draft{grid-template-columns:minmax(0,1fr) auto;gap:4px 6px;padding:5px 6px;border-radius:3px;background:#f5fafc}html body .wf-source-draft>label{grid-column:1/-1;display:grid;gap:3px;font-size:11px;font-weight:600;margin:0}html body .wf-source-draft>label>textarea{box-sizing:border-box;width:100%;height:27px;min-height:27px;padding:3px 6px;font-size:12px}html body .wf-source-draft .wf-source-values{font-size:10px;line-height:1.35;align-self:center;overflow-wrap:anywhere}html body .wf-source-draft>.wf-source-tools{grid-column:2;grid-row:2;padding:0;gap:3px}html body .wf-source-draft .wf-source-tools .btn{display:grid;place-items:center;width:28px;height:26px;min-height:26px;padding:3px;border-radius:3px}
  `;host.append(style);
  function layout(){if(!region||disposed)return;const w=Math.max(32,viewport.clientWidth),h=Math.max(32,viewport.offsetHeight-18),scale=Math.min((w-16)/canvas.width,(h-16)/canvas.height)*zoom,cw=Math.max(1,canvas.width*scale),ch=Math.max(1,canvas.height*scale),sw=Math.max(w,cw+16),sh=Math.max(h,ch+16);stage.style.width=sw+'px';stage.style.height=sh+'px';canvas.style.width=cw+'px';canvas.style.height=ch+'px';canvas.style.left=(sw-cw)/2+'px';canvas.style.top=(sh-ch)/2+'px';zoomValue.value=Math.round(zoom*100)+'%';zoomValue.title='Bu panelin sığdırılmış görünümüne göre yakınlaştırma oranı';zoomRange.value=String(Math.log2(zoom));zoomRange.setAttribute('aria-valuetext',Math.round(zoom*100)+'%');}
  function setZoom(value,event){if(!region||disposed||drag)return;autoFocus=false;const vr=viewport.getBoundingClientRect(),cr=canvas.getBoundingClientRect(),px=event?event.clientX:vr.left+viewport.clientWidth/2,py=event?event.clientY:vr.top+viewport.clientHeight/2,ax=(px-cr.left)/cr.width,ay=(py-cr.top)/cr.height;zoom=Math.max(.25,Math.min(MAX_ZOOM,value));layout();viewport.scrollLeft=canvas.offsetLeft+ax*parseFloat(canvas.style.width)-(px-vr.left-viewport.clientLeft);viewport.scrollTop=canvas.offsetTop+ay*parseFloat(canvas.style.height)-(py-vr.top-viewport.clientTop);}
  function showView(all){whole=all;autoFocus=true;focusPending=true;draw();}
  function focusView(){if(!focusPending||!viewport.clientWidth)return;focusPending=false;const b=draft?.box||c.box,W=c.pageImage.width,H=c.pageImage.height,w=Math.max(32,viewport.clientWidth-16),h=Math.max(32,viewport.offsetHeight-34),base=Math.min(w/W,h/H);
   // Autofocus is deliberately calmer than manual zoom: retain drawing context,
   // and never enlarge a single digit to fill the entire preview.
   const scale=Math.min(w/Math.max(b.w*W*1.5,70),h/Math.max(b.h*H*2.5,70),96/Math.max(1,Math.min(b.w*W,b.h*H)),4);
   zoom=whole?1:Math.min(16,Math.max(1,scale/base));layout();viewport.scrollLeft=canvas.offsetLeft+(b.x+b.w/2)*parseFloat(canvas.style.width)-viewport.clientWidth/2;viewport.scrollTop=canvas.offsetTop+(b.y+b.h/2)*parseFloat(canvas.style.height)-viewport.clientHeight/2;if(whole)viewport.scrollTo(0,0);}
  const resize=typeof ResizeObserver==='function'?new ResizeObserver(()=>{focusPending=autoFocus;layout();focusView();}):null;resize?.observe(viewport);
  const detailResize=typeof ResizeObserver==='function'?new ResizeObserver(()=>{if(detailSelection&&!detail.hidden)paintDetail(detailSelection);}):null;detailResize?.observe(detailSurface);
  function current(){return !disposed&&host.isConnected&&(options.isCurrent?options.isCurrent():host.closest('.wf-dialog')?.classList.contains('open'));}
  function reset(){revision++;busy=false;clearDetailSelection();scope='all';draft=null;read=null;selecting=false;drag=null;options.onSelectionChange?.(false);form.hidden=true;cancel.hidden=true;canvas.style.cursor='';select.setAttribute('aria-pressed','false');[near,page,select,retry,apply,input].forEach(n=>n.disabled=false);showDetail();draw();}
  function draw(){
   if(!c.pageImage)return;
   const records=options.balloonRecords||[];
   const marker=candidate=>{
    const saved=records.find(a=>a.id===candidate.addedId),b=candidate.box;
    return saved||{number:candidate.plannedNumber,anchorX:b.x+b.w/2,anchorY:b.y+b.h/2,bubbleX:Math.min(.98,b.x+b.w+.025),bubbleY:Math.max(.025,b.y-.025),size:24,fontSize:13,color:'#008c9f'};
   };
   const item=marker(c),others=options.candidates.filter(other=>other!==c&&!other.addedId).map(candidate=>({candidate,item:marker(candidate),placed:!!candidate.plannedNumber}));
   for(const record of records){if(record.listOnly||record.id===c.addedId)continue;const b=record.selectionBox||{x:record.anchorX||0,y:record.anchorY||0,w:0,h:0};others.push({candidate:{box:b,page:record.page},item:record,placed:true});}
   region=root.ASMachCandidatePreview.paint(canvas,c,item,!!item.number,true,others,null,selecting||!!draft,true);
   canvas.dataset.balloonNumbers=JSON.stringify([...(item.number?[item.number]:[]),...others.filter(o=>o.placed&&Number(o.candidate.page)===Number(c.page)).map(o=>o.item.number)]);
   layout();focusView();near.setAttribute('aria-pressed',String(!whole));page.setAttribute('aria-pressed',String(whole));
   const b=drag?box(drag.start,drag.end):draft?.box;if(!b)return;
   const g=canvas.getContext('2d'),x=(b.x-region.x)/region.w*canvas.width,y=(b.y-region.y)/region.h*canvas.height,w=b.w/region.w*canvas.width,h=b.h/region.h*canvas.height;
   g.fillStyle='#00bfd833';g.fillRect(x,y,w,h);g.strokeStyle='#006aef';g.lineWidth=3;g.setLineDash([6,3]);g.strokeRect(x,y,w,h);
  }
  function point(e){const r=canvas.getBoundingClientRect(),clamp=v=>Math.max(0,Math.min(1,v));return{x:region.x+clamp((e.clientX-r.left)/r.width)*region.w,y:region.y+clamp((e.clientY-r.top)/r.height)*region.h};}
  function box(a,b){return{x:Math.min(a.x,b.x),y:Math.min(a.y,b.y),w:Math.abs(a.x-b.x),h:Math.abs(a.y-b.y)};}
  canvas.onpointerdown=e=>{if(!region||![0,1].includes(e.button))return;e.preventDefault();canvas.focus({preventScroll:true});if(!selecting||e.button===1||e.altKey){pan={x:e.clientX,y:e.clientY,left:viewport.scrollLeft,top:viewport.scrollTop,id:e.pointerId};canvas.setPointerCapture(e.pointerId);return;}if(busy)return;drag={start:point(e),end:point(e),id:e.pointerId};canvas.setPointerCapture(e.pointerId);};
  canvas.onpointermove=e=>{if(pan?.id===e.pointerId){viewport.scrollLeft=pan.left+pan.x-e.clientX;viewport.scrollTop=pan.top+pan.y-e.clientY;return;}if(!drag||drag.id!==e.pointerId)return;drag.end=point(e);draw();};
  canvas.onpointerup=e=>{
   if(pan?.id===e.pointerId){pan=null;canvas.releasePointerCapture(e.pointerId);return;}
   if(!drag||drag.id!==e.pointerId)return;const b=box(drag.start,point(e));drag=null;canvas.releasePointerCapture(e.pointerId);
   if(b.w*c.pageImage.width<8||b.h*c.pageImage.height<8){hint.textContent='Ölçü ve toleransları kapsayan daha büyük bir kutu çizin.';draw();return;}
   const crop=document.createElement('canvas');crop.width=Math.max(1,Math.round(b.w*c.pageImage.width));crop.height=Math.max(1,Math.round(b.h*c.pageImage.height));crop.getContext('2d').drawImage(c.pageImage,b.x*c.pageImage.width,b.y*c.pageImage.height,b.w*c.pageImage.width,b.h*c.pageImage.height,0,0,crop.width,crop.height);
   draft={box:b,snapshot:crop.toDataURL('image/png'),scope,enhancement:readingMode,autoApply:true};read=null;input.value='';selecting=false;canvas.style.cursor='';form.hidden=false;draw();showDetail(scope==='all'?draft.snapshot:c.snapshot,scope==='all'?draft.box:c.box);recognize();
  };
  canvas.onpointercancel=()=>{drag=null;pan=null;draw();};
  host.addEventListener('keydown',e=>{if(e.key==='Escape'&&(selecting||draft||busy)){e.preventDefault();e.stopPropagation();reset();hint.textContent='Seçim iptal edildi. Mevcut ölçü korundu.';}});
  async function recognize(){
   if(!draft||busy||!current())return;const edit={...draft},token=++revision;busy=true;updateTargets();[near,page,select,retry,apply,input].forEach(n=>n.disabled=true);hint.textContent='Seçim okunuyor…';
   try{const result=await options.recognize(edit);if(!current()||token!==revision)return;draft={...edit,box:result.box||edit.box,snapshot:result.snapshot||edit.snapshot,sourceTextHeight:result.sourceTextHeight??edit.sourceTextHeight};read=result;input.value=result.text||'';updateValues();draw();if(!input.value.trim())throw Error('Metin bulunamadı.');const applied={...draft,...readingEvidence(result),text:input.value,confidence:result.confidence,source:result.source,quiet:true};if(edit.scope&&edit.scope!=='all')options.applyPartial(applied);else options.apply(applied);appliedHint(applied);}
   catch(e){if(current()&&token===revision)hint.textContent='Okuma tamamlanamadı: '+e.message+' Yeniden deneyin veya metni elle girin. Mevcut ölçü korundu.';}
   finally{if(!disposed&&token===revision){busy=false;updateTargets();[near,page,select,retry,apply,input].forEach(n=>n.disabled=false);}}
  }
  showDetail();if(c.pageImage){draw();const saved=c.reviewed||c.parsed||c;hint.textContent=saved.ocrNeedsReview?'Kontrol gerekli. '+(saved.ocrReviewReason||'Nominal, tolerans ve işaretleri kaynak görüntüyle karşılaştırın.'):'';}else{hint.textContent='Kaynak sayfa görüntüsü yüklenemedi.';[near,page,select].forEach(n=>n.disabled=true);}
  if(options.readOnly){select.hidden=true;modes.hidden=true;targets.hidden=true;hint.textContent='Karakteristiğe eklendi. Bu görünüm salt okunurdur; düzenlemeler karakteristik listesinden yapılır.';}
  return{cancel:reset,dispose(){disposed=true;revision++;resize?.disconnect();detailResize?.disconnect();options.onSelectionChange?.(false);}};
 }
 root.ASMachCandidateSource={mount};
})(window);
