(function(root){
 'use strict';
 const columns=[['select','',30],['number','Balon',62],['state','İnceleme',112],['snapshot','Kaynak',100],['originalText','Okunan metin',140],['type','Tür',85],['nominalValue','Nominal',76],['lowerTolerance','Alt tolerans',86],['upperTolerance','Üst tolerans',86],['unit','Birim',52],['classification','Sınıf',102],['information','Uyarı',210],['actions','İşlemler',80],['requirement','Gereklilik',160],['page','Sayfa',48],['view','Görünüş',100],['lowerLimit','Alt limit',85],['upperLimit','Üst limit',85],['method','Yöntem',120],['frequency','Sıklık',140],['confidence','OCR %',60]];
 const storage='asmach.candidate-table.v2';let prefs={order:columns.map(c=>c[0]),hidden:['requirement','view','lowerLimit','upperLimit','method','frequency','confidence'],widths:{}},sort=null,context,dragged,menu;
 try{const p=JSON.parse(ASMachPreferences.getItem(storage));if(p){prefs.order=[...new Set([...(p.order||[]).filter(k=>columns.some(c=>c[0]===k)),...prefs.order])];prefs.hidden=(p.hidden||[]).filter(k=>k!=='select'&&columns.some(c=>c[0]===k));prefs.widths=p.widths||{};}}catch{}
 const save=()=>{try{ASMachPreferences.setItem(storage,JSON.stringify(prefs));}catch{}};
 const make=(tag,text)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n;};
function value(c,key,index){const r=c.reviewed||c.parsed;switch(key){case'originalText':return c.originalText??c.text;case'classification':return root.ASMachClassification.label(r.classification);case'number':return c.addedId?'#'+c.savedNumber:c.plannedNumber?'→ #'+c.plannedNumber:'—';case'state':return c.addedId?'✓ Eklendi':'Bekleyen';case'page':return c.page;case'view':return context.labels.get(c.scanRegion?.id||'legacy:'+c.page)||'';case'type':return r.type;case'requirement':return r.requirement||c.text;case'method':return c.plan.rolePlans?'Sorumlu bazlı plan':context.app.methodLabel(c.plan.inspectionMethod);case'frequency':return c.plan.rolePlans?'Sorumlu bazlı plan':root.ASMachInspectionPlan.label(c.plan);case'information':return context.error(c)||'Bilgiler tamam';case'confidence':return Math.round(c.confidence||0);default:return r[key]??'';}}
 function setup(){
  const compact=make('style');compact.textContent='#automaticReviewModal.wf-dashboard .wf-table.ct-columns td{box-sizing:border-box;max-height:40px}#automaticReviewModal.wf-dashboard .wf-table.ct-columns .wf-preview{height:34px;min-height:0;padding:0!important;width:90px;border:0;background:transparent}#automaticReviewModal.wf-dashboard .ct-review-state{width:100%;font-size:11px;height:26px;min-height:0;padding:2px;border:1px solid #d4e2ea;background:white;border-radius:3px}#automaticReviewModal.wf-dashboard .wf-table.ct-columns td[data-column=actions] .btn{height:25px;min-height:0;padding:2px 5px!important;font-size:11px}#automaticReviewModal.wf-dashboard .wf-table.ct-columns td[data-column=information]{font-size:10px!important}#automaticReviewModal.wf-dashboard .wf-filterbar{gap:4px}#automaticReviewModal.wf-dashboard .wf-filterbar .btn{min-height:28px;padding:4px 7px;font-size:11px}';document.head.append(compact);
  root.addEventListener('keydown',e=>{const editor=e.target.closest?.('.ct-cell-editor');if(!editor)return;if(['Escape','Enter'].includes(e.key)&&!e.isComposing){e.preventDefault();e.stopImmediatePropagation();if(e.key==='Escape')editor.querySelector('[data-cancel]').click();else editor.querySelector('form').requestSubmit();}},true);
  const body=document.getElementById('wfRows');body.addEventListener('click',e=>{if(e.target.closest('.ct-cell-editor'))return;const cell=e.target.closest('td[data-column]');if(!cell||!editable.includes(cell.dataset.column)||e.target.closest('button,input,select'))return;e.stopImmediatePropagation();clearTimeout(clickTimer);const index=Number(cell.closest('tr').dataset.index);clickTimer=setTimeout(()=>root.ASMachCandidateDashboard.select(index),250);},true);body.addEventListener('dblclick',e=>{if(e.target.closest('.ct-cell-editor'))return;const cell=e.target.closest('td[data-column]');if(!cell||!editable.includes(cell.dataset.column))return;e.preventDefault();e.stopImmediatePropagation();clearTimeout(clickTimer);editCell(Number(cell.closest('tr').dataset.index),cell.dataset.column);},true);body.addEventListener('keydown',e=>{if(e.target.closest('.ct-cell-editor'))return;const cell=e.target.closest('td[data-column]');if(cell&&editable.includes(cell.dataset.column)&&['Enter','F2'].includes(e.key)){e.preventDefault();e.stopPropagation();editCell(Number(cell.closest('tr').dataset.index),cell.dataset.column);}});
  const sharedStyle=make('style');sharedStyle.textContent='#automaticReviewModal.wf-dashboard .wf-table.ct-columns{font-family:"Segoe UI",Arial,sans-serif}#automaticReviewModal.wf-dashboard .wf-table.ct-columns td{height:36px;padding:2px 6px!important;font-size:12px!important;color:#38546c;border:0;border-bottom:1px solid #e6edf3}#automaticReviewModal.wf-dashboard .wf-table.ct-columns th{font-size:10px!important;padding:7px 6px;background:#eff5f9;color:#597084;letter-spacing:.3px;border:0;border-bottom:1px solid #cfdee8}#automaticReviewModal.wf-dashboard .wf-table.ct-columns td[data-editable]:hover{box-shadow:inset 0 -2px #2c9aa4}#automaticReviewModal.wf-dashboard .wf-table.ct-columns td:has(.ct-cell-editor){overflow:visible!important;position:relative;z-index:5}#automaticReviewModal.wf-dashboard .wf-table.ct-columns td .wf-preview img{width:88px;height:32px;max-height:32px;object-fit:contain}#automaticReviewModal.wf-dashboard .wf-table.ct-columns tr.ct-selected>td{background:#e5f5f8}';document.head.append(sharedStyle);
  const trigger=make('button','Sütunlar');trigger.className='btn';trigger.id='wfColumnPicker';document.querySelector('.wf-filterbar').append(trigger);menu=make('div');menu.id='wfTableColumns';menu.setAttribute('popover','auto');document.body.append(menu);
  trigger.onclick=()=>{menu.replaceChildren();for(const [key,title] of columns){if(key==='select')continue;const label=make('label'),input=make('input');input.type='checkbox';input.checked=!prefs.hidden.includes(key);input.onchange=()=>{prefs.hidden=input.checked?prefs.hidden.filter(k=>k!==key):[...prefs.hidden,key];save();context.refresh();};label.append(input,make('span',title));menu.append(label);}const reset=make('button','Varsayılan sütunlar');reset.className='btn';reset.onclick=()=>{prefs={order:columns.map(c=>c[0]),hidden:['requirement','view','lowerLimit','upperLimit','method','frequency','confidence'],widths:{}};save();menu.hidePopover();context.refresh();};menu.append(reset);menu.showPopover();const r=trigger.getBoundingClientRect(),b=menu.getBoundingClientRect();menu.style.left=Math.max(8,Math.min(r.left,innerWidth-b.width-8))+'px';menu.style.top=Math.max(8,Math.min(r.bottom+5,innerHeight-b.height-8))+'px';};
  const style=make('style');style.textContent=`#wfTableColumns{position:fixed;margin:0;width:410px;max-width:90vw;border:1px solid #cbdce6;border-radius:6px;padding:10px;background:white;box-shadow:0 8px 25px #173b4930}#wfTableColumns:popover-open{display:grid;grid-template-columns:repeat(3,1fr);gap:5px}#wfTableColumns label{font-size:11px;display:flex;align-items:center;gap:5px;padding:6px;background:#f1f6f9}#wfTableColumns input{width:14px;height:14px}#wfTableColumns button{grid-column:1/-1}.wf-dashboard .wf-table.ct-columns th{width:auto;white-space:nowrap;font-size:10px}.ct-heading{border:0;background:none;font:inherit;color:inherit;cursor:pointer;padding:0 9px 0 0}.ct-resize{position:absolute;right:0;top:0;bottom:0;width:6px;cursor:col-resize;touch-action:none}.wf-dashboard .wf-table.ct-columns td{height:31px;font-size:11px}.wf-dashboard .wf-table.ct-columns th.ct-subgroup{padding-left:22px;background:#f4f8fa}.wf-dashboard .wf-table.ct-columns tr.ct-group th{position:static}.wf-dashboard .wf-table.ct-columns .wf-preview img{max-height:25px}`;document.head.append(style);
 }
 function reviewRow(c,row,index){
  const disabled=document.getElementById('wfRun').disabled,status=row.querySelector('[data-column=state]');
  if(status){status.replaceChildren();const select=make('select');select.className='ct-review-state';select.setAttribute('aria-label','Aday '+(index+1)+' inceleme durumu');for(const [value,label]of [['','İncelenmedi'],['corrected','Düzeltildi'],['approved','Onaylandı'],['rejected','Reddedildi']])select.append(new Option(label,value));select.value=c.reviewStatus||'';select.disabled=disabled;select.onclick=e=>e.stopPropagation();select.onchange=e=>{e.stopPropagation();setReview(c,select.value);};status.append(select);if(c.addedId)status.append(make('small',' · Karakteristiğe eklendi'));}
  const actions=row.querySelector('[data-column=actions]');if(actions&&!c.addedId){const next=make('button','✓ →');next.className='btn ct-approve';next.title='Onayla ve sonraki incelenmemiş adaya geç';next.setAttribute('aria-label','Aday '+(index+1)+' onayla ve ilerle');next.disabled=disabled;next.onclick=e=>{e.stopPropagation();if(!setReview(c,'approved',false))return;const list=context.candidates,nextIndex=[...list.keys()].slice(index+1).concat([...list.keys()].slice(0,index)).find(i=>context.visible(list[i])&&!['approved','rejected'].includes(list[i].reviewStatus));if(nextIndex!==undefined)root.ASMachCandidateDashboard.select(nextIndex);else context.refresh();};actions.prepend(next);}
  const check=row.querySelector('[data-column=select] input');if(check&&c.reviewStatus==='rejected'){check.checked=false;check.disabled=true;}
  const source=row.querySelector('[data-column=snapshot] img');if(source){source.loading='lazy';source.style.objectFit='contain';}
 }
 function setReview(c,status,refresh=true){
  root.ASMachSharedCandidateInspector.park();
  if(status==='approved'&&context.error(c)){context.app.toast(context.error(c),true);context.refresh();return false;}
  c.reviewStatus=status;if(status==='rejected')c.selected=false;
  if(c.addedId){const record=context.app.state.annotations.find(r=>r.id===c.addedId);if(record){context.app.checkpoint();record.candidateReviewStatus=status;context.app.recordChange('Algılama inceleme durumu güncellendi',record);}}
  if(refresh)context.refresh();return true;
 }
 const collapsed=new Set();
 const editable=['type','requirement','nominalValue','unit','lowerTolerance','upperTolerance','lowerLimit','upperLimit','method','frequency','classification'];let clickTimer;
 function editCell(index,column){
  if(document.getElementById('wfRun').disabled)return;root.ASMachCandidateDashboard.select(index);const data=context,c=data.candidates[index],record=root.ASMachSharedCandidateInspector.recordFor(c);if(!record)return;const key=({method:'inspectionMethod',frequency:'inspectionFrequency'})[column]||column;
  if(record.rolePlans&&['method','frequency'].includes(column)){document.getElementById('cwInspectorTab2')?.click();data.app.toast('Sorumlu bazlı yöntemi ve sıklığı Denetleme bölümünden düzenleyin.');return;}
  const cell=document.querySelector('#wfRows tr[data-index="'+index+'"] [data-column="'+column+'"]');if(!cell)return;document.querySelector('.ct-cell-editor')?.remove();const d=make('div');d.className='acui-cell-dialog acui-cell-inline ct-cell-editor';d.innerHTML='<form><div data-control></div><footer><button type="button" data-cancel title="Vazgeç (Esc)">×</button><button type="submit" title="Uygula (Enter)">✓</button></footer></form>';const numeric=['nominalValue','lowerTolerance','upperTolerance','lowerLimit','upperLimit'].includes(key),options=key==='classification'?[...document.getElementById('characteristicClass').options].map(o=>({value:o.value,label:o.textContent})):key==='type'?[...document.getElementById('characteristicType').options].map(o=>({value:o.value,label:o.textContent})):key==='unit'?root.ASMachCharacteristicEditing.unitsForType(record.type).map(v=>({value:v,label:v||'Birim yok'})):key==='inspectionMethod'?data.app.getMethods():key==='inspectionFrequency'?root.ASMachInspectionPlan.FREQUENCIES:null,input=make(options?'select':'input');input.setAttribute('aria-label','Yeni değer');if(options)options.forEach(o=>input.append(new Option(o.label,o.value)));input.value=record[key]??'';if(numeric)input.inputMode='decimal';d.querySelector('[data-control]').append(input);cell.append(d);cell.style.overflow='visible';cell.style.position='relative';let busy=false;const close=()=>d.remove();d.querySelector('[data-cancel]').onclick=close;d.addEventListener('click',e=>e.stopPropagation());d.addEventListener('change',e=>e.stopPropagation());d.addEventListener('keydown',e=>{e.stopPropagation();if(e.key==='Escape'){e.preventDefault();close();}if(e.key==='Enter'){e.preventDefault();d.querySelector('form').requestSubmit();}});input.oninput=()=>input.setCustomValidity('');
  d.querySelector('form').onsubmit=async e=>{e.preventDefault();if(busy)return;if(root.ASMachSharedCandidateInspector.recordFor(c)!==record){close();return;}const patch={[key]:input.value};if(numeric){const n=record.type==='Açı'?root.ASMachRequirements.parseAngle(input.value):Number(input.value.trim().replace(',','.'));if(!input.value.trim()||n==null||!Number.isFinite(n)){input.setCustomValidity('Geçerli bir sayı girin.');input.reportValidity();return;}patch[key]=String(n);const next={...record,...patch},fmt=n=>String(Number(n.toFixed(10)));if(key.endsWith('Limit')){const lo=Number(next.lowerLimit),hi=Number(next.upperLimit);if(!String(next.lowerLimit??'').trim()||!String(next.upperLimit??'').trim()||lo>hi){input.setCustomValidity('Alt limit üst limiti aşamaz; iki limiti de girin.');input.reportValidity();return;}const mid=(lo+hi)/2;Object.assign(patch,{nominalValue:fmt(mid),lowerTolerance:fmt(lo-mid),upperTolerance:fmt(hi-mid)});}else for(const [tol,lim] of [['lowerTolerance','lowerLimit'],['upperTolerance','upperLimit']])patch[lim]=next.nominalValue!==''&&next[tol]!==''?fmt(Number(next.nominalValue)+Number(next[tol])):'';patch.toleranceExplicit=true;patch.toleranceStandard='Manuel düzenleme';}
   const beforeEdit=JSON.stringify(record);busy=true;try{if(['classification','inspectionMethod','inspectionFrequency','requirement'].includes(key)){if(key==='inspectionFrequency'&&['CUSTOM','EVERY_N_PIECES','EVERY_N_HOURS'].includes(patch[key])){close();document.getElementById('cwInspectorTab2')?.click();data.app.toast('Aralık ve açıklamayı Denetleme bölümünde tamamlayın.');return;}data.app.checkpoint();Object.assign(record,patch);if(key==='requirement'){record.requirementMode='manual';record.autoParse=false;}if(key==='inspectionMethod')data.app.applyMethodStyle(record,patch[key]);data.app.recordChange('Aday tablo hücresi düzenlendi',record);}else await root.ASMachCharacteristicEditing.confirmCorrection(data.app,record,patch);if(JSON.stringify(record)!==beforeEdit){c.reviewStatus='corrected';if(c.addedId)record.candidateReviewStatus='corrected';}close();root.ASMachSharedCandidateInspector.park();data.refresh();}finally{busy=false;}
  };input.focus();input.select?.();
 }
 function applyMissingGeneral(c,app){
  const r=c.parsed;if(c.addedId||c.reviewed||!r||r.toleranceExplicit||r.toleranceAmbiguous||r.fitClass||r.threadClass)return;
  if([r.lowerTolerance,r.upperTolerance].some(v=>v!==''&&v!=null))return;
  if(!app.state.generalTolerance?.standard)return;
  const parsed=app.parseRequirement(c.text,app.state.generalTolerance.standard,c.forcedType||r.type,r.referenceLength||0);
  if(!parsed.toleranceStandard||parsed.toleranceExplicit||parsed.toleranceAmbiguous||String(parsed.nominalValue)!==String(r.nominalValue))return;
  if(![parsed.lowerTolerance,parsed.upperTolerance].some(v=>v!==''&&v!=null))return;
  for(const key of ['lowerTolerance','upperTolerance','lowerLimit','upperLimit','toleranceStandard'])r[key]=parsed[key];
  c.generalToleranceSource=parsed.toleranceStandard;
 }
 function render(data){context=data;if(!menu)setup();const table=document.querySelector('.wf-table'),body=document.getElementById('wfRows'),head=table.querySelector('thead tr');table.classList.add('ct-columns');
  const visibleCols=prefs.order.filter(k=>!prefs.hidden.includes(k)),rows=new Map();for(const row of body.querySelectorAll('tr[data-index]'))rows.set(Number(row.dataset.index),row);
  head.replaceChildren();table.querySelector('colgroup')?.remove();const cols=make('colgroup');let total=0;
  for(const key of visibleCols){const def=columns.find(c=>c[0]===key),minimum=Math.max(32,...def[1].split(/\s+/).map(word=>word.length*7+24)),w=Math.max(minimum,Math.min(600,Number(prefs.widths[key])||def[2])),col=make('col');col.style.width=w+'px';cols.append(col);total+=w;const th=make('th');th.dataset.column=key;const b=make('button',def[1]+(sort?.key===key?(sort.desc?' ↓':' ↑'):''));b.className='ct-heading';b.type='button';b.onclick=()=>{if(['snapshot','select','actions'].includes(key))return;sort={key,desc:sort?.key===key?!sort.desc:false};context.refresh();};th.append(b);th.draggable=key!=='select';th.ondragstart=()=>dragged=key;th.ondragover=e=>e.preventDefault();th.ondrop=e=>{e.preventDefault();if(!dragged||dragged===key||key==='select')return;prefs.order=prefs.order.filter(k=>k!==dragged);prefs.order.splice(prefs.order.indexOf(key),0,dragged);save();context.refresh();};const grip=make('span');grip.className='ct-resize';grip.onpointerdown=e=>{e.preventDefault();e.stopPropagation();th.draggable=false;const x=e.clientX,start=col.getBoundingClientRect().width;const move=e=>{const next=Math.round(Math.max(minimum,Math.min(600,start+e.clientX-x)));prefs.widths[key]=next;col.style.width=next+'px';table.style.width=total+next-w+'px';};const up=()=>{document.removeEventListener('pointermove',move);document.removeEventListener('pointerup',up);save();context.refresh();};document.addEventListener('pointermove',move);document.addEventListener('pointerup',up,{once:true});};th.append(grip);head.append(th);}
  table.prepend(cols);table.style.width=Math.max(total,table.parentElement.clientWidth-2)+'px';
  for(const [index,row] of rows){const c=data.candidates[index];c.originalText??=c.text;const old=[...row.children];row.replaceChildren();for(const key of visibleCols){let td;if(key==='select')td=old[0];else if(key==='snapshot')td=old[2];else{td=make('td',String(value(c,key,index)));td.title=td.textContent;if(key==='information'&&data.error(c))td.style.color='#93600b';}if(key==='actions'){td.replaceChildren();if(!c.addedId){const del=make('button','×');del.className='btn ct-delete';del.title='Yanlış / fazla adayı sil';del.setAttribute('aria-label',`Aday ${index+1} sil`);del.onclick=e=>{e.stopPropagation();data.removeCandidates([c]);};del.disabled=document.getElementById('wfRun').disabled;td.append(del);}else td.textContent='—';}if(c.addedId&&key==='select'){const check=td.querySelector('input');if(check){check.disabled=true;check.checked=false;check.title='Bu ölçü zaten karakteristiğe eklendi.';}}if(c.addedId&&key==='snapshot'){const button=td.querySelector('button');if(button){button.removeAttribute('data-preview');button.setAttribute('aria-label','Eklenen ölçünün kaynak görüntüsü');button.onclick=e=>{e.stopPropagation();row.click();};}}if(key==='state'){td.style.color=c.addedId?'#087949':'#627c8b';td.style.fontWeight='600';}td.dataset.column=key;row.append(td);}}
  for(const [index,row] of rows){const r=data.candidates[index].reviewed||data.candidates[index].parsed;if(r.toleranceStandard&&!r.toleranceExplicit&&!r.toleranceAmbiguous&&[r.lowerTolerance,r.upperTolerance].some(v=>v!==''&&v!=null)){
   const cell=row.querySelector('[data-column=requirement]');if(cell){const note=make('small',`Genel: ${r.lowerTolerance||'0'} / ${r.upperTolerance||'0'}`);note.style.cssText='display:block;color:#007987;font-size:10px';note.title=r.toleranceStandard;cell.append(note);}
   for(const cell of row.querySelectorAll('[data-column=lowerTolerance],[data-column=upperTolerance],[data-column=lowerLimit],[data-column=upperLimit]'))cell.title='Genel tolerans: '+r.toleranceStandard;
  }}
  for(const [index,row] of rows){const r=data.candidates[index].reviewed||data.candidates[index].parsed;if(r.type==='GD&T'){const cell=row.querySelector('[data-column=requirement]');if(cell)cell.innerHTML=root.ASMachGdtReport.markup(r,27);}}
  const indexes=data.candidates.map((c,i)=>i).filter(i=>data.visible(data.candidates[i]));if(sort)indexes.sort((a,b)=>{const va=value(data.candidates[a],sort.key,a),vb=value(data.candidates[b],sort.key,b);return String(va).localeCompare(String(vb),'tr',{numeric:true})*(sort.desc?-1:1);});
  const mode=document.getElementById('wfGrouping').value;body.replaceChildren();
  const groupBy=(list,fn)=>{const m=new Map();list.forEach(i=>{const k=fn(data.candidates[i]);if(!m.has(k))m.set(k,[]);m.get(k).push(i);});return m;};
  function header(key,title,list,sub=false){const tr=make('tr');tr.className='ct-group';const th=make('th');th.colSpan=visibleCols.length;th.className=sub?'ct-subgroup':'';
   const eligible=list.map(i=>data.candidates[i]).filter(c=>!c.addedId&&c.reviewStatus!=='rejected'),selected=eligible.filter(c=>c.selected).length,check=make('input');check.type='checkbox';check.checked=eligible.length>0&&selected===eligible.length;check.indeterminate=selected>0&&selected<eligible.length;check.disabled=!eligible.length||document.getElementById('wfRun').disabled;check.setAttribute('aria-label',title+' grubunu seç / seçimi kaldır');check.style.cssText='vertical-align:middle;margin:0 8px 0 2px;width:14px;height:14px';check.onclick=e=>e.stopPropagation();check.onchange=e=>{e.stopPropagation();eligible.forEach(c=>c.selected=check.checked);data.refresh();};
   const b=make('button',`${collapsed.has(key)?'▸':'▾'} ${title} · ${list.length} kayıt · ${selected} seçili`);b.className='ct-heading';b.setAttribute('aria-expanded',String(!collapsed.has(key)));b.onclick=()=>{collapsed.has(key)?collapsed.delete(key):collapsed.add(key);data.refresh();};th.append(check,b);tr.append(th);body.append(tr);return !collapsed.has(key);}
  const append=list=>list.forEach(i=>{const row=rows.get(i);if(row){row.hidden=false;body.append(row);}});
  if(mode==='none')append(indexes);else if(mode==='type'){for(const [type,list] of groupBy(indexes,c=>c.parsed.type))if(header('type:'+type,type,list))append(list);}else{for(const [key,list] of groupBy(indexes,c=>c.scanRegion?.id||'legacy:'+c.page)){if(!header('view:'+key,data.labels.get(key)||'Görünüş',list))continue;if(mode==='view-type'){for(const [type,sub] of groupBy(list,c=>c.parsed.type))if(header(key+':'+type,type,sub,true))append(sub);}else append(list);}}
  for(const [index,row] of rows){row.classList.toggle('ct-selected',!!data.candidates[index].selected&&!data.candidates[index].addedId);for(const cell of row.querySelectorAll('td[data-column]'))if(editable.includes(cell.dataset.column)){cell.dataset.editable=cell.dataset.column;cell.tabIndex=0;cell.title+=' · Çift tık / F2: düzenle';}}
  for(const [index,row] of rows)reviewRow(data.candidates[index],row,index);
  if(!indexes.length){const tr=make('tr'),td=make('td'),empty=make('div');empty.className='wf-empty-state';empty.append(make('strong',data.candidates.length?'Bu filtrede aday yok':'Henüz tarama sonucu yok'),make('span',data.candidates.length?'Filtreleri değiştirerek diğer kayıtları görüntüleyebilirsiniz.':'Görünüşleri seçip taramayı başlatın.'));const added=data.candidates.filter(c=>c.addedId).length;if(added&&!data.showAdded&&data.showAddedRecords){const b=make('button','Eklenen '+added+' kaydı göster');b.className='btn';b.onclick=data.showAddedRecords;empty.append(b);}if(data.candidates.length&&data.clearFilters){const b=make('button','Filtreleri temizle');b.className='btn';b.onclick=data.clearFilters;empty.append(b);}td.colSpan=visibleCols.length;td.append(empty);tr.append(td);body.append(tr);}
 }
 root.ASMachCandidateTable={render,applyMissingGeneral};
})(window);
