(function(root){
 'use strict';let app,ops,sampling,stamp;const el=(tag,text)=>{const e=document.createElement(tag);if(text)e.textContent=text;return e;};
 function refresh(){if(!app)return;const r=app.selectedAnnotation(),pane=document.getElementById('ipControlPane');if(!r||!pane)return;document.getElementById('productionLinksButton')?.remove();pane.querySelector('.ct-trace')?.setAttribute('hidden','');
  if(!ops){ops=el('section');ops.id='inlineOperations';pane.append(ops);sampling=el('section');sampling.id='inlineSampling';pane.querySelector('.ct-common').append(sampling);}
  ops.replaceChildren();const production=root.ASMachProduction.data(app.state),links=root.ASMachProduction.links(r);const label=el('label');label.className='field';label.append(el('span','Operasyon'));const select=el('select');select.setAttribute('aria-label','Operasyon bağlantısı');const empty=el('option',production.operations.length?'Operasyon seçin':'Tanımlı operasyon yok');empty.value='';select.append(empty);for(const op of production.operations){const option=el('option',root.ASMachProduction.operationLabel(app.state,op.id));option.value=op.id;option.disabled=links.some(l=>l.operationId===op.id);select.append(option);}label.append(select);ops.append(label);select.onchange=()=>{if(!select.value)return;app.checkpoint();r.operationLinks=[...links,{operationId:select.value}];app.recordChange('Operasyon bağlandı',r);app.renderAll();};
  for(const link of links){const row=el('div');row.style.cssText='display:flex;gap:6px;align-items:center;margin:4px 0;font-size:11px';row.append(el('span',root.ASMachProduction.operationLabel(app.state,link.operationId)||'Bulunamayan operasyon'));const remove=el('button','×');remove.type='button';remove.className='btn';remove.setAttribute('aria-label','Operasyon bağlantısını kaldır');remove.onclick=()=>{if(production.evidence.some(e=>e.characteristicId===r.id&&e.operationId===link.operationId)){app.toast('Bu operasyona bağlı muayene kaydı var; bağlantı kaldırılamaz.',true);return;}app.checkpoint();r.operationLinks=links.filter(l=>l!==link);app.recordChange('Operasyon bağlantısı kaldırıldı',r);app.renderAll();};row.append(remove);ops.append(row);}
  const key=JSON.stringify([app.state.fileData?.length,r.id,r.commonPlanEnabled,r.commonSampling,r.rolePlans,r.inspectionFrequency,app.state.metadata?.inspectionReport?.lotSize]);if(key===stamp)return;stamp=key;sampling.replaceChildren();const draft={...root.ASMachRolePlans.blank(),sampleMode:r.inspectionFrequency==='EACH_PART'?'all':'manual',...r.commonSampling};const controls=[];
  const field=(name,title,options)=>{const label=el('label');label.className='field';label.append(el('span',title));const input=el(options?'select':'input');if(options)for(const [value,title]of options){const o=el('option',title);o.value=value;input.append(o);}input.value=draft[name]||'';input.dataset.sampling=name;input.setAttribute('aria-label',title);label.append(input);sampling.append(label);controls.push(input);input.onchange=()=>{app.checkpoint();draft[name]=input.value;r.commonSampling={...draft};stamp=null;app.recordChange('Ortak numune planı güncellendi',r);app.renderAll();};return label;};
  field('sampleStandard','Numune standardı',[['reference','Mevcut referans tablosu'],['custom','Standart / müşteri planı (manuel)']]);const note=field('sampleStandardNote','Ad / revizyon');field('sampleMode','Numune seçimi',[['none','Belirtilmedi'],['manual','Manuel adet'],['table','Tabloya göre'],['all','%100 kontrol']]);const level=field('sampleLevel','Seviye',root.ASMachRolePlans.levels.map(v=>[v,v])),count=field('sampleCount','Numune adedi');
  const message=el('small');message.setAttribute('role','status');sampling.append(message);const apply=el('button','Numune planını uygula');apply.type='button';apply.className='btn';sampling.append(apply);
  function visibility(){note.hidden=draft.sampleStandard!=='custom';level.hidden=draft.sampleMode!=='table';count.hidden=draft.sampleMode!=='manual';for(const c of controls)c.disabled=r.commonPlanEnabled!==true;apply.hidden=true;const lot=app.state.metadata?.inspectionReport?.lotSize;for(const option of level.querySelector('select').options){const result=root.ASMachRolePlans.sample({...draft,sampleLevel:option.value,sampleMode:'table'},lot);option.textContent=option.value+' - P:'+(lot||'—')+' - N:'+(result.error?'—':result.count);}message.textContent=r.commonPlanEnabled?root.ASMachRolePlans.samplingError({...draft,inspectionFrequency:r.inspectionFrequency},'quality',lot||undefined):'Ortak numune ayarları saklanır; etkin plana geçildiğinde kullanılır.';}
  apply.onclick=()=>{const plan={...draft,inspectionFrequency:r.inspectionFrequency};const error=plan.sampleMode==='none'&&r.inspectionFrequency!=='EACH_PART'?'':root.ASMachRolePlans.samplingError(plan,'legacy',app.state.metadata?.inspectionReport?.lotSize||undefined);if(error){message.textContent=error;return;}app.checkpoint();r.commonSampling={...draft};app.recordChange('Ortak numune planı güncellendi',r);stamp=null;app.renderAll();message.textContent='Numune planı kaydedildi.';};visibility();
 }
 root.ASMachInspectionInline={init(bridge){app=bridge;refresh();},refresh};
})(window);
