/* Keep live controls and bindings; only reorganize the property sheet. */
(function(root){
 'use strict';
 function init(){const form=document.getElementById('selectionForm');if(!form||form.dataset.compactInspector)return;form.dataset.compactInspector='true';
  const nav=form.querySelector('.ip-tabs'),scroll=form.querySelector('.ip-scroll');if(!nav||!scroll)return;
  let prefs={};try{prefs=JSON.parse(ASMachPreferences.getItem('asmach.inspector.sections.v1'))||{};}catch{}
  const groups=[];
  for(const [key,title,initial] of [['Data','Genel · Ölçü ve kaynak',true],['Control','Denetleme · Kontrol planı',false],['Style','Balonlama · Görünüm',false]]){
   const old=document.getElementById('ip'+key+'Tab'),pane=document.getElementById('ip'+key+'Pane'),group=document.createElement('section'),button=document.createElement('button');group.className='ic-group';button.type='button';button.id=old.id;button.className='ic-heading';button.textContent=title;button.setAttribute('aria-controls',pane.id);pane.setAttribute('role','region');pane.setAttribute('aria-labelledby',button.id);group.append(button,pane);scroll.append(group);old.remove();
   function set(open){pane.hidden=!open;button.setAttribute('aria-expanded',String(open));group.classList.toggle('is-open',open);prefs[key]=open;}
   set(typeof prefs[key]==='boolean'?prefs[key]:initial);button.onclick=()=>{root.ASMachCharacteristicInspector?.cancelSource?.();set(pane.hidden);try{ASMachPreferences.setItem('asmach.inspector.sections.v1',JSON.stringify(prefs));}catch{}};groups.push({button,pane,set});
  }
  nav.remove();
  const source=form.querySelector('.ci-source');if(source){const box=document.createElement('details'),summary=document.createElement('summary');box.className='ic-source-fold';summary.textContent='Kaynak görüntü';box.open=prefs.Source!==false;source.before(box);source.querySelector('h3')?.remove();box.append(summary,source);box.addEventListener('toggle',()=>{prefs.Source=box.open;if(!box.open)root.ASMachCharacteristicInspector?.cancelSource?.();try{ASMachPreferences.setItem('asmach.inspector.sections.v1',JSON.stringify(prefs));}catch{}});}
  const tools=document.createElement('div');tools.className='ic-section-tools';for(const [label,open] of [['Tümünü aç',true],['Tümünü daralt',false]]){const b=document.createElement('button');b.type='button';b.className='btn';b.textContent=label;b.onclick=()=>{root.ASMachCharacteristicInspector?.cancelSource?.();groups.forEach(g=>g.set(open));try{ASMachPreferences.setItem('asmach.inspector.sections.v1',JSON.stringify(prefs));}catch{}};tools.append(b);}scroll.before(tools);
  for(const [id,text] of [['lowerTolerance','Alt tol.'],['upperTolerance','Üst tol.'],['characteristicType','Tür'],['evaluationMethod','Değerlendirme']]){const l=form.querySelector(`label[for="${id}"]`);if(l){l.textContent=text;l.title=id==='lowerTolerance'?'Alt tolerans':id==='upperTolerance'?'Üst tolerans':text;}}
  for(const id of ['nominalValue','characteristicType','selectedGdtSubtype','inspectionMethod'])document.getElementById(id)?.closest('.field')?.classList.add('ic-wide');
  const style=document.createElement('style');style.textContent=`
   #selectionForm[data-compact-inspector]{font-size:11px}#selectionForm[data-compact-inspector] .ip-identity{padding:6px 8px;gap:8px}#selectionForm[data-compact-inspector] .ci-number{width:132px;display:grid;grid-template-columns:45px 1fr;gap:3px;align-items:center}#selectionForm[data-compact-inspector] .ci-number-actions{grid-column:1/-1;margin:0}#selectionForm[data-compact-inspector] .ci-number input{height:26px!important;min-height:26px!important;font-size:14px!important}#selectionForm[data-compact-inspector] .ci-number-hint{grid-column:1/-1;margin:0;font-size:9px;line-height:1.2}#selectionForm[data-compact-inspector] .ip-location{gap:2px;padding:0}
   #selectionForm .ic-section-tools{display:flex;justify-content:flex-end;gap:4px;padding:3px 7px}#selectionForm .ic-section-tools .btn{font-size:9px;min-height:21px;padding:2px 5px}#selectionForm[data-compact-inspector] .ip-scroll{padding:4px 6px;display:block}#selectionForm .ic-group{border:1px solid #ccdfe8;border-radius:5px;margin-bottom:5px;overflow:hidden;background:white}#selectionForm .ic-heading{display:flex;align-items:center;gap:6px;width:100%;padding:7px 8px;border:0;background:#eaf3f7;color:#164256;font-size:11px;font-weight:600;text-align:left;cursor:pointer}#selectionForm .ic-heading:before{content:'▸';font-size:10px}#selectionForm .is-open>.ic-heading:before{content:'▾'}#selectionForm .ic-heading:focus-visible{outline:2px solid #008e9e;outline-offset:-2px}#selectionForm[data-compact-inspector] .ip-pane{padding:5px;gap:5px}#selectionForm[data-compact-inspector] [hidden]{display:none!important}
   #selectionForm[data-compact-inspector] .ip-section{padding:5px;border-radius:4px;margin:0}#selectionForm[data-compact-inspector] .ip-section h3{font-size:10px;margin:0 0 5px}#selectionForm[data-compact-inspector] .field{display:grid;grid-template-columns:minmax(48px,32%) minmax(0,1fr);align-items:center;gap:4px;margin:0;min-width:0}#selectionForm[data-compact-inspector] .field>label{font-size:10px;margin:0;line-height:1.2;overflow-wrap:anywhere}#selectionForm[data-compact-inspector] .field>small,#selectionForm[data-compact-inspector] .field>.requirement-actions{grid-column:1/-1}#selectionForm[data-compact-inspector] .field input,#selectionForm[data-compact-inspector] .field select{height:26px;min-height:26px;padding:3px 5px;font-size:11px;min-width:0;width:100%}#selectionForm[data-compact-inspector] .field textarea{height:38px;min-height:34px;padding:4px;font-size:11px;min-width:0;width:100%;resize:vertical}#selectionForm[data-compact-inspector] .ip-grid{grid-template-columns:repeat(2,minmax(0,1fr));gap:5px}#selectionForm[data-compact-inspector] .ic-wide{grid-column:1/-1}#selectionForm[data-compact-inspector] .ip-grid .field:not(.ic-wide){grid-template-columns:minmax(38px,42%) minmax(0,1fr)}#selectionForm[data-compact-inspector] .ip-section-head .field{display:flex;gap:4px}#selectionForm[data-compact-inspector] .ip-section-head .field input{width:52px}
   #selectionForm[data-compact-inspector] label.field{font-size:10px;color:#4d6e82}#selectionForm[data-compact-inspector] .ci-help{font-size:9px;line-height:1.3;margin:3px 0 0}#selectionForm[data-compact-inspector] .ci-inline-actions{margin-top:4px}#selectionForm[data-compact-inspector] .ci-inline-actions .btn{min-height:23px;padding:3px 6px;font-size:10px}#selectionForm[data-compact-inspector] .ci-source-editor{gap:3px}#selectionForm[data-compact-inspector] .wf-source-viewport{height:190px}#selectionForm[data-compact-inspector] .ci-plan-summary{grid-template-columns:1fr 1fr;gap:4px}#selectionForm[data-compact-inspector] .ci-plan-summary>p{grid-column:1/-1}#selectionForm[data-compact-inspector] .ci-role-card{padding:5px;font-size:10px}#selectionForm[data-compact-inspector] .ip-footer{padding:5px 6px;gap:4px}#selectionForm[data-compact-inspector] .ip-footer .btn{min-height:25px;padding:4px 6px;font-size:10px}#selectionForm[data-compact-inspector] .ip-note{font-size:10px;margin:2px 0}
  `;document.head.append(style);
  redesign(form,scroll);
  style.textContent+='#selectionForm .ic-source-fold{border:1px solid #d5e3eb;border-radius:4px}#selectionForm .ic-source-fold>summary{padding:5px 6px;font-size:10px;font-weight:600;color:#245369;cursor:pointer;background:#f3f8fa}#selectionForm .ic-source-fold>.ci-source{border:0}';
 }
 function redesign(form,scroll){
  const $=id=>document.getElementById(id),data=$('ipDataPane'),fold=form.querySelector('.ic-source-fold'),source=document.createElement('section');source.className='ic-group';const head=document.createElement('button');head.type='button';head.className='ic-heading';head.id='ipSourceTab';head.textContent='Kaynak ve OCR';const pane=document.createElement('div');pane.className='ip-pane';pane.id='ipSourcePane';pane.setAttribute('role','region');pane.setAttribute('aria-labelledby',head.id);head.setAttribute('aria-controls',pane.id);pane.append(form.querySelector('.ci-source'),form.querySelector('.ci-ocr'));fold.remove();source.append(head,pane);data.closest('.ic-group').after(source);const set=open=>{pane.hidden=!open;head.setAttribute('aria-expanded',String(open));source.classList.toggle('is-open',open);};set(false);head.onclick=()=>{root.ASMachCharacteristicInspector?.cancelSource?.();set(pane.hidden);};
  $('ipDataTab').textContent='Ölçü ve tolerans';$('ipControlTab').textContent='Kontrol ve denetleme';$('ipStyleTab').textContent='Balon görünümü';
  form.querySelectorAll('.ic-section-tools button').forEach(b=>b.addEventListener('click',()=>set(b.textContent==='Tümünü aç')));
  const extended=$('ipExtended'),advanced=document.createElement('details'),summary=document.createElement('summary');advanced.className='ic-advanced';summary.textContent='Genel tolerans ayarları';advanced.append(summary);const replace=$('ipReplaceTolerance').closest('label');replace.classList.add('ic-check');for(const n of [$('ipGeneralChoice').closest('label'),$('ipReferenceLength').closest('label'),replace,$('ipApplyGeneral'),$('ipLimitMessage')])advanced.append(n);extended.append(advanced);extended.querySelector('h3').textContent='Kabul limitleri';
  $('acuiDetailsOpen').textContent='Ayrıntılı düzenle ↗';$('acuiDetailsOpen').style.setProperty('background','#eef7fa','important');$('acuiDetailsOpen').style.setProperty('color','#246a80','important');
  const css=document.createElement('style');css.textContent=`
  #selectionForm[data-compact-inspector]{background:#f4f7fa;color:#214257}#selectionForm[data-compact-inspector] .ip-identity{background:white;padding:10px;gap:12px;border-bottom:1px solid #dce6ed}#selectionForm[data-compact-inspector] .ci-number input{height:31px!important;min-height:31px!important;font-size:16px!important}#selectionForm[data-compact-inspector] .ip-location{gap:4px;padding-top:2px}#selectionForm[data-compact-inspector] .ip-scroll{padding:0 8px 8px;scrollbar-gutter:stable}#selectionForm .ic-section-tools{padding:6px 9px;gap:7px}#selectionForm .ic-section-tools .btn{font-size:10px;min-height:25px;padding:4px 6px;background:transparent;border:0;color:#526f83}
  #selectionForm .ic-group{border:1px solid #d9e4eb;border-radius:8px;margin-bottom:8px;background:white}#selectionForm .ic-heading{padding:11px 10px;background:white;font-size:12px;font-weight:600;color:#21465c;gap:8px}#selectionForm .is-open>.ic-heading{background:#f1f8fb;border-bottom:1px solid #dce8ef}#selectionForm[data-compact-inspector] .ip-pane{padding:10px;gap:11px}#selectionForm[data-compact-inspector] .ip-section{border:0;background:transparent;border-radius:0;padding:0;margin:0}#selectionForm[data-compact-inspector] .ip-section+.ip-section{border-top:1px solid #ecf1f5;padding-top:10px}#selectionForm[data-compact-inspector] .ip-section h3{font-size:11px;color:#517083;margin:0 0 8px}
  #selectionForm[data-compact-inspector] .field{grid-template-columns:78px minmax(0,1fr);gap:7px;align-items:center}#selectionForm[data-compact-inspector] .field>label{font-size:11px;line-height:1.3;color:#567287}#selectionForm[data-compact-inspector] label.field{font-size:11px;line-height:1.3;color:#567287}#selectionForm[data-compact-inspector] .field input,#selectionForm[data-compact-inspector] .field select{height:31px;min-height:31px;padding:5px 7px;font-size:12px;border-radius:5px;border:1px solid #cbdce6}#selectionForm[data-compact-inspector] .field textarea{height:54px;min-height:44px;padding:6px 7px;font-size:12px;line-height:1.4}#selectionForm[data-compact-inspector] .field>div,#selectionForm[data-compact-inspector] .field>button,#selectionForm[data-compact-inspector] .field>small{grid-column:1/-1}#selectionForm[data-compact-inspector] .ip-grid{gap:8px}#selectionForm[data-compact-inspector] .ip-grid .field:not(.ic-wide){grid-template-columns:43px minmax(0,1fr);gap:4px}#selectionForm[data-compact-inspector] #nominalValue{background:#f4fafc;font-weight:600;font-size:14px}#selectionForm[data-compact-inspector] .ip-section-head{margin-bottom:8px}#selectionForm[data-compact-inspector] .ip-section-head h3{margin:0}
  #selectionForm .ic-advanced{margin-top:10px;border-top:1px dashed #d6e4ec;padding-top:7px}#selectionForm .ic-advanced>summary{font-size:11px;color:#21778d;cursor:pointer;padding:4px 0}#selectionForm .ic-advanced>.field{margin-top:8px}#selectionForm .ic-advanced .ic-check{display:flex!important;align-items:flex-start;gap:7px;font-size:11px;line-height:1.4;margin:10px 0}#selectionForm .ic-check input{width:14px!important;height:14px!important;min-height:14px!important;flex:0 0 14px;margin:0}#selectionForm #ipApplyGeneral{width:100%;display:block;margin-top:7px;min-height:30px;font-size:11px}#selectionForm #ipLimitMessage{font-size:10px!important;line-height:1.4;margin:6px 0 0}
  #selectionForm[data-compact-inspector] .ci-help{font-size:10px;line-height:1.4;margin:6px 0 0}#selectionForm[data-compact-inspector] .ci-inline-actions .btn{font-size:11px;min-height:28px;padding:5px 7px}#selectionForm[data-compact-inspector] .ci-inline-actions{margin-top:7px}#selectionForm[data-compact-inspector] .wf-source-viewport{height:210px}#selectionForm[data-compact-inspector] .ci-role-card{padding:7px}#selectionForm[data-compact-inspector] .ip-footer{padding:7px 9px;background:white;gap:6px;border-top:1px solid #dce6ed}#selectionForm[data-compact-inspector] .ip-footer .btn{min-height:29px;font-size:11px;padding:5px 7px}#selectionForm[data-compact-inspector] #acuiDetailsOpen{background:#eef7fa;color:#246a80;border:1px solid #cde1eb;box-shadow:none}
  `;document.head.append(css);
 }
 root.ASMachInspectorCompact={init};
})(window);
