/* Shared report model for the offline Excel writer and paginated PDF renderer. */
(function(root){
 'use strict';
 let app;
 const titles={control:'Kontrol planı',intermediate:'Ara kontrol formu',characteristics:'Karakteristik listesi'};
 const modeLabels={manual:'Manuel',table:'Tablo',all:'%100',none:'Belirtilmedi'};
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const clone=x=>JSON.parse(JSON.stringify(x));
 const RP=()=>root.ASMachRolePlans;
 const owner=role=>role==='legacy'?'Ortak plan (sorumlu atanmamış)':RP().roles[role]||'Plan atanmadı';
 const quantity=v=>v==null||String(v).trim()===''?'':Number(v);
 function quantityError(o){const order=quantity(o.orderQuantity),lot=quantity(o.lotSize);if([order,lot].some(v=>v!==''&&(!Number.isSafeInteger(v)||v<1))||order!==''&&lot!==''&&lot>order)return 'Girilen sipariş ve parti adetleri pozitif tam sayı olmalı; parti sipariş adedini aşmamalı.';return '';}
 function entries(r,o){const plans=RP().normalize(r);if(plans)return Object.keys(plans).filter(role=>(o.role==='both'||!o.role||o.role===role)&&plans[role].enabled).map(role=>({role,p:plans[role]}));
   if(o.role&&o.role!=='both')return [];
   return [{role:'legacy',p:{...RP().blank(),sampleMode:r.inspectionFrequency==='EACH_PART'?'all':'none',...(r.commonSampling||{}),enabled:true,inspectionMethod:r.inspectionMethod||'',inspectionFrequency:r.inspectionFrequency||'',frequencyInterval:r.frequencyInterval||'',frequencyNote:r.frequencyNote||'',operation:r.operation||'',reaction:r.reaction||''}}];
 }
 function entryError(role,p,lot){let error;if(role==='legacy'){if(!p.inspectionMethod)return 'Ortak plan: kontrol yöntemi seçin.';if(!p.inspectionFrequency)return 'Ortak plan: kontrol sıklığı seçin.';error=root.ASMachInspectionPlan.validate(p);if(app?.getMethods&&!app.getMethods().some(m=>m.value===p.inspectionMethod))return 'Ortak plan: kontrol yöntemi artık tanımlı değil.';}else error=RP().validate({rolePlans:{[role]:p}},lot===''?undefined:lot);
   if(error)return error;if(role==='legacy'&&p.sampleMode!=='none'){error=RP().samplingError(p,role,lot===''?undefined:lot);if(error)return error;}if(['table','all'].includes(p.sampleMode)&&lot==='')return 'Numune hesabı için rapor ekranında bu partinin adedini girin.';return '';
 }
 function sampleFor(role,p,lot){if(role==='legacy'&&p.sampleMode==='none')return{code:'',count:''};if(lot===''&&p.sampleMode==='manual'&&p.sampleCount!=='')return{code:'',count:Number(p.sampleCount)};return RP().sample(p,lot,role);}
 const numeric=x=>x!==''&&x!=null&&Number.isFinite(Number(x))?Number(x):x??'';
 const value=x=>x&&typeof x==='object'&&'formula'in x?x.value:x??'';
 function sheet(name,n){return{name,n,landscape:true,colWidth:12,cells:[],images:[],heights:{},breaks:[],lastRow:0};}
 function put(s,r,c,v,cs=1,style=0){s.cells.push({r,c,cs,rs:1,value:v,style});s.lastRow=Math.max(s.lastRow,r+1);return s.cells.at(-1);}
 function selections(state,o){if(root.ASMachProduction)return root.ASMachProduction.reportRecords(state,o);const ids=new Set(o.ids||[]);return [...state.annotations].filter(r=>(!o.selectedOnly||ids.has(r.id))&&(!o.type||r.type===o.type)&&(!o.operation||r.operation===o.operation||Object.values(r.rolePlans||{}).some(p=>p.operation===o.operation))).sort(root.ASMachNumberOrder.records);}
 function readiness(state,o={}){const issues=[],blockers=[];for(const r of selections(state,o)){if(r.productionControl){if(!root.ASMachProduction.data(state).controls.find(c=>c.id===r.id)?.acceptance)issues.push({r,message:'Kabul kriteri eksik.'});continue;}for(const message of root.ASMachRequirements?.consistencyErrors?.(r)||[])blockers.push({r,message});for(const i of root.ASMachInspectionPlan.checkInformation(r,{pageCount:state.pageCount,methods:app?.getMethods?.()})){if(i.code==='inconsistent'){if(!blockers.some(b=>b.r===r&&b.message===i.label))blockers.push({r,message:i.label});}else if(!['method','frequency'].includes(i.code))issues.push({r,message:i.label});}for(const message of root.ASMachRequirements?.activeWarnings?.(r)||r.parseWarnings||[])if(!issues.some(i=>i.r===r&&i.message===message))issues.push({r,message});}return{issues,blockers};}
 function build(state,o={}){
   o={...o,includeSnapshots:false,logo:root.ASMachReportBrand?.logo()||o.logo||'',orientation:'landscape'};
   const B=root.ASMachReportBrand,both=(a,b)=>a+'\n'+b;
   const records=selections(state,o),lot=quantity(o.lotSize),order=quantity(o.orderQuantity),mode=o.mode||'control';
   if(!records.length)throw new Error('Rapora uygun karakteristik bulunamadı.');
   const qError=quantityError(o);if(qError)throw new Error(qError);
   const review=readiness(state,o);if(review.blockers.length)throw new Error(review.blockers.map(i=>`#${i.r.number}: ${i.message}`).join('\n'));o.draft=review.issues.length>0;
   const plan=sheet('Plan',9),table=sheet('NumuneTablosu',11),main=sheet(({control:'Control Plan',intermediate:'In-process Inspection',characteristics:'Characteristics'})[mode],12),rows=[];
   put(plan,0,0,'Sipariş ve numune planı',9,1);put(plan,1,0,both('Order qty.','Sipariş adedi'));put(plan,1,1,order);put(plan,2,0,both('Lot qty.','Parti adedi'));put(plan,2,1,lot);
   put(plan,1,2,'Sipariş / İş emri',2);put(plan,1,4,o.workOrder||'',3);put(plan,4,0,both('Source: user-provided sampling table. Acceptance / rejection numbers are not defined.','Kaynak: kullanıcının numunelendirme tablosu. Kabul / red sayıları tanımlı değildir.'),9);plan.heights[4]=35;
   put(plan,5,0,both('Sample size is the total quantity inspected; frequency defines when inspection is repeated.','Numune adedi kontrol edilecek toplam parçadır; sıklık kontrolün tekrar zamanıdır.'),9);plan.heights[5]=42;plan.heights[1]=40;plan.heights[2]=40;plan.heights[3]=8;
   ['Balon','Sorumlu','Numune modu','Seviye','Manuel adet','Kod harfi','Numune adedi','Yöntem','Sıklık'].forEach((v,c)=>put(plan,7,c,v,1,2));plan.heights[7]=32;
   ['Parti alt sınırı',...RP().levels,'','Kod','Numune'].forEach((v,c)=>put(table,0,c,v,1,2));
   RP().starts.forEach((start,i)=>{put(table,i+1,0,start);RP().codes[i].forEach((v,c)=>put(table,i+1,c+1,v));});
   Object.entries(RP().sizes).forEach(([code,n],i)=>{put(table,i+1,9,code);put(table,i+1,10,n);});
   for(const r of records){const selected=entries(r,o);
     if(!selected.length){if(mode==='characteristics'){rows.push({r,role:'',p:RP().blank(),count:'',code:'',ref:null});continue;}throw new Error(`#${r.number}: Seçilen sorumlu için etkin plan yok. Ortak planlar için tüm sorumluları seçin veya sorumlu atayın.`);}
     for(const {role,p} of selected){const error=entryError(role,p,lot);if(error){if(mode==='characteristics'&&role==='legacy'){rows.push({r,role:'',p:RP().blank(),count:'',code:'',ref:null});continue;}throw new Error(`#${r.number} ${error}`);}
       const s=sampleFor(role,p,lot),i=plan.lastRow,rr=i+1;
       [r.number,owner(role),p.sampleMode,p.sampleLevel,p.sampleCount===''?'':Number(p.sampleCount)].forEach((v,c)=>put(plan,i,c,v));
       const validLot='AND(ISNUMBER($B$3),$B$3>=1,MOD($B$3,1)=0,OR($B$2="",$B$3<=$B$2))';
       put(plan,i,5,{formula:`IF(C${rr}="table",IF(AND(${validLot},$B$3>=2),VLOOKUP($B$3,NumuneTablosu!$A$2:$H$16,MATCH(D${rr},NumuneTablosu!$B$1:$H$1,0)+1,TRUE),"CHECK LOT / ADET"),"")`,value:s.code});
       const quantityCell=put(plan,i,6,{formula:`IF(${validLot},IF(C${rr}="all",$B$3,IF(C${rr}="manual",IF(AND(ISNUMBER(E${rr}),E${rr}>=1,E${rr}<=$B$3,MOD(E${rr},1)=0),E${rr},"CHECK SAMPLE / NUMUNE"),IF(C${rr}="table",IF($B$3>=2,MIN($B$3,VLOOKUP(F${rr},NumuneTablosu!$J$2:$K$17,2,FALSE)),"CHECK LOT / ADET"),"CHECK MODE / MOD"))),"CHECK LOT / ADET")`,value:s.count});quantityCell.value.formula=`IF(AND(C${rr}="manual",$B$3=""),IF(AND(ISNUMBER(E${rr}),E${rr}>=1,MOD(E${rr},1)=0),E${rr},"CHECK SAMPLE / NUMUNE"),${quantityCell.value.formula})`;if(role==='operator'||role==='legacy')quantityCell.value.formula=`IF(OR(C${rr}="none",AND(C${rr}="manual",E${rr}="")),"",${quantityCell.value.formula})`;
       put(plan,i,7,B?.text(app?.methodLabel?.(p.inspectionMethod)||p.inspectionMethod)||p.inspectionMethod);put(plan,i,8,(B?.frequency(p)||root.ASMachInspectionPlan.label(p))+(p.frequencyNote?' · '+p.frequencyNote:''));plan.heights[i]=38;
       rows.push({r,role,p,count:s.count,code:s.code,ref:rr});
     }
   }
   if(!rows.length)throw new Error('Seçilen kapsamda etkin kalite / operatör kontrolü yok.');
   main.widths=mode==='control'?[7,10,25,12,14,18,13,8,8,8,17,21]:mode==='characteristics'?[6,10,10,24,10,10,10,10,25,10,12,17]:[8,12,25,22,15,12,12,12,12,12,16,22];put(main,0,0,titles[mode],12,1);main.heights[0]=28;
   put(main,1,0,`Part / Drawing / Revision\nParça / Çizim / Revizyon: ${state.metadata.partNo||'—'} ${state.metadata.partName||''} | ${state.metadata.drawingNo||state.fileName||'—'} | ${state.metadata.drawingRevision||'—'}`,12);main.heights[1]=42;
   const suffix=` | Work order / İş emri: ${o.workOrder||'—'} | Date / Tarih: ${o.date||'—'} | Shift / Vardiya: ${o.shift||'—'}`;
   put(main,2,0,{formula:`"Order / Sipariş: "&IF(Plan!$B$2="","",Plan!$B$2)&" | Lot / Parti: "&IF(Plan!$B$3="","",Plan!$B$3)&"${suffix.replace(/"/g,'""')}"`,value:`Order / Sipariş: ${order} | Lot / Parti: ${lot}${suffix}`},12);main.heights[2]=28;
   put(main,3,0,`Prepared by / Reviewed by / Record status\nHazırlayan / Kontrol eden / Kayıt durumu: ${o.preparedBy||'—'} / ${o.checkedBy||'—'} / ${o.draft?'DRAFT / TASLAK — Eksik veya doğrulanacak bilgi var':o.withResults?'Recorded results / Kayıtlı sonuçlar':'Blank inspection record / Boş kontrol kaydı'}`,12);main.heights[3]=42;
   put(main,4,0,`Document ID / Revision / Serial or Lot / Equipment ID\nDoküman no / Revizyon / Seri veya parti / Cihaz no: ${o.documentNo||'—'} / ${o.reportRevision||'—'} / ${o.lotSerial||'—'} / ${o.equipmentId||'—'}`,12);main.heights[4]=42;
   let headers=mode==='control'?['Balon','Tür','Gereklilik / limit','Sorumlu','Yöntem','Sıklık','Numune modu','Seviye','Kod','Adet','Operasyon','Uygunsuzlukta işlem']:mode==='characteristics'?['Balon','Sayfa / Zon','Tür','Gereklilik','Nominal','Alt tol.','Üst tol.','Datum','Sorumlu / yöntem / sıklık','Numune','Kayıtlı sonuç','Görsel']:['Balon','Sorumlu','Gereklilik / limit','Yöntem / sıklık','Numune aralığı','1','2','3','4','5','Tarih / Saat','Kontrol eden / uygunluk'];
   headers.forEach((v,c)=>put(main,5,c,v,1,2));main.heights[5]=38;main.freeze=6;
   const formula=(ref,col,cached)=>ref?{formula:`Plan!${col}${ref}`,value:cached}:'';
   function addImage(r,row,col){if(r.type!=='GD&T')return;const data=root.ASMachGdtReport?.image(r);if(!/^data:image\/png;base64,/.test(data||''))return;const bytes=Uint8Array.from(atob(data.split(',')[1]),x=>x.charCodeAt(0));if(bytes.length<24)return;const v=new DataView(bytes.buffer),w=v.getUint32(16),h=v.getUint32(20);if(!w||!h)return;const k=Math.min(((main.widths?.[col]||12)*7-8)/w,(r.type==='GD&T'?16:40)/h);main.images.push({r:row,c:col,bytes,dataUrl:data,width:w*k,height:h*k,name:`GD&T ${r.number}`});}
   let resultCount=0;
   for(const {r,role,p,count,code,ref} of rows){const method=(B?.text(app?.methodLabel?.(p.inspectionMethod)||p.inspectionMethod)||p.inspectionMethod)+(r.toolingReference?'\nID: '+r.toolingReference:''),freq=(B?.frequency(p)||root.ASMachInspectionPlan.label(p))+(mode==='intermediate'&&p.operation?'\nOperation / Operasyon: '+p.operation:''),limits=[r.lowerLimit,r.upperLimit].some(v=>v!=null&&v!=='')?`\nLimit: ${r.lowerLimit||'—'} / ${r.upperLimit||'—'}`:'',name=owner(role);
     if(mode==='intermediate'){
       if(count===''){const row=main.lastRow;[r.number,name,r.type==='GD&T'&&root.ASMachGdtReport?.image(r)?'':(r.requirement||'')+limits,method+'\n'+freq,'Not specified\nBelirtilmedi','','','','','','',''].forEach((v,c)=>put(main,row,c,v));main.heights[row]=68;if(r.type==='GD&T')addImage(r,row,2);continue;}
       const from=Number(o.sampleFrom||1),to=Math.min(count,Number(o.sampleTo||count));if(!Number.isSafeInteger(from)||!Number.isSafeInteger(to)||from<1||to<from)throw new Error('Numune aralığı geçersiz veya plandaki numune adedini aşıyor.');
       resultCount+=to-from+1;if(resultCount>10000)throw new Error('Form çok büyük. Numune başlangıç / bitiş aralığını daraltın.');
       for(let start=from;start<=to;start+=5){const row=main.lastRow,end=Math.min(start+4,to);[r.number,name,r.type==='GD&T'&&root.ASMachGdtReport?.image(r)?'':(r.requirement||'')+limits+(r.unit?'\nUnit / Birim: '+r.unit:''),method+'\n'+freq,`${start}–${end} / ${count}`,...Array.from({length:5},(_,j)=>start+j<=end?`N${start+j}: ______`:'—'),'',''].forEach((v,c)=>put(main,row,c,v));main.heights[row]=68;if(r.type==='GD&T')addImage(r,row,2);}
     }else{
       const row=main.lastRow,values=mode==='control'?[r.number,r.type,r.type==='GD&T'&&root.ASMachGdtReport?.image(r)?'':r.requirement+limits+(r.unit?'\nUnit / Birim: '+r.unit:''),name,method,freq+(p.frequencyNote?'\n'+p.frequencyNote:''),modeLabels[p.sampleMode]||'',p.sampleMode==='table'?p.sampleLevel:'',formula(ref,'F',code),formula(ref,'G',count),p.operation,p.reaction]:[r.number,`${r.page} / ${r.zone||''}`,r.type,(r.requirement||'')+(r.unit?'\nUnit / Birim: '+r.unit:''),numeric(r.nominalValue),numeric(r.lowerTolerance),numeric(r.upperTolerance),r.datumRefs,`${name}\n${method}\n${freq}`,formula(ref,'G',count),o.withResults&&role==='legacy'?numeric(r.result):'',''];
       values.forEach((v,c)=>put(main,row,c,v));main.heights[row]=64;if(mode==='characteristics')addImage(r,row,11);else if(r.type==='GD&T')addImage(r,row,2);
     }
   }
   main.printTitles='$1:$6';plan.freeze=8;plan.widths=[16,14,16,10,12,12,13,20,24];table.widths=[18,8,8,8,8,8,8,8,4,10,12];main.colWidth=12;
   
   for(let r=5;r<main.lastRow;r++){const cells=main.cells.filter(c=>c.r===r);const lineCount=Math.max(1,...cells.map(c=>String(value(c.value)).split('\n').reduce((n,line)=>n+Math.max(1,Math.ceil(line.length/(main.widths.slice(c.c,c.c+c.cs).reduce((a,b)=>a+b,0)-1))),0)));main.heights[r]=Math.max(main.heights[r]||30,lineCount*14+12);if(main.heights[r]>400)throw new Error('Bir açıklama Excel satırına sığmayacak kadar uzun. Açıklamayı kısaltın veya karakteristik notuna taşıyın.');}
   for(const s of [main,plan,table]){s.paperSize=o.paper==='a3'?8:9;s.landscape=o.orientation!=='portrait';}
   const model={sheets:[main,plan,table],mode,options:o,validation:review.issues.map(i=>({number:i.r.number,message:i.message}))};return B?B.decorate(model):model;
 }
 function wrap(g,text,width){const lines=[];for(const paragraph of String(text??'').split('\n')){let line='';for(const word of paragraph.split(/\s+/)){if(g.measureText(line+(line?' ':'')+word).width<=width)line+=(line?' ':'')+word;else{if(line)lines.push(line);line='';for(const ch of word){if(g.measureText(line+ch).width>width){lines.push(line);line='';}line+=ch;}}}lines.push(line);}return lines;}
 async function pdf(model){
   const o=model.options,s=model.sheets[0],large=o.paper==='a3',W=large?2380:1684,H=large?1684:1190,margin=38;
   const widths=s.widths.map(w=>(W-2*margin)*w/s.widths.reduce((a,b)=>a+b,0)),doc=new root.jspdf.jsPDF({compress:true,orientation:'landscape',unit:'pt',format:large?'a3':'a4'});
   const pics=new Map();for(const pic of s.images.filter(p=>p.r>=6)){pics.set(pic.r,{image:await app.loadImage(pic.dataUrl),col:pic.c});}
   const logo=await app.loadImage(root.ASMachReportBrand.logo()),rows=new Map();
   for(const c of s.cells){if(!rows.has(c.r))rows.set(c.r,[]);rows.get(c.r).push(c);}
   let canvas,g,y,pageCount=0;
   const cells=r=>(rows.get(r)||[]).sort((a,b)=>a.c-b.c);
   const text=v=>String(value(v));
   function measure(r,header=false){g.font=(header?'bold ':'')+'18px Arial';const lines=cells(r).map(c=>wrap(g,text(c.value),widths.slice(c.c,c.c+c.cs).reduce((a,b)=>a+b,0)-16));return{lines,height:Math.max(header?74:66,...lines.map(l=>l.length*22+20))};}
   function row(r,header=false){const m=measure(r,header);if(m.height>H-y-100&&!header){finish();start();}if(y+m.height>H-100)throw Error('Bir rapor satırı yazdırılabilir alana sığmıyor. Açıklamayı kısaltın veya A3 seçin.');
     let x=margin;cells(r).forEach((c,i)=>{const w=widths.slice(c.c,c.c+c.cs).reduce((a,b)=>a+b,0);g.fillStyle=header?'#e8edf1':r%2?'#f7f9fa':'white';g.fillRect(x,y,w,m.height);g.strokeStyle='#aebbc3';g.lineWidth=.8;g.strokeRect(x,y,w,m.height);g.fillStyle='#172e3c';g.font=(header?'bold ':'')+'18px Arial';m.lines[i].forEach((line,j)=>g.fillText(line,x+8,y+25+j*22));
       if(pics.get(r)?.col===c.c){const im=pics.get(r).image,k=Math.min((w-16)/im.width,32/im.height);g.drawImage(im,x+8,y+(m.height-im.height*k)/2,im.width*k,im.height*k);}x+=w;});y+=m.height;
   }
function start(){canvas=document.createElement('canvas');canvas.width=W;canvas.height=H;g=canvas.getContext('2d');g.fillStyle='white';g.fillRect(0,0,W,H);const title=root.ASMachReportBrand.text(model.title||titles[model.mode]).split('\n');g.fillStyle='#172e3c';g.font='bold 30px Arial';g.fillText(title[0],margin,47);g.font='19px Arial';g.fillText(title[1]||'',margin,75);const k=Math.min(230/logo.width,76/logo.height);g.drawImage(logo,W-margin-logo.width*k,12,logo.width*k,logo.height*k);g.strokeStyle='#d8ad29';g.lineWidth=3;g.beginPath();g.moveTo(margin,92);g.lineTo(W-margin,92);g.stroke();y=120;g.font='17px Arial';
     for(let r=1;r<=4;r++){for(const line of wrap(g,value(cells(r)[0]?.value),W-2*margin)){g.fillText(line,margin,y);y+=21;}y+=5;}y+=10;row(5,true);
   }
function finish(){g.font='15px Arial';g.fillStyle='#415361';g.fillText('Prepared / Hazırlayan: '+(o.preparedBy||'________________')+'    Reviewed / Kontrol: '+(o.checkedBy||'________________')+'    Approval / Onay: ________________',margin,H-72);g.fillText(model.footer||'Sample size is not inspection frequency. Acceptance criteria require approval.',margin,H-43);g.fillText('Numune adedi kontrol sıklığı değildir. Kabul kriterleri ayrıca onaylanır.',margin,H-23);g.fillText('Page / Sayfa '+(++pageCount),W-margin-160,H-23);if(pageCount>1)doc.addPage();doc.addImage(canvas.toDataURL('image/png'),'PNG',0,0,doc.internal.pageSize.getWidth(),doc.internal.pageSize.getHeight(),undefined,'FAST');canvas.width=1;canvas.height=1;}
   start();for(let r=6;r<s.lastRow;r++){row(r);if(r%20===0)await new Promise(resolve=>setTimeout(resolve,0));}finish();return doc.output('blob');
 }
 function init(bridge){app=bridge;const button=document.createElement('button');button.className='btn';button.id='inspectionReportsButton';button.textContent='Kontrol planı / Form raporları';button.onclick=open;app.elements.csvButton.after(button);}
 function open(){
   if(!app.state.annotations.length&&!root.ASMachProduction?.data(app.state).controls.length)return app.toast('Önce karakteristik veya üretim kontrolü ekleyin.',true);
   const existing=document.querySelector('.inspection-report-dialog[open]');
   if(existing&&existing._source===app.state.fileData&&existing._annotations===app.state.annotations){root.ASMachWorkspaceTabs?.activate('inspection');root.ASMachRibbon?.select('reports');existing.dispatchEvent(new Event('focusin'));return;}
   document.querySelectorAll('.inspection-report-dialog').forEach(d=>{if(d.open)d.close();d.remove();});
   const original=app.state.annotations,settings=app.state.metadata.inspectionReport||{},modal=document.createElement('dialog');modal.className='asmach-modal inspection-report-dialog';
   modal._source=app.state.fileData;modal._annotations=original;root.ASMachRibbon?.select('reports');
   const input=(key,label,type='text')=>`<label>${label}<input data-option="${key}" type="${type}" ${type==='number'?'min="1" step="1"':''} value="${esc(settings[key]??'')}"></label>`;
   modal.innerHTML=`<header class="acui-head"><div><h2>Rapor merkezi</h2><p>İngilizce başlıklar, altında Türkçe · Şenyüz Makine</p></div><button class="btn" data-close>Kapat</button></header><div class="acui-content">
   <section class="ir-section"><h3>1. Rapor ve kapsam</h3><div class="ir-grid"><label>Rapor türü<select data-option="mode">${Object.entries(titles).map(([v,l])=>`<option value="${v}">${l}</option>`).join('')}</select></label><label>Sorumlu<select data-option="role"><option value="both">Tümü — operatör / kalite / ortak plan</option><option value="operator">Operatör</option><option value="quality">Kalite</option></select></label><label>Yazdırma düzeni<select data-option="paper"><option value="a4">A4 · Yatay</option><option value="a3">A3 · Yatay</option></select></label><label>Tür filtresi<select data-option="type"><option value="">Tüm türler</option>${[...new Set(original.map(r=>r.type))].map(t=>`<option>${esc(t)}</option>`).join('')}</select></label>${input('operation','Operasyon filtresi')}<label class="ir-check"><input type="checkbox" data-option="selectedOnly"> Yalnız seçili balonlar</label></div><label class="ir-check" data-results><input type="checkbox" data-option="withResults"> Kayıtlı karakteristik sonuçlarını dahil et</label></section>
   <section class="ir-section"><h3>2. Sipariş ve izlenebilirlik</h3><div class="ir-grid">${input('orderQuantity','Sipariş adedi (isteğe bağlı)','number')}${input('lotSize','Parti adedi (numune hesabı için)','number')}${input('workOrder','Sipariş / İş emri')}${input('lotSerial','Parti / Seri numarası')}${input('documentNo','Rapor / Doküman numarası')}${input('reportRevision','Rapor revizyonu')}${input('date','Kontrol tarihi','date')}${input('shift','Vardiya')}${input('equipmentId','Cihaz / kalibrasyon referansı')}${input('preparedBy','Hazırlayan')}${input('checkedBy','Kontrol eden')}</div></section>
   <section class="ir-section" data-range><h3>3. Numune aralığı</h3><p>Boş bırakırsanız tüm planlı numuneler hazırlanır. Her satırda 5 ölçüm alanı vardır.</p><div class="ir-grid">${input('sampleFrom','İlk numune','number')}${input('sampleTo','Son numune','number')}</div></section>
   <section class="ir-section"><h3>Kontrol planı hazırlığı</h3><div data-preflight></div><div class="ir-actions"><button class="btn" data-plan-selected>Seçili balonların planı</button><button class="btn" data-plan-all>Kapsamdaki tüm planlar</button></div>
   <details data-migration><summary>Eski yöntem ve sıklıkları aktar</summary><p>Her balonun mevcut yöntemi ve sıklığı korunur. Sadece henüz sorumlu planı bulunmayan kayıtlar aktarılır.</p><div class="ir-grid"><label>Hangi sorumluya?<select data-migrate-role><option value="operator">Operatör</option><option value="quality">Kalite</option><option value="both">Her ikisi</option></select></label><label>Numune planı<select data-migrate-sample><option value="table">Tabloya göre · G2</option><option value="all">%100 kontrol</option></select></label><button class="btn" data-migrate>Eski kayıtları aktar</button></div></details></section>
   <div class="ir-brand"><img src="${root.ASMachReportBrand.logo()}" alt="Şenyüz Makine"><p>Snapshotlar rapora alınmaz. Yalnız oluşturulan GD&T çerçeveleri eklenir.<br>Numune tablosu kabul / red sayısı belirlemez. Müşteri şartları ve kuruluşun doküman onayı ayrıca uygulanır.</p></div>
   <p data-status role="status" aria-live="polite"></p></div><footer class="acui-foot"><button class="btn" data-settings>Ayarları kaydet</button><span class="acui-foot-note" data-summary></span><button class="btn" data-pdf>PDF önizle / kaydet</button><button class="btn primary" data-xlsx>Excel oluştur</button></footer>`;
   if(!document.getElementById('ir-style')){const style=document.createElement('style');style.id='ir-style';style.textContent='.inspection-report-dialog{width:min(1120px,96vw);padding:0;border:1px solid #bacdd7;border-radius:14px;color:#173441}.inspection-report-dialog .acui-head{display:flex;justify-content:space-between;gap:14px}.inspection-report-dialog .acui-head .btn{background:white;color:#163747;flex:none}.inspection-report-dialog h2{margin:0;font-size:21px}.inspection-report-dialog p{font-size:12px;line-height:1.5}.ir-section{padding:12px;border:1px solid #d6e0e7;border-radius:9px;margin-bottom:12px}.ir-section h3{margin:0 0 10px;font-size:14px}.ir-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}.ir-grid label{display:grid;gap:5px;font-size:12px;min-width:0}.ir-grid input,.ir-grid select{width:100%;min-width:0;padding:8px;border:1px solid #c8d6de;border-radius:6px;background:white}.ir-check{display:flex!important;align-items:center;gap:8px!important;font-size:12px;margin-top:10px}.ir-check input{width:auto}.ir-actions{display:flex;gap:8px;flex-wrap:wrap;margin:10px 0}.ir-brand{display:flex;align-items:center;gap:20px;background:#f5f7f9;padding:10px;border-radius:8px}.ir-brand img{width:150px;max-height:70px;object-fit:contain}.ir-issue{padding:6px 0;color:#8a3e16}.ir-issue button{margin-left:8px}.inspection-report-dialog [hidden]{display:none!important}@media(max-width:700px){.ir-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.ir-brand{flex-wrap:wrap}}@media(max-width:430px){.ir-grid{grid-template-columns:1fr}}';document.head.append(style);}
   document.body.append(modal);const $=s=>modal.querySelector(s);
   if(root.ASMachProduction){const select=document.createElement('select');select.dataset.option='operation';const ops=root.ASMachProduction.data(app.state).operations,legacy=[...new Set(original.flatMap(r=>[r.operation,...Object.values(r.rolePlans||{}).map(p=>p.operation)]).filter(Boolean))];select.innerHTML='<option value="">Tüm operasyonlar</option>'+ops.map(r=>`<option value="${esc(r.id)}">${esc(root.ASMachProduction.label(r))}</option>`).join('')+legacy.map(s=>`<option value="${esc(s)}">${esc(s)} (eski kayıt)</option>`).join('');$('[data-option="operation"]').replaceWith(select);const b=document.createElement('button');b.className='btn';b.textContent='Üretim / operasyon planlarını düzenle';b.onclick=()=>{modal.close();root.ASMachProduction.open('controls');};$('[data-plan-all]').after(b);}
   modal.querySelectorAll('[data-option]').forEach(n=>{const v=settings[n.dataset.option];if(v!==undefined){if(n.type==='checkbox')n.checked=Boolean(v);else n.value=v;}});
   const ids=()=>[...new Set([...(root.ASMachCharacteristicUI?.selectionIds?.()||[]),...(app.state.selectedId?[app.state.selectedId]:[])])];
   const options=()=>{const o={ids:ids(),logo:root.ASMachReportBrand.logo(),includeSnapshots:false,orientation:'landscape'};modal.querySelectorAll('[data-option]').forEach(n=>o[n.dataset.option]=n.type==='checkbox'?n.checked:n.value);if(o.mode!=='characteristics')o.withResults=false;return o;};
   const current=()=>{if(app.state.annotations!==original)throw new Error('Belge değişti. Rapor ekranını yeniden açın.');};
   const save=()=>{current();app.checkpoint();const o=options();delete o.logo;delete o.ids;app.state.metadata.inspectionReport=o;app.recordChange('Rapor ve numune ayarları güncellendi');};
   function refresh(){const o=options(),records=selections(app.state,o),review=readiness(app.state,o),issues=[...review.blockers];const q=quantityError(o);if(q)issues.push({r:null,message:q});for(const r of records){const selected=entries(r,o);if(!selected.length&&o.mode!=='characteristics')issues.push({r,message:'Seçilen sorumlu için etkin plan yok. Tüm sorumluları seçin veya plan atayın.'});else for(const {role,p} of selected){const e=entryError(role,p,quantity(o.lotSize));if(e&&!(role==='legacy'&&o.mode==='characteristics'))issues.push({r,message:e});}}
     $('[data-preflight]').innerHTML=issues.length?issues.slice(0,12).map(({r,message})=>`<div class="ir-issue">${r?'#'+esc(r.number)+':':''} ${esc(message)} ${r?`<button class="btn" data-fix="${esc(r.id)}">${review.blockers.some(i=>i.r===r)?'Ölçüyü düzelt':'Planı düzelt'}</button>`:''}</div>`).join('')+(issues.length>12?`<p>ve ${issues.length-12} eksik plan daha</p>`:''):'<p>Kontrol planı alanlarında eksik bulunmadı.</p>';
     const reviewRecords=[...new Set(review.issues.map(i=>i.r))];
     if(review.issues.length)$('[data-preflight]').insertAdjacentHTML('beforeend','<p><b>TASLAK RAPOR:</b> '+reviewRecords.length+' karakteristikte ölçü / doğrulama uyarısı var. Bunlar taslak çıktıyı engellemez; çelişkili sayısal değerler ise düzeltilmelidir.</p>'+reviewRecords.map(r=>`<div class="ir-issue"><div><b>#${esc(r.number)} · ${esc(r.type)}</b><ul>${review.issues.filter(i=>i.r===r).map(i=>`<li>${esc(i.message)}</li>`).join('')}</ul></div><button class="btn" data-characteristic-fix="${esc(r.id)}">Düzelt / doğrula</button></div>`).join(''));
     $('[data-preflight]').querySelectorAll('[data-characteristic-fix]').forEach(b=>b.onclick=()=>fixCharacteristic(b.dataset.characteristicFix));
     $('[data-summary]').textContent=`${records.length} karakteristik · ${issues.length} plan uyarısı`; $('[data-range]').hidden=o.mode!=='intermediate';$('[data-results]').hidden=o.mode!=='characteristics';$('[data-migration]').hidden=!records.some(r=>!r.rolePlans);if(records.some(r=>!r.rolePlans)&&(!o.role||o.role==='both'))$('[data-preflight]').insertAdjacentHTML('beforeend','<p>Eski yöntem / sıklık bilgileri ortak plan olarak aktarılır. Kalite veya operatör sorumluluğu atanmış sayılmaz; aralık değeri numune adedine çevrilmez.</p>');
     $('[data-preflight]').querySelectorAll('[data-fix]').forEach(b=>b.onclick=()=>review.blockers.some(i=>i.r.id===b.dataset.fix)?fixCharacteristic(b.dataset.fix):edit([records.find(r=>r.id===b.dataset.fix)]));
   }
   function fixCharacteristic(id){if(root.ASMachProduction?.data(app.state).controls.some(c=>c.id===id)){modal.close();root.ASMachProduction.open('controls',id);return;}root.ASMachCharacteristicUI.openEditor(id);const editor=document.getElementById('acuiEditor');editor?.addEventListener('close',()=>{if(modal.open)refresh();},{once:true});const r=app.state.annotations.find(r=>r.id===id);if(r?.type==='Açı')document.getElementById('acuiGeneralApply')?.scrollIntoView({block:'center'});else if(r?.parseWarnings?.length)document.getElementById('acuiWarningReview')?.scrollIntoView({block:'center'});else document.getElementById('acuiNumericSection')?.scrollIntoView({block:'center'});}
   function edit(targets){targets=targets.filter(Boolean);if(targets.some(r=>r.productionControl||r.operationId||r.operationLinks?.length)){const r=targets[0];modal.close();root.ASMachProduction.open(r.productionControl?'controls':'links',r.id);return;}targets=targets.map(r=>original.find(c=>c.id===r.id)).filter(Boolean);if(targets.length>1){root.ASMachCharacteristicEditing.open(app,targets.map(r=>r.id),{plansOnly:true,onApplied:refresh});return;}if(!targets.length){$('[data-status]').textContent='Önce balon seçin.';return;}RP().open(app,targets[0],plans=>{current();if(!plans)return;app.checkpoint();targets.forEach(r=>{r.rolePlans=clone(plans);app.recordChange('Kontrol planı güncellendi',r);});app.renderAll();refresh();});}
   $('[data-plan-selected]').onclick=()=>edit(original.filter(r=>ids().includes(r.id)));$('[data-plan-all]').onclick=()=>edit(selections(app.state,options()));
   $('[data-migrate]').onclick=()=>{try{current();const targets=selections(app.state,options()).filter(r=>!r.rolePlans&&!r.productionControl&&!r.operationId).map(r=>original.find(a=>a.id===r.id)).filter(Boolean),role=$('[data-migrate-role]').value,sample=$('[data-migrate-sample]').value;if(!targets.length)return;app.checkpoint();for(const r of targets){const p={...RP().blank(),enabled:true,inspectionMethod:r.inspectionMethod||'',inspectionFrequency:r.inspectionFrequency||'',frequencyInterval:r.frequencyInterval||'',frequencyNote:r.frequencyNote||'',sampleMode:r.inspectionFrequency==='EACH_PART'?'all':sample,sampleLevel:'G2'};r.rolePlans={operator:role!=='quality'?clone(p):RP().blank(),quality:role!=='operator'?clone(p):RP().blank()};app.recordChange('Eski kontrol planı sorumluya aktarıldı',r);}app.renderAll();refresh();$('[data-status]').textContent=targets.length+' kayıt aktarıldı. Kalan uyarıları tamamlayın.';}catch(e){$('[data-status]').textContent=e.message;}};
   $('[data-close]').onclick=()=>modal.close();modal.addEventListener('close',()=>modal.remove());modal.addEventListener('keydown',e=>e.stopPropagation());
   $('[data-settings]').onclick=()=>{try{save();$('[data-status]').textContent='Ayarlar kaydedildi.';}catch(e){$('[data-status]').textContent=e.message;}};
   modal.querySelectorAll('[data-option]').forEach(n=>n.addEventListener('change',()=>{if(n.dataset.option==='orderQuantity'&&!$('[data-option="lotSize"]').value)$('[data-option="lotSize"]').value=n.value;refresh();}));
   async function output(format){const buttons=modal.querySelectorAll('[data-xlsx],[data-pdf]');buttons.forEach(b=>b.disabled=true);try{current();$('[data-status]').textContent='Rapor hazırlanıyor…';const o=options(),model=build(app.state,o),filename=app.baseName(app.state.fileName)+'_'+o.mode+'.'+format;save();if(format==='xlsx')await app.saveBlob(root.ASMachWorkflow.zipStored(root.ASMachExcelReports.files(model)),filename,'Excel kontrol raporu',{'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet':['.xlsx']});else{const blob=await pdf(model);modal.close();await root.ASMachPdfPreview.open(blob,{fileName:filename,detail:titles[o.mode],onSave:()=>app.saveBlob(blob,filename,'PDF kontrol raporu',{'application/pdf':['.pdf']})});}$('[data-status]').textContent='Rapor hazır.';}catch(e){$('[data-status]').textContent=e.message;refresh();$('[data-status]').scrollIntoView({block:'nearest'});}finally{buttons.forEach(b=>b.disabled=false);}}
   $('[data-xlsx]').onclick=()=>output('xlsx');$('[data-pdf]').onclick=()=>output('pdf');modal.addEventListener('focusin',()=>refreshIfChanged());let lastStamp='';function refreshIfChanged(){const s=JSON.stringify(app.state.annotations);if(s!==lastStamp){lastStamp=s;refresh();}}(root.ASMachWorkspaceTabs?modal.show():modal.showModal());refresh();
 }
 root.ASMachInspectionReports={init,open,build,pdf,selections,readiness};
})(window);
