(function(root){
 'use strict';let panel,busy=false;
 function create(){
  panel=document.createElement('section');panel.id='licenseCenter';panel.hidden=true;panel.setAttribute('aria-label','Lisans merkezi');
  panel.innerHTML='<header><div><small>ASMACH INSPECTION</small><h2>Lisans merkezi</h2><p>Lisansınız, cihazınız ve doğrulama işlemleri</p></div><button type="button" class="btn" data-close>Lisansı kapat ×</button></header><div class="lc-columns"><section><h3>Mevcut lisans</h3><dl></dl><button class="btn" data-copy>Cihaz kimliğini kopyala</button><button class="btn" data-check>Şimdi doğrula</button></section><section><h3>Etkinleştirme ve yenileme</h3><p>Size verilen lisans anahtarını bu bilgisayarda etkinleştirin. Süre güncellendiyse mevcut lisansı yeniden doğrulayın.</p><label>Lisans anahtarı<input data-key maxlength="36" placeholder="XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX" autocomplete="off" spellcheck="false"></label><button class="btn primary" data-activate>Anahtarı etkinleştir</button><details><summary>Lisans dosyası ile işlem</summary><input data-file type="file" accept=".asmach-license,.json"><button class="btn" data-import>Dosyayı doğrula</button></details><details><summary>Cihaz güvenliği</summary><p>TPM kimliği cihaz bağını korur. Bu işlem TPM’yi sıfırlamaz.</p><button class="btn" data-tpm>TPM kimliğini denetle</button></details></section></div><p class="lc-feedback" role="status"></p>';
  document.body.append(panel);
  panel.querySelector('[data-close]').onclick=close;
  document.addEventListener('click',e=>{if(e.target.closest('.rb-tab,.rb-tabs button,[id^="rbTab-"],[data-workspace-trigger]:not(#ribbonLicenseButton),#appSettingsButton,#ribbonAboutButton,#helpButton'))close();},true);
  document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!panel.hidden)close();});
  const css=document.createElement('style');css.textContent='#licenseCenter{position:fixed;inset:110px 0 0;z-index:2500;overflow:auto;background:#f3f7fa;padding:24px 32px;color:#23465b;font:13px Segoe UI;box-sizing:border-box}#licenseCenter[hidden]{display:none!important}#licenseCenter>header{display:flex;justify-content:space-between;align-items:center;margin-bottom:20px}#licenseCenter h2{margin:6px 0;font-size:24px}#licenseCenter h3{margin:0 0 14px}#licenseCenter p{line-height:1.6;color:#607d90}#licenseCenter small{font-size:10px;letter-spacing:.07em;color:#627e90}.lc-summary{display:grid;grid-template-columns:1fr 1fr 1.4fr;gap:14px;margin-bottom:16px}.lc-summary>div,.lc-columns>section{background:white;border:1px solid #d5e3eb;border-radius:8px;padding:20px}.lc-columns{display:grid;grid-template-columns:1.1fr 1fr;gap:16px}#licenseCenter dl{display:grid;grid-template-columns:130px 1fr;gap:0;margin:0 0 16px}#licenseCenter dt,#licenseCenter dd{padding:10px 0;border-bottom:1px solid #edf2f6;margin:0;overflow-wrap:anywhere}#licenseCenter dt{color:#668093}#licenseCenter label{display:grid;gap:7px;margin:14px 0}#licenseCenter input{padding:9px;border:1px solid #c8dbe5;border-radius:4px;min-width:0}#licenseCenter .btn{margin:4px 6px 4px 0}#licenseCenter details{border-top:1px solid #e1eaf0;padding:12px 0;margin-top:12px}#licenseCenter summary{cursor:pointer}.lc-feedback{white-space:pre-line}#licenseCenter[data-valid=true] [data-state]{color:#148268}@media(max-width:800px){#licenseCenter{padding:16px}.lc-columns,.lc-summary{grid-template-columns:1fr}}';document.head.append(css);
  css.textContent+='#licenseCenter{background:#fff;padding:20px 28px}#licenseCenter>header{margin-bottom:16px;border-bottom:1px solid #dce6ed;padding-bottom:12px}#licenseCenter .lc-summary{grid-template-columns:1fr 1fr;gap:24px;border-bottom:1px solid #dce6ed;padding-bottom:16px}#licenseCenter .lc-summary>div,#licenseCenter .lc-columns>section{border:0;border-radius:0;box-shadow:none;padding:8px 0;background:transparent}#licenseCenter .lc-summary h2{font-size:18px}#licenseCenter .lc-columns{gap:32px}#licenseCenter .lc-columns>section+section{border-left:1px solid #dce6ed;padding-left:24px}html body .toolbar #ribbonLicenseButton[aria-pressed=true]{background:#dff3f6!important;border-color:#008da1!important;box-shadow:inset 0 -2px #008da1!important;color:#006c7b!important}@media(max-width:800px){#licenseCenter .lc-summary{grid-template-columns:1fr}#licenseCenter .lc-columns>section+section{border-left:0;border-top:1px solid #dce6ed;padding:16px 0}}';
  panel.querySelector('[data-copy]').onclick=()=>run(async()=>{await navigator.clipboard.writeText(panel.dataset.device||'');return 'Cihaz kimliği kopyalandı.';});
  panel.querySelector('[data-check]').onclick=()=>run(()=>root.ASMachDesktop.invoke('license_check_online'));
  panel.querySelector('[data-activate]').onclick=()=>run(()=>root.ASMachDesktop.invoke('license_activate',{key:panel.querySelector('[data-key]').value.trim()}));
  panel.querySelector('[data-import]').onclick=()=>run(async()=>{const file=panel.querySelector('[data-file]').files[0];if(!file||file.size>24000)throw Error('En fazla 24 KB boyutunda bir lisans dosyası seçin.');await root.ASMachDesktop.invoke('license_import',{text:await file.text()});return root.ASMachDesktop.invoke('license_check_online');});
  panel.querySelector('[data-tpm]').onclick=()=>run(async()=>{const r=await root.ASMachDesktop.invoke('license_tpm_identity');return 'TPM denetimi başarılı. Cihaz kimliği: '+r.deviceId;});
 }
 function render(s){const l=s?.license,set=(q,t)=>{const node=panel.querySelector(q);if(node)node.textContent=t||'—';};panel.dataset.device=s?.deviceId||'';panel.dataset.valid=String(!!s?.valid);set('[data-state]',s?(s.valid?'Lisans geçerli':'Doğrulama gerekli'):'Masaüstü uygulaması gerekli');set('[data-reason]',s?.reason||'Lisans bilgileri yalnızca kurulu uygulamada güvenle okunabilir.');const date=v=>v?new Date(v*1000).toLocaleString('tr-TR'):'—';set('[data-online]',s?(s.onlineConfigured?'Yapılandırıldı':'Yapılandırılmadı'):'Kullanılamıyor');set('[data-message]',s?.onlineMessage);const dl=panel.querySelector('dl');dl.replaceChildren();for(const [name,value]of [['Kalan süre',l?Math.max(0,Math.ceil((l.expiresAt*1000-Date.now())/86400000))+' gün':'—'],['Lisans numarası',l?.licenseNumber],['Lisans kimliği',l?.licenseId],['Bitiş tarihi',date(l?.expiresAt)],['Bilgisayar kimliği',s?.deviceId]]){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=name;dd.textContent=value||'—';dl.append(dt,dd);}panel.querySelectorAll('button:not([data-close]),input').forEach(b=>b.disabled=!root.ASMachDesktop||busy);}
 async function run(fn){if(busy)return;busy=true;panel.querySelectorAll('button:not([data-close])').forEach(b=>b.disabled=true);const feedback=panel.querySelector('[role=status]');feedback.textContent='İşlem yapılıyor…';try{const r=await fn();if(typeof r==='string')feedback.textContent=r;else{render(r);feedback.textContent=r.valid?'İşlem tamamlandı.':r.reason;if(!r.valid)await root.ASMachDesktop.license.open();}}catch(e){feedback.textContent=String(e.message||e);}finally{busy=false;panel.querySelectorAll('button:not([data-close])').forEach(b=>b.disabled=!root.ASMachDesktop);}}
 function close(){if(!panel)return;panel.hidden=true;document.getElementById('ribbonLicenseButton')?.setAttribute('aria-pressed','false');}
 async function open(){if(!panel)create();panel.style.top=(document.querySelector('.toolbar').getBoundingClientRect().bottom)+'px';root.ASMachWorkspaceTabs?.activate('drawing');document.getElementById('ribbonLicenseButton')?.setAttribute('aria-pressed','true');panel.hidden=false;render(null);if(root.ASMachDesktop)await run(()=>root.ASMachDesktop.invoke('license_status'));}
 root.ASMachLicenseCenter={open,close};
})(window);
