(function(root){
 'use strict';const queue=[];let active=false;
 function request(options){return new Promise(resolve=>{queue.push({options,resolve});next();});}
 function next(){if(active||!queue.length)return;active=true;const {options:o,resolve}=queue.shift(),previous=document.activeElement,d=document.createElement('dialog');d.className='app-message';d.setAttribute('aria-labelledby','appMessageTitle');d.setAttribute('aria-describedby','appMessageText');
  d.innerHTML='<header><img class="am-logo" alt="" aria-hidden="true"><span id="appMessageTitle">ASMach Inspection</span><button type="button" data-close aria-label="Kapat">×</button></header><main><strong data-topic></strong><div id="appMessageText"></div><label data-option hidden><input type="checkbox"><span></span></label></main><footer></footer>';
  d.querySelector('.am-logo').src=root.ASMachBrandLogo;
  d.querySelector('[data-topic]').textContent=o.title||'';d.querySelector('[data-topic]').hidden=!o.title;d.querySelector('#appMessageText').textContent=String(o.message??'');
  if(o.checkbox){const l=d.querySelector('[data-option]');l.hidden=false;l.querySelector('span').textContent=o.checkbox.label;l.querySelector('input').checked=!!o.checkbox.checked;}
  const finish=value=>{if(!d.open)return;const checked=d.querySelector('input').checked;d.close();d.remove();active=false;if(previous?.isConnected)previous.focus({preventScroll:true});resolve({value,checked});next();};
  const choices=o.choices||[{value:true,label:'Evet',positive:true},{value:false,label:'Hayır'}];
  const accept=choices.find(c=>c.positive)||choices.find(c=>c.value===true)||choices[0];
  const cancelValue=Object.prototype.hasOwnProperty.call(o,'cancelValue')?o.cancelValue:false;
  for(const c of choices){const b=document.createElement('button');b.type='button';b.dataset.answer=String(c.value);const i=document.createElement('span');i.className=c.positive?'am-yes':'am-no';i.textContent=c.positive?'✓':c.value===false?'✕':'';i.setAttribute('aria-hidden','true');b.append(i,document.createTextNode(c.label));b.onclick=()=>finish(c.value);d.querySelector('footer').append(b);}
  const hint=(node,text)=>{const k=document.createElement('kbd');k.className='am-key';k.textContent=text;node.append(k);};
  const buttons=[...d.querySelectorAll('footer button')];buttons.forEach((b,index)=>{const choice=choices[index],keys=[];if(choice===accept){hint(b,'Enter');keys.push('Enter');}if(choice.value===cancelValue){hint(b,'Esc');keys.push('Escape');}if(choice.value===true)keys.push('E');if(choice.value===false)keys.push('H');b.setAttribute('aria-keyshortcuts',keys.join(' '));});
  const checkbox=d.querySelector('input[type=checkbox]');if(o.checkbox){checkbox.setAttribute('aria-keyshortcuts','Alt+1 Space');hint(d.querySelector('[data-option]'),'Alt+1');}
  const guide=document.createElement('small');guide.className='am-navigation';guide.textContent='← ↑ ↓ → Gezin · Boşluk Seç'+(choices.some(c=>c.value===true)&&choices.some(c=>c.value===false)?' · E Evet · H Hayır':'');d.querySelector('main').append(guide);
  d.querySelector('[data-close]').setAttribute('aria-keyshortcuts','Escape');d.querySelector('[data-close]').title='Kapat (Esc)';
  d.querySelector('[data-close]').onclick=()=>finish(cancelValue);d.addEventListener('cancel',e=>{e.preventDefault();finish(cancelValue);});
  d.addEventListener('keydown',e=>{e.stopPropagation();if(e.isComposing)return;const stop=()=>e.preventDefault();if(e.key==='Escape'){stop();if(!e.repeat)finish(cancelValue);return;}if(e.altKey&&e.code==='Digit1'&&o.checkbox){stop();if(!e.repeat){checkbox.focus();checkbox.click();}return;}if(e.ctrlKey||e.metaKey||e.altKey)return;
   if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Home','End'].includes(e.key)){stop();const items=[...(o.checkbox?[checkbox]:[]),...buttons].filter(n=>!n.disabled);const i=items.indexOf(document.activeElement),step=['ArrowLeft','ArrowUp'].includes(e.key)?-1:1;const next=e.key==='Home'?0:e.key==='End'?items.length-1:(i+step+items.length)%items.length;items[next]?.focus();return;}
   if(e.key==='Enter'){stop();if(!e.repeat)finish(accept.value);return;}
   const answer=e.key.toLocaleLowerCase('tr')==='e'?true:e.key.toLocaleLowerCase('tr')==='h'?false:undefined;if(answer!==undefined&&choices.some(c=>c.value===answer)){stop();if(!e.repeat)finish(answer);}
  });
  document.body.append(d);d.showModal();const safe=[...d.querySelectorAll('footer button')].find(b=>b.dataset.answer===String(o.defaultValue??false));(safe||d.querySelector('footer button')).focus();
 }
 const confirm=(message,title='İşlem onayı')=>request({message,title}).then(r=>r.value===true);
 const alert=(message,title='Uyarı')=>request({message,title,choices:[{value:true,label:'Tamam',positive:true}],defaultValue:true});
 root.ASMachMessages={request,confirm,alert};root.alert=message=>{void alert(message);};
 const css=document.createElement('style');css.textContent='.app-message{position:fixed;inset:0;margin:auto;width:min(460px,calc(100vw - 30px));max-height:85dvh;padding:0;border:1px solid #adb7c0;border-radius:9px;background:#fff;color:#14374a;box-shadow:0 12px 42px #10283945;font:12px Segoe UI,Arial,sans-serif;overflow:auto}.app-message::backdrop{background:#15293c30}.app-message header{display:flex;align-items:center;gap:8px;background:#f4f4f4;padding:8px 10px;border-bottom:1px solid #e6e6e6;font-size:13px;color:#172a34}.app-message .am-logo{display:grid;place-items:center;background:#008c9d;color:white;font-size:10px;font-weight:700;border-radius:5px;width:21px;height:21px}.app-message [data-close]{margin-left:auto;border:0;background:transparent;width:28px;height:24px;font-size:21px;color:#333;border-radius:3px}.app-message [data-close]:hover{background:#c73740;color:white}.app-message main{padding:15px 16px 13px;line-height:1.55}.app-message [data-topic]{display:block;margin-bottom:7px;font-size:12px}.app-message #appMessageText{white-space:pre-wrap;overflow-wrap:anywhere}.app-message [data-option]{display:flex;gap:7px;align-items:center;margin-top:11px}.app-message [hidden]{display:none!important}.app-message input[type=checkbox]{accent-color:#008c9d;width:14px;height:14px;margin:0}.app-message footer{display:flex;justify-content:flex-end;flex-wrap:wrap;gap:8px;background:#f4f4f4;border-top:1px solid #e5e5e5;padding:10px 14px}.app-message footer button{display:flex;align-items:center;justify-content:center;gap:7px;min-width:92px;min-height:30px;padding:4px 12px;border:1px solid #bfc7cd;border-radius:3px;background:#fafafa;color:#164967;font:12px Segoe UI,Arial,sans-serif}.app-message button:focus-visible{outline:2px solid #008a9e;outline-offset:1px}.app-message footer button:hover{background:#e8f4fa;border-color:#73afc6}.app-message .am-yes{color:#19923a;font-size:19px}.app-message .am-no{color:#d32d36;font-size:18px}';document.head.append(css);
 const shortcutsStyle=document.createElement('style');shortcutsStyle.textContent='.app-message .am-key{font:10px Segoe UI,sans-serif;padding:1px 4px;border:1px solid #c8d4dc;border-radius:3px;background:white;color:#446477;margin-left:3px}.app-message .am-navigation{display:block;margin-top:12px;color:#526c7d;font-size:10px}.app-message input:focus-visible{outline:2px solid #008a9e;outline-offset:3px}';document.head.append(shortcutsStyle);
 let invalidPending=false;document.addEventListener('invalid',e=>{if(!e.target.validationMessage)return;e.preventDefault();if(invalidPending)return;invalidPending=true;const input=e.target;void alert(input.validationMessage,'Girişi kontrol edin').then(()=>{invalidPending=false;if(input.isConnected)input.focus();});},true);
})(window);
