(function(root){
 'use strict';
 function validatedValue(target,text){let value=String(text).trim();if(target.type!=='textarea')value=value.replace(/\s*\n\s*/g,' ');if(target.tagName==='SELECT'){const matches=[...target.options].filter(o=>!o.disabled&&[o.textContent.trim(),o.value].some(v=>v.toLocaleLowerCase('tr')===value.toLocaleLowerCase('tr')));if(matches.length!==1)throw Error('Metin seçeneklerden biriyle tam eşleşmeli. Algılanan metni düzeltin veya seçeneği elle seçin.');value=matches[0].value;}if(target.type==='number'){value=value.replace(',','.');if(!/^[+-]?(?:\d+(?:\.\d*)?|\.\d+)$/.test(value))throw Error('Geçerli bir sayı okunamadı. Algılanan metni düzeltin.');}if(target.type==='date'){const m=value.match(/^(\d{2})[./-](\d{2})[./-](\d{4})$/);if(m)value=m[3]+'-'+m[2]+'-'+m[1];}const test=target.cloneNode(true);test.value=value;if(test.value!==value||!test.checkValidity())throw Error('Okunan değer alanın biçim veya sınırlarına uygun değil. Algılanan metni düzeltin.');return value;}
 const ocrIcon='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAAsQAAALEBxi1JjQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAHiSURBVEiJ1da/a1RBEAfwzz2jcIUJghqNWniFEIUgaNKJ0T9AESsLLRSsLG1EELRR0tpdYSNYBNFaxASVQFCMWgnijwuoiOLdxSYgSbTYPXy+u3eHd0HwC/uW2Rm+szuzM/vgIqp4h7W4is04jzqm5GMq2lRzxgWooT+HYCfm2jiYizat0I9qXxS+4xIOZIyKWGrjYAk3sZhZf4wrKBSEE2zANMp4nTH+jI85DrZjMLO2C2dxCLW+jPIVXrTZcRYf4khjOS0kf0HWFf6JgwQlIaGrhWLkTBI8xWRUfFkF8gbHZORuwihmhNs1g7GUbjce4BteRtuScE3rUTfQzvtWVDAe5XHMY0gonDc4IoR1D3ZgBI/i2g2cSxOuyTg4EY9YjnIF27ARm7Ae1/ATX4UCHcQZoeiO4xbeNgizddAttuA6TuFeJ8MKDqMQ53khdI0QHRXCcVA48Qge4rLQ/NZ12s1+oZdU4zya0g3jvpDkJ9gnJPl23FAZJ9NkBb8zv4xj+NRpBx0whLtCfhfETwmz2NsjucgxGzkXEqwIj0225faCxci58v83u2wdDGsuvm4enJYOpnE6Y1wU7vWY1riDH5rz98ePQk1+g+rl0R8QH/0JvM8xSvCsjYM6ngs3sRUmfgGbkG6k+AmvuwAAAABJRU5ErkJggg==';
 function attach(host,app){host.querySelectorAll('.pr-project input,.pr-project textarea,.pr-project select,[data-editor] input,[data-editor] textarea,[data-editor] select').forEach(input=>{if((!['text','number','textarea','date','select-one'].includes(input.type))||input.disabled||input.readOnly||input.closest('.po-input'))return;const name=input.closest('label')?.textContent.trim()||input.dataset.field||input.getAttribute('aria-label')||'Veri',wrap=document.createElement('div'),button=document.createElement('button');wrap.className='po-input';input.before(wrap);wrap.append(input,button);button.type='button';button.className='btn';button.innerHTML='<img src="'+ocrIcon+'" width="20" height="20" alt="" aria-hidden="true">';button.title=name+' — çizimden oku';button.setAttribute('aria-label',name+' için OCR');button.disabled=!app.state.fileData&&!app.state.pdfDoc;button.onclick=()=>open(app,input,name);});}
 async function open(app,target,name){
 const existing=target.closest('#projectSetup')?.querySelector('#projectOcrDialog');if(existing?.setTarget){existing.setTarget(target,name);return;}
 const key=app.state.pdfDoc||app.state.fileData;let original=target.value;let page=app.state.currentPage||1,zoom=1,box=null,start=null,token=0,ready=false;
 const d=document.createElement('dialog');d.id='projectOcrDialog';d.innerHTML='<header><strong></strong><button type="button" data-close aria-label="Kapat">×</button></header><nav><label>Sayfa <select data-page></select></label><button type="button" data-minus aria-label="Uzaklaştır">−</button><output>100%</output><button type="button" data-plus aria-label="Yakınlaştır">+</button><button type="button" data-fit>Sığdır</button><span>Kutuyla seç · Ctrl + tekerlek: yakınlaştır</span></nav><div class="po-view"><div class="po-stage"><canvas></canvas><div class="po-box" hidden></div></div></div><footer><label>Algılanan metin<textarea rows="2" data-text></textarea></label><p role="status"></p><div><button type="button" data-read disabled>Seçimi oku</button><button type="button" data-close>Vazgeç</button><button type="button" data-apply disabled>Alana aktar</button></div></footer>';
 d.querySelectorAll('button').forEach(b=>b.type='button');
 const setup=target.closest('#projectSetup');if(setup){setup.querySelector('#projectOcrDialog')?.remove();d.style.position='static';d.showModal=()=>{d.open=true;};d.close=()=>{d.open=false;d.dispatchEvent(new Event('close'));};setup.querySelector('form').append(d);}else document.body.append(d);
 d.querySelector('strong').textContent=name+' · Çizimden oku';const q=s=>d.querySelector(s),view=q('.po-view'),stage=q('.po-stage'),canvas=q('canvas'),mark=q('.po-box'),text=q('[data-text]'),status=q('[role=status]'),select=q('[data-page]');const current=()=>d.open&&d.isConnected&&target.isConnected&&(app.state.pdfDoc||app.state.fileData)===key;
 const pointerBadge=document.createElement('img');pointerBadge.src=ocrIcon;pointerBadge.className='po-cursor-badge';pointerBadge.alt='';pointerBadge.setAttribute('aria-hidden','true');pointerBadge.hidden=true;d.append(pointerBadge);
 const followPointer=e=>{const bounds=canvas.getBoundingClientRect();pointerBadge.hidden=e.pointerType==='touch'||e.clientX<bounds.left||e.clientX>bounds.right||e.clientY<bounds.top||e.clientY>bounds.bottom;if(!pointerBadge.hidden){pointerBadge.style.left=(e.clientX-10)+'px';pointerBadge.style.top=(e.clientY+18)+'px';}};
 canvas.addEventListener('pointerenter',followPointer);canvas.addEventListener('pointermove',followPointer);canvas.addEventListener('pointerleave',()=>pointerBadge.hidden=true);canvas.addEventListener('pointercancel',()=>pointerBadge.hidden=true);
 q('footer>label').hidden=!!setup;q('footer>div').hidden=!!setup;if(setup)q('header [data-close]').hidden=true;
 d.setTarget=(input,label)=>{if(ready)++token;target=input;name=label;original=input.value;clear();q('strong').textContent=name+' · Kutuyla seçerek doldur';};
 for(let i=1;i<=(app.state.pdfDoc?.numPages||1);i++){const option=document.createElement('option');option.textContent=i;option.value=i;select.append(option);}select.value=page;
 const size=()=>{stage.style.width=canvas.width*zoom+'px';stage.style.height=canvas.height*zoom+'px';q('output').textContent=Math.round(zoom*100)+'%';};const fit=()=>{if(!ready)return;zoom=Math.min((view.clientWidth-24)/canvas.width,(view.clientHeight-24)/canvas.height);size();};const clear=()=>{box=null;mark.hidden=true;text.value='';q('[data-apply]').disabled=true;q('[data-read]').disabled=true;};
 const render=async()=>{const job=++token;ready=false;clear();status.textContent='Sayfa hazırlanıyor…';try{const temp=document.createElement('canvas');if(app.state.pdfDoc){const pdfPage=await app.state.pdfDoc.getPage(page),v=pdfPage.getViewport({scale:1.5});temp.width=v.width;temp.height=v.height;await pdfPage.render({canvasContext:temp.getContext('2d'),viewport:v}).promise;}else{const source=app.elements.sourceCanvas;temp.width=source.width;temp.height=source.height;temp.getContext('2d').drawImage(source,0,0);}if(!current()||job!==token)return;canvas.width=temp.width;canvas.height=temp.height;canvas.getContext('2d').drawImage(temp,0,0);ready=true;fit();status.textContent='Aktarmak istediğiniz bilgiyi kutuyla seçin.';}catch(e){if(current())status.textContent=e.message;}};
 const changeZoom=factor=>{if(!ready)return;zoom=Math.max(.1,Math.min(6,zoom*factor));size();};q('[data-plus]').onclick=()=>changeZoom(1.25);q('[data-minus]').onclick=()=>changeZoom(.8);q('[data-fit]').onclick=fit;view.addEventListener('wheel',e=>{if(e.ctrlKey){e.preventDefault();changeZoom(e.deltaY<0?1.1:1/1.1);}},{passive:false});select.onchange=()=>{page=Number(select.value);void render();};
 const point=e=>{const r=canvas.getBoundingClientRect();return{x:Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),y:Math.max(0,Math.min(1,(e.clientY-r.top)/r.height))};};canvas.onpointerdown=e=>{if(!ready||e.button!==0)return;++token;original=target.value;clear();start=point(e);canvas.setPointerCapture(e.pointerId);};canvas.onpointermove=e=>{if(!start)return;const end=point(e);box={x:Math.min(start.x,end.x),y:Math.min(start.y,end.y),w:Math.abs(end.x-start.x),h:Math.abs(end.y-start.y)};Object.assign(mark.style,{left:box.x*100+'%',top:box.y*100+'%',width:box.w*100+'%',height:box.h*100+'%'});mark.hidden=false;};canvas.onpointerup=()=>{if(!start)return;start=null;q('[data-read]').disabled=!box||box.w*canvas.width<3||box.h*canvas.height<3;if(!q('[data-read]').disabled)void read();};canvas.onpointercancel=()=>{start=null;clear();};
 async function read(){if(!current()||!box)return;const job=++token,region={...box};q('[data-read]').disabled=true;status.textContent='Metin okunuyor…';try{const snapshot=await root.ASMachOCR.capture({pdfDoc:app.state.pdfDoc,page,canvas:app.elements.sourceCanvas,box:region,dpi:400,padding:0});const result=await root.ASMachOCR.recognize(snapshot,{textMode:true});if(!current()||job!==token)return;text.value=(result.text||'').trim();q('[data-apply]').disabled=!text.value;status.textContent=text.value?'Alana aktarılıyor…':'Metin bulunamadı; alanı yeniden seçin.';if(text.value)q('[data-apply]').onclick();}catch(e){if(current()&&job===token)status.textContent=e.message;}finally{if(current()&&job===token)q('[data-read]').disabled=false;}}
 q('[data-read]').onclick=read;text.oninput=()=>q('[data-apply]').disabled=!text.value.trim();q('[data-apply]').onclick=()=>{if(!current()||target.value!==original){status.textContent='Belge veya hedef alan değişti. Pencereyi kapatıp yeniden açın.';return;}let value;try{value=validatedValue(target,text.value);}catch(e){status.textContent=e.message;return;}target.value=value;target.dispatchEvent(new Event('input',{bubbles:true}));target.dispatchEvent(new Event('change',{bubbles:true}));original=value;status.textContent=name+' alanına aktarıldı. Başka bir alan seçebilirsiniz.';if(!setup)d.close();};d.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>d.close());d.addEventListener('close',()=>{++token;d.remove();target.focus();});d.showModal();await render();
 }
 const style=document.createElement('style');style.textContent='#projectOcrDialog [hidden]{display:none!important}.po-input{display:flex;gap:4px;min-width:0}.po-input>input,.po-input>textarea{flex:1;min-width:0}.po-input>button{flex:0 0 30px;padding:2px!important}#projectOcrDialog{width:min(1100px,94vw);height:min(820px,92dvh);max-height:92dvh;padding:0;border:1px solid #a9c8d6;border-radius:8px;color:#173c50}#projectOcrDialog[open]{display:flex;flex-direction:column}#projectOcrDialog::backdrop{background:#10253688}#projectOcrDialog header,#projectOcrDialog nav{display:flex;align-items:center;gap:8px;padding:9px 12px;border-bottom:1px solid #cfdee7;flex-shrink:0}#projectOcrDialog header{justify-content:space-between}#projectOcrDialog button,#projectOcrDialog select{padding:5px 9px;border:1px solid #bfd5e0;border-radius:4px;background:white;color:inherit}#projectOcrDialog nav span{font-size:11px}#projectOcrDialog .po-view{flex:1;min-height:0;overflow:auto;background:#e5edf2;padding:10px}#projectOcrDialog .po-stage{position:relative;margin:auto;background:white;flex-shrink:0}#projectOcrDialog canvas{display:block;width:100%;height:100%;touch-action:none;cursor:crosshair}#projectOcrDialog .po-box{position:absolute;border:1px dashed #008c9f;background:#00a1b51c;pointer-events:none;box-sizing:border-box}#projectOcrDialog footer{padding:10px 12px;flex-shrink:0;background:#f5f9fb}#projectOcrDialog textarea{display:block;box-sizing:border-box;width:100%;border:1px solid #bfd5e0}#projectOcrDialog footer>div{display:flex;justify-content:flex-end;gap:7px}#projectOcrDialog [role=status]{font-size:11px;margin:5px 0}#projectOcrDialog [data-apply]{background:#00899b;color:white}#projectOcrDialog button:disabled{opacity:.5}';document.head.append(style);root.ASMachProjectOcr={attach,open};
 const iconStyle=document.createElement('style');iconStyle.textContent=`
 .po-input{position:relative;display:block!important;min-width:0}
 .po-input>input,.po-input>textarea{display:block;width:100%!important;box-sizing:border-box!important;padding-right:36px!important}
 .po-input>select{display:block;width:100%!important;box-sizing:border-box!important;padding-right:60px!important}
 .po-input:has(>select)>button{right:22px}
 .po-input>button{position:absolute;right:3px;top:50%;transform:translateY(-50%);display:flex;align-items:center;justify-content:center;width:27px!important;height:26px!important;min-height:0!important;padding:3px!important;margin:0!important;border:0!important;border-radius:3px;background:transparent!important;cursor:pointer}
 .po-input>button:hover,.po-input>button:focus-visible{background:#dff2f5!important;outline:1px solid #07899a}
 .po-input>button img{display:block;width:20px;height:20px;object-fit:contain;pointer-events:none}
 .po-input>button:disabled{opacity:.4;cursor:default}
 #projectOcrDialog canvas{cursor:crosshair!important}
 #projectOcrDialog .po-cursor-badge{opacity:.5;position:fixed;width:20px;height:20px;z-index:2147483647;pointer-events:none;object-fit:contain;filter:drop-shadow(0 0 2px white)}
 `;document.head.append(iconStyle);
})(window);
