(function(root){
 'use strict';
 const pairs={
 'Kontrol planı':'Control Plan','Ara kontrol formu':'In-process Inspection Record','Karakteristik listesi':'Characteristic Register','Sipariş ve numune planı':'Order and Sampling Plan','Balon':'No.','Tür':'Type','Gereklilik / limit':'Requirement / Limits','Sorumlu':'Owner','Yöntem':'Method','Sıklık':'Frequency','Numune modu':'Sampling','Seviye':'Level','Kod':'Code','Kod harfi':'Code Letter','Adet':'Qty.','Operasyon':'Operation','Uygunsuzlukta işlem':'Reaction Plan','Sayfa / Zon':'Sheet / Zone','Gereklilik':'Requirement','Nominal':'Nominal','Alt tol.':'Lower Dev.','Üst tol.':'Upper Dev.','Datum':'Datum','Sorumlu / yöntem / sıklık':'Responsibility / Method / Frequency','Numune':'Sample','Numune adedi':'Sample Size','Kayıtlı sonuç':'Recorded Result','Görsel':'Generated GD&T','Snapshot':'Generated GD&T','Yöntem / sıklık':'Method / Frequency','Numune aralığı':'Sample Range','Tarih / Saat':'Date / Time','Kontrol eden / uygunluk':'Inspector / Disposition','Sipariş adedi':'Order Quantity','Parti adedi':'Lot Quantity','Sipariş / İş emri':'Order / Work Order','Manuel adet':'Manual Quantity','Parti alt sınırı':'Minimum Lot Size','Operatör':'Operator','Kalite':'Quality','Plan atanmadı':'No Plan Assigned','Manuel':'Manual','Tablo':'Sampling Table','Uzunluk':'Length','Çap':'Diameter','Yarıçap':'Radius','Açı':'Angle','Diş':'Thread','Pah':'Chamfer','Yüzey pürüzlülüğü':'Surface Roughness','Malzeme':'Material','Proses':'Process','Not':'Note','Diğer':'Other','Kumpas':'Caliper','Mikrometre':'Micrometer','Yükseklik mihengiri':'Height Gauge','Komparatör':'Dial Indicator','Mastar':'Gauge','Görsel kontrol':'Visual Inspection','Görsel Kontrol':'Visual Inspection','Yüzey pürüzlülük cihazı':'Surface Roughness Tester','Doküman / sertifika kontrolü':'Document / Certificate Review','Proses doğrulama':'Process Verification','Fonksiyon kontrolü':'Functional Inspection','Ölçüm kontrol raporu':'Dimensional Inspection Report','GD&T görsel kontrol raporu':'GD&T Inspection Report',
 'Does FAIR Contain a Documented Nonconformance(s)?  Yes / No':'FAIR kayıtlı uygunsuzluk içeriyor mu? Evet / Hayır','Part Type':'Parça türü','Detail part: continue at field 19. Assembly: complete the INDEX below.':'Detay parça: Alan 19 ile devam edin. Montaj: Aşağıdaki indeksi doldurun.','INDEX of part numbers or sub-assembly numbers':'Parça veya alt montaj numaraları indeksi','Part Number':'Parça numarası','Part Name':'Parça adı','Serial Number':'Seri numarası','FAIR Identifier':'FAIR numarası','Part Revision Level':'Parça revizyonu','Drawing Number':'Çizim numarası','Drawing Revision Level':'Çizim revizyonu','Additional Changes':'Ek değişiklikler','Manufacturing Process Reference':'Üretim proses referansı','Organization Name':'Kuruluş adı','Supplier Code':'Tedarikçi kodu','Purchase Order Number':'Sipariş numarası','Detail / Assembly':'Detay / Montaj','Full FAI / Partial FAI':'Tam FAI / Kısmi FAI','Date':'Tarih','Comments':'Açıklamalar','FAIR Verified By':'FAIR doğrulayan','FAIR Reviewed/Approved By':'FAIR gözden geçiren / onaylayan','Customer Approval':'Müşteri onayı','Material or Process Name':'Malzeme veya proses adı','Specification Number':'Şartname numarası','Code':'Kod','Supplier':'Tedarikçi','Customer Approval Verification':'Müşteri onayı doğrulaması','Certificate of Conformance Number':'Uygunluk sertifikası numarası','Functional Test Procedure Number':'Fonksiyon test prosedürü numarası','Acceptance Report Number':'Kabul raporu numarası','Char. No.':'Kar. No.','Reference Location':'Referans konumu','Characteristic Designator':'Karakteristik sınıfı','Requirement':'Gereklilik','Results':'Sonuçlar','Designed / Qualified Tooling':'Tasarlanmış / nitelendirilmiş takım','Nonconformance Number':'Uygunsuzluk numarası','Additional Data / Comments':'Ek bilgiler / açıklamalar','Characteristic Accountability':'Karakteristik takibi','Inspection / Test Results':'Muayene / test sonuçları',
 'FORM 1 – PART NUMBER ACCOUNTABILITY':'FORM 1 - PARÇA NUMARASI TAKİBİ','FORM 2 – PRODUCT ACCOUNTABILITY':'FORM 2 - ÜRÜN TAKİBİ','FORM 3 – CHARACTERISTIC ACCOUNTABILITY, VERIFICATION AND COMPATIBILITY EVALUATION':'FORM 3 - KARAKTERİSTİK TAKİBİ, DOĞRULAMA VE UYUMLULUK DEĞERLENDİRMESİ'
 };
 Object.assign(pairs,{'Ortak plan (sorumlu atanmamış)':'Shared plan (owner unassigned)','Belirtilmedi':'Not specified','Sonuç':'Result','Üretilen GD&T':'Generated GD&T','KUMPAS':'Caliper','MIKROMETRE':'Micrometer','MİKROMETRE':'Micrometer'});
 const englishKeys=new Set(['Does FAIR Contain a Documented Nonconformance(s)?  Yes / No','Part Type','Detail part: continue at field 19. Assembly: complete the INDEX below.','INDEX of part numbers or sub-assembly numbers','Part Number','Part Name','Serial Number','FAIR Identifier','Part Revision Level','Drawing Number','Drawing Revision Level','Additional Changes','Manufacturing Process Reference','Organization Name','Supplier Code','Purchase Order Number','Detail / Assembly','Full FAI / Partial FAI','Date','Comments','FAIR Verified By','FAIR Reviewed/Approved By','Customer Approval','Material or Process Name','Specification Number','Code','Supplier','Customer Approval Verification','Certificate of Conformance Number','Functional Test Procedure Number','Acceptance Report Number','Char. No.','Reference Location','Characteristic Designator','Requirement','Results','Designed / Qualified Tooling','Nonconformance Number','Additional Data / Comments','Characteristic Accountability','Inspection / Test Results',...Object.keys(pairs).filter(x=>x.startsWith('FORM '))]);
 function text(v){if(typeof v!=='string')return v;const company=root.ASMachBrandSettings?.load().company;if(company)v=v.replace(/ŞENYÜZ MAKİNE|Şenyüz Makine/g,()=>company);const m=v.match(/^(\d+\. )?(.*?)(\n[\s\S]*)?$/),prefix=m?.[1]||'',key=m?.[2]||v,tail=m?.[3]||'';if(!pairs[key])return v;return (key==='Balon'?'':prefix)+(englishKeys.has(key)?key+'\n'+pairs[key]:pairs[key]+'\n'+key)+tail;}
 const both=(en,tr)=>en+'\n'+tr;
 function frequency(p){if(!p.inspectionFrequency)return both('Not specified','Belirtilmedi');const n=p.frequencyInterval||'',map={EACH_PART:['Every part (100%)','Her parça (%100)'],FIRST_PIECE:['First piece','İlk parça'],HOURLY:['Hourly','Saatlik'],LAST_PIECE:['Last piece','Son parça'],FIRST_LAST:['First and last piece','İlk ve son parça'],PER_LOT:['Each lot','Her parti'],PER_SHIFT:['Each shift','Her vardiya'],EVERY_N_PIECES:[`Every ${n} pieces`,`Her ${n} parçada`],EVERY_N_HOURS:[`Every ${n} hours`,`Her ${n} saatte`],SETUP:['At setup','Ayar sonrası'],CUSTOM:['Custom plan','Özel plan']};const a=map[p.inspectionFrequency];return a?both(...a):root.ASMachInspectionPlan?.label(p)||'';}
 function logo(){return root.ASMachBrandSettings?.load().logo||root.ASMachReportLogo||'';}
 function picture(data,r,c,maxW=170,maxH=56,name='Şenyüz Makine'){if(!/^data:image\/png;base64,/.test(data||''))return null;const bytes=Uint8Array.from(atob(data.split(',')[1]),x=>x.charCodeAt(0));const v=new DataView(bytes.buffer),w=v.getUint32(16),h=v.getUint32(20),k=Math.min(maxW/w,maxH/h);return{r,c,bytes,dataUrl:data,width:w*k,height:h*k,name};}
 function decorate(model){if(model.branded)return model;model.branded=true;for(const s of model.sheets){s.cells.forEach(c=>{c.value=text(c.value);if(typeof c.value==='string'&&c.value.includes('\n')&&c.r<8)s.heights[c.r]=Math.max(s.heights[c.r]||18,c.style===1?52:42);});s.images=s.images.filter(p=>!p.name?.includes('snapshot')||p.name?.includes('GD&T'));const title=s.cells.find(c=>c.r===0&&c.c===0&&c.cs===s.n);if(title){const reserve=Math.max(2,Math.ceil(s.n/4));title.cs-=reserve;const pic=picture(logo(),0,s.n-reserve,Math.min(190,reserve*(s.colWidth*7+5)),64);if(pic)s.images.push(pic);s.heights[0]=Math.max(s.heights[0]||0,56);}else{const row=s.lastRow+1,pic=picture(logo(),row,0);if(pic){s.images.push(pic);s.lastRow=row+3;s.heights[row]=50;}}for(const c of s.cells){if(typeof c.value!=='string'||!c.value)continue;const chars=Math.max(4,(s.widths?s.widths.slice(c.c,c.c+c.cs).reduce((a,b)=>a+b,0):s.colWidth*c.cs)-1),lines=c.value.split('\n').reduce((n,t)=>n+Math.max(1,Math.ceil(t.length/chars)),0),height=Math.ceil((lines*(c.style===1?22:13)+12)/(c.rs||1));for(let r=c.r;r<c.r+(c.rs||1);r++)s.heights[r]=Math.max(s.heights[r]||18,Math.min(400,height));}s.paperSize||=s.landscape?8:9;s.printTitles||=s.freeze?`$1:$${s.freeze}`:undefined;s.footer=(root.ASMachBrandSettings?.load().company||'ŞENYÜZ MAKİNE')+'  |  Controlled record / Kontrollü kayıt';}return model;}
 function templateFiles(files){
   if(!root.DOMParser)return;
   const doc=new root.DOMParser().parseFromString(files['xl/sharedStrings.xml'],'application/xml'),nodes=[...doc.getElementsByTagName('si')];
   const overrides={41:'Baseline part number (including revision)\nTemel parça numarası (revizyon dahil)',53:'a) Detail part: go to field 19. b) Assembly: complete the INDEX below.\na) Detay parça: alan 19 ile devam edin. b) Montaj: aşağıdaki indeksi doldurun.',57:'INDEX of part / sub-assembly numbers\nParça / alt montaj numaraları indeksi',67:'19. Does FAIR contain documented nonconformance(s)?\nFAIR belgelenmiş uygunsuzluk içeriyor mu?',78:'Form 1: Part Number Accountability\nParça numarası takibi',79:'Form 2: Product Accountability\nÜrün takibi - malzeme, özel proses ve fonksiyon testleri',80:'Form 3: Characteristic Accountability\nKarakteristik takibi, doğrulama ve uyumluluk değerlendirmesi'};
   for(const [i,node] of nodes.entries()){const raw=[...node.getElementsByTagName('t')].map(t=>t.textContent).join('').trim(),m=raw.match(/^(\d+\.\s*)?([\s\S]*?)\(([^()]+)\)\s*:?$/);let content=overrides[i];if(!content&&m)content=(m[1]||'')+m[3].trim()+'\n'+m[2].trim();if(content){node.textContent='';const t=doc.createElementNS(doc.documentElement.namespaceURI,'t');t.setAttributeNS('http://www.w3.org/XML/1998/namespace','xml:space','preserve');t.textContent=content;node.appendChild(t);}}
   files['xl/sharedStrings.xml']=new root.XMLSerializer().serializeToString(doc);
   const stylesDoc=new root.DOMParser().parseFromString(files['xl/styles.xml'],'application/xml');
   for(const xf of stylesDoc.getElementsByTagName('cellXfs')[0].children){let alignment=xf.getElementsByTagName('alignment')[0];if(!alignment){alignment=stylesDoc.createElementNS(stylesDoc.documentElement.namespaceURI,'alignment');xf.appendChild(alignment);}alignment.setAttribute('wrapText','1');alignment.removeAttribute('shrinkToFit');xf.setAttribute('applyAlignment','1');}
   files['xl/styles.xml']=new root.XMLSerializer().serializeToString(stylesDoc);
   for(const key of Object.keys(files))if(/^xl\/worksheets\/sheet\d+\.xml$/.test(key)){
     const sheetDoc=new root.DOMParser().parseFromString(files[key],'application/xml'),ns=sheetDoc.documentElement.namespaceURI;
     for(const c of sheetDoc.getElementsByTagName('c')){if(c.getAttribute('t')!=='s')continue;const i=Number(c.getElementsByTagName('v')[0]?.textContent),value=nodes[i]?.textContent||'';if(!value.includes('\n'))continue;const ref=c.getAttribute('r'),row=Number(ref.match(/\d+/)[0]),merge=[...sheetDoc.getElementsByTagName('mergeCell')].find(m=>m.getAttribute('ref').split(':')[0]===ref),end=merge?Number(merge.getAttribute('ref').split(':')[1].match(/\d+/)[0]):row;for(let n=row;n<=end;n++){const rowNode=[...sheetDoc.getElementsByTagName('row')].find(r=>Number(r.getAttribute('r'))===n);if(rowNode){rowNode.setAttribute('ht',Math.max(Number(rowNode.getAttribute('ht')||15),32/(end-row+1)));rowNode.setAttribute('customHeight','1');}}}
     for(const el of sheetDoc.getElementsByTagName('oddHeader'))el.textContent='&CFIRST ARTICLE INSPECTION / İlk Parça Onay Formu&RPage / Sayfa: &P / &N';
     for(const el of sheetDoc.getElementsByTagName('oddFooter'))el.textContent='&RŞENYÜZ MAKİNE | FAI Record / İlk Parça Kaydı';
     files[key]=new root.XMLSerializer().serializeToString(sheetDoc);
   }
 }
 root.ASMachReportBrand={text,both,frequency,logo,picture,decorate,templateFiles};
})(window);
