/* Independent inspection responsibilities. Sampling table transcribed from the user's reference. */
(function(root){
 'use strict';
 const roles={operator:'Operatör',quality:'Kalite'},levels=['S1','S2','S3','S4','G1','G2','G3'];
 const starts=[2,9,16,26,51,91,151,281,501,1201,3201,10001,35001,150001,500001];
 const codes=['AAAAAAB','AAAAABC','AABBBCD','ABBCCDE','BBCCCEF','BBCDDFG','BCDEEGH','BCDEFHJ','CCEFGJK','CDEGHKL','CDFGJLM','CDFHKMN','DEGJLNP','DEGJMPQ','DEHKNQR'].map(s=>s.split(''));
 const sizes={A:2,B:3,C:5,D:8,E:13,F:20,G:32,H:50,J:80,K:125,L:200,M:315,N:500,P:800,Q:1250,R:2000};
 const originalSizes={...sizes},samplingKey='asmach.sampling-counts.v1';
 try{const saved=JSON.parse(root.ASMachPreferences.getItem(samplingKey)||'{}');for(const code of Object.keys(sizes))if(Number.isSafeInteger(saved[code])&&saved[code]>0)sizes[code]=saved[code];}catch{}
 function openSamplingTable(onSave,container){
  const d=document.createElement(container?'section':'dialog');d.id='samplingTableEditor';d.setAttribute('aria-label','Numune alma referans tablosu');
  d.innerHTML='<header><strong>Numune alma referans tablosu</strong><button type="button" data-close aria-label="Kapat">×</button></header><main><p>Yüklenen referanstan programa aktarılmış tablo. Parti aralıkları ve kod harfleri sabittir; kod başına numune adetlerini aşağıdan düzenleyebilirsiniz. Kabul / ret sayıları bu tabloda tanımlı değildir.</p><div class="st-scroll"><table><thead><tr><th>Parti büyüklüğü</th>'+levels.map(l=>'<th>'+l+'</th>').join('')+'</tr></thead><tbody>'+starts.map((start,i)=>'<tr><th>'+start.toLocaleString('tr-TR')+' – '+(starts[i+1]?(starts[i+1]-1).toLocaleString('tr-TR'):'üzeri')+'</th>'+codes[i].map(code=>'<td>'+code+' <small data-count="'+code+'"></small></td>').join('')+'</tr>').join('')+'</tbody></table></div><h4>Kod harfine göre numune adedi</h4><div class="st-counts">'+Object.keys(sizes).map(code=>'<label>'+code+'<input aria-label="'+code+' numune adedi" data-code="'+code+'" type="number" min="1" step="1" value="'+sizes[code]+'"></label>').join('')+'</div><p>Numune adedi parti adedini aşarsa parti adedine sınırlandırılır. Değiştirilen adetler kullanıcıya özel plandır; bir standarda uygunluk onayı değildir.</p><p data-status role="status"></p></main><footer><button type="button" data-reset>Referans adetlerine dön</button><button type="button" data-close>Vazgeç</button><button type="button" data-save>Adetleri kaydet</button></footer>';
  const style=document.createElement('style');style.textContent='#samplingTableEditor{padding:0;width:min(850px,94vw);max-height:92vh;border:1px solid #aabdc9;border-radius:6px;color:#234355}#samplingTableEditor[open]{display:flex;flex-direction:column}#samplingTableEditor::backdrop{background:#14253666}#samplingTableEditor header,#samplingTableEditor footer{display:flex;gap:8px;align-items:center;justify-content:space-between;padding:9px 12px;background:#eef3f6;flex-shrink:0}#samplingTableEditor main{padding:10px 12px;overflow:auto}#samplingTableEditor p{font-size:11px;margin:6px 0;line-height:1.4}#samplingTableEditor table{border-collapse:collapse;width:100%;font-size:11px}#samplingTableEditor th,#samplingTableEditor td{border:1px solid #d0dfe7;padding:4px 7px;text-align:center}#samplingTableEditor th{background:#eef5f8}#samplingTableEditor small{color:#527587}#samplingTableEditor .st-counts{display:grid;grid-template-columns:repeat(8,1fr);gap:6px}#samplingTableEditor label{display:flex;align-items:center;gap:4px;font-size:11px}#samplingTableEditor input{min-width:0;width:100%;height:26px;box-sizing:border-box;border:1px solid #bdcfd9;border-radius:3px}#samplingTableEditor button{border:1px solid #bdcfd9;background:white;padding:6px 10px;border-radius:3px;color:#234355;cursor:pointer}#samplingTableEditor [data-save]{background:#008a9d;color:white}#samplingTableEditor h4{margin:10px 0;font-size:12px}';d.append(style);(container||document.body).append(d);d.close=container?()=>{d.querySelector('[data-status]').textContent='Adetler kaydedildi.';}:d.close.bind(d);if(container){d.querySelectorAll('[data-close]').forEach(b=>b.remove());d.style.cssText='width:100%;max-height:none;box-sizing:border-box';}
  const refresh=()=>{for(const el of d.querySelectorAll('[data-count]'))el.textContent='('+d.querySelector('[data-code="'+el.dataset.count+'"]').value+')';};refresh();d.addEventListener('input',refresh);
  d.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>d.close());d.onclose=()=>d.remove();
  d.querySelector('[data-reset]').onclick=()=>{d.querySelectorAll('[data-code]').forEach(input=>input.value=originalSizes[input.dataset.code]);refresh();d.querySelector('[data-status]').textContent='Referans adetleri hazırlandı. Uygulamak için kaydedin.';};
  d.querySelector('[data-save]').onclick=async()=>{const next={};for(const input of d.querySelectorAll('[data-code]')){const n=Number(input.value);if(!Number.isSafeInteger(n)||n<1){d.querySelector('[data-status]').textContent='Tüm adetler pozitif tam sayı olmalı.';input.focus();return;}next[input.dataset.code]=n;}const changed=Object.keys(sizes).filter(k=>sizes[k]!==next[k]);if(!changed.length){d.close();return;}if(!await root.ASMachMessages.confirm('Numune adetleri değişecek:\n'+changed.map(k=>k+': '+sizes[k]+' → '+next[k]).join('\n')+'\nBu cihazda “Tabloya göre” kullanan mevcut ve yeni planlar yeniden hesaplanır. Manuel adetler değişmez. Kaydedilsin mi?'))return;try{root.ASMachPreferences.setItem(samplingKey,JSON.stringify(next));await root.ASMachPreferences.flush?.();Object.assign(sizes,next);onSave?.();root.ASMachApp?.renderAll();d.close();}catch{d.querySelector('[data-status]').textContent='Adetler kaydedilemedi.';}};
  if(!container)d.showModal();return d;
 }
 const clone=x=>JSON.parse(JSON.stringify(x));
 const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const blank=()=>({enabled:false,inspectionMethod:'',inspectionFrequency:'',frequencyInterval:'',frequencyNote:'',sampleMode:'manual',sampleLevel:'G2',sampleCount:'',sampleStandard:'reference',sampleStandardNote:'',operation:'',reaction:''});
 function normalize(record){if(record.commonPlanEnabled===true){const p={...blank(),...(record.commonSampling||{}),enabled:true};for(const k of ['inspectionMethod','inspectionFrequency','frequencyInterval','frequencyNote','operation','reaction'])p[k]=String(record[k]||'');return {operator:{...p},quality:{...p}};}if(!record.rolePlans)return record.commonPlanEnabled===false?{operator:blank(),quality:blank()}:null;return Object.fromEntries(Object.keys(roles).map(role=>{const p=record.rolePlans[role]||{};return[role,{...blank(),...Object.fromEntries(Object.keys(blank()).map(k=>[k,k==='enabled'?p.enabled===true:String(p[k]??blank()[k])]))}];}));}
 function optionalSample(p,role){return role==='operator'&&p.inspectionFrequency!=='EACH_PART'&&(p.sampleMode==='none'||p.sampleMode==='manual'&&String(p.sampleCount??'').trim()==='');}
 function sample(p,lot,role){if(p.inspectionFrequency==='EACH_PART'&&p.sampleMode!=='all')return{error:'Her parça kontrolünde numune seçimini %100 yapın.'};if(optionalSample(p,role))return{code:'',count:'',optional:true};const n=Number(lot);
   if(p.sampleMode==='manual'){const count=Number(p.sampleCount);if(!Number.isSafeInteger(count)||count<1)return{error:'Numune adedi pozitif tam sayı olmalı.'};if(lot==null||String(lot).trim()==='')return{code:'',count};if(!Number.isSafeInteger(n)||n<1)return{error:'Parti adedi pozitif tam sayı olmalı.'};return count>n?{error:'Numune adedi parti adedini aşamaz.'}:{code:'',count};}
   if(!Number.isSafeInteger(n)||n<1)return{error:'Parti adedi pozitif tam sayı olmalı.'};
   if(p.sampleMode==='all')return{code:'',count:n};
   if(p.sampleMode==='manual'){const count=Number(p.sampleCount);return !Number.isSafeInteger(count)||count<1||count>n?{error:'Numune adedi 1 ile parti adedi arasında olmalı.'}:{code:'',count};}
   if(p.sampleMode!=='table'||!levels.includes(p.sampleLevel))return{error:'Numune planını ve muayene seviyesini seçin.'};
   if(n<2)return{error:'Paylaşılan tablo 2 adetten başlıyor. 1 adet için %100 kontrol seçin.'};
   const row=starts.findLastIndex(x=>n>=x),code=codes[row][levels.indexOf(p.sampleLevel)];return{code,count:Math.min(n,sizes[code]),tableCount:sizes[code]};
 }
 function validate(record,lot){const plans=normalize(record);if(!plans)return'';for(const [role,p] of Object.entries(plans)){if(!p.enabled)continue;
   if(!p.inspectionMethod)return roles[role]+': kontrol yöntemi seçin.';
   const methods=root.ASMachApp?.getMethods?.();if(methods&&!methods.some(m=>m.value===p.inspectionMethod))return roles[role]+': seçilen yöntem artık tanımlı değil.';
   if(!p.inspectionFrequency&&role!=='operator')return roles[role]+': kontrol sıklığı seçin.';
   if(p.inspectionFrequency==='EACH_PART'&&p.sampleMode!=='all')return roles[role]+': her parça kontrolünde numune seçimi %100 olmalı.';
   const e=root.ASMachInspectionPlan.validate({...p,rolePlans:null});if(e)return roles[role]+': '+e;
   const sampling=samplingError(p,role,lot);if(sampling)return roles[role]+': '+sampling;
 }return'';}
 function samplingError(p,role,lot){
   if(p.sampleStandard==='custom'&&!String(p.sampleStandardNote||'').trim())return 'Numune standardının adını ve revizyonunu girin.';
   if(p.sampleStandard==='custom'&&p.sampleMode==='table')return 'Özel standart için otomatik tablo hesabı yok; manuel adet veya %100 seçin.';
   if(p.inspectionFrequency==='EACH_PART'&&p.sampleMode!=='all')return 'Her parça kontrolünde numune seçimi %100 olmalı.';
   if(optionalSample(p,role))return '';
   if(!['manual','table','all'].includes(p.sampleMode))return 'Numune planını seçin.';
   if(p.sampleMode==='manual'&&(!Number.isSafeInteger(Number(p.sampleCount))||Number(p.sampleCount)<1))return 'Numune adedi pozitif tam sayı olmalı.';
   if(p.sampleMode==='table'&&!levels.includes(p.sampleLevel))return 'Muayene seviyesini seçin.';
   if(lot!==undefined){const s=sample(p,lot,role);if(s.error)return s.error;}return '';
 }
 function mount(host,record,methods,lot){
   let touched=Boolean(record.rolePlans),plans=normalize(record)||{operator:blank(),quality:blank()};
   host.classList.add('role-plan-host');
   const expanded={operator:false,quality:false};let migrationOpen=false;
   function render(){
    host.querySelectorAll('[data-advanced]').forEach(d=>expanded[d.dataset.advanced]=d.open);
    if(host.querySelector('.rp-migration'))migrationOpen=host.querySelector('.rp-migration').open;
    host.innerHTML=`<div class="rp-heading"><b>Kontrol planı</b><div class="rp-copy"><button type="button" class="btn" data-copy="operator" title="Operatör planını kaliteye kopyala">Operatör → Kalite</button><button type="button" class="btn" data-copy="quality" title="Kalite planını operatöre kopyala">Kalite → Operatör</button></div></div>${!record.rolePlans&&(record.inspectionMethod||record.inspectionFrequency)?`<details class="rp-migration" ${migrationOpen?'open':''}><summary>Eski kayıttan aktar</summary><label>Yöntem ve sıklık<select data-migrate><option value="">Aktarılmadı — eski kayıt korunur</option><option value="operator">Operatöre aktar</option><option value="quality">Kaliteye aktar</option><option value="both">Her ikisine aktar</option></select></label></details>`:''}<div class="rp-cards">${Object.entries(roles).map(([role,label])=>{const p=plans[role];const select=(key,title,items)=>`<label>${title}<select data-role="${role}" data-key="${key}">${items.map(m=>`<option value="${esc(m.value)}" ${p[key]===m.value?'selected':''}>${esc(m.label)}</option>`).join('')}</select></label>`;const input=(key,title,type='text')=>`<label>${title}<input data-role="${role}" data-key="${key}" type="${type}" ${type==='number'?'min="1" step="1"':''} value="${esc(p[key])}"></label>`;
     return `<fieldset class="rp-card ${p.enabled?'rp-enabled':''}"><legend><label class="rp-enable"><input data-role="${role}" data-key="enabled" type="checkbox" ${p.enabled?'checked':''}> ${label} kontrolü</label></legend><p class="rp-disabled" ${p.enabled?'hidden':''}>Bu rol için kontrol planını etkinleştirin.</p><div ${p.enabled?'':'hidden'} class="rp-content"><div class="rp-fields">${select('inspectionMethod','Yöntem',[{value:'',label:'Yöntem seçin'},...methods])}${select('inspectionFrequency',role==='operator'?'Sıklık · isteğe bağlı':'Sıklık',root.ASMachInspectionPlan.FREQUENCIES)}${['EVERY_N_PIECES','EVERY_N_HOURS'].includes(p.inspectionFrequency)?input('frequencyInterval',p.inspectionFrequency==='EVERY_N_HOURS'?'Saat aralığı':'Parça aralığı','number'):''}${select('sampleMode','Numune seçimi',[...(role==='operator'?[{value:'none',label:'Adet belirtilmedi'}]:[]),{value:'manual',label:'Manuel adet'},{value:'table',label:'Tabloya göre'},{value:'all',label:'%100 kontrol'}])}${p.sampleMode==='table'?select('sampleLevel','Muayene seviyesi',levels.map(v=>({value:v,label:v}))):p.sampleMode==='manual'?input('sampleCount',role==='operator'?'Adet · isteğe bağlı':'Numune adedi','number'):''}</div><output data-sample="${role}"></output><details class="rp-advanced" data-advanced="${role}" ${expanded[role]?'open':''}><summary>Ek bilgiler${p.frequencyNote||p.operation||p.reaction?' · kayıt var':''}</summary><div class="rp-fields">${input('frequencyNote','Sıklık açıklaması')}${input('operation','Operasyon')}${input('reaction','Uygunsuzlukta işlem')}</div></details></div></fieldset>`;}).join('')}</div>`;
     for(const role of Object.keys(roles)){const fields=host.querySelector(`[data-role="${role}"][data-key="sampleMode"]`)?.closest('.rp-fields');if(!fields)continue;const label=document.createElement('label');label.innerHTML=`Numune standardı<select data-role="${role}" data-key="sampleStandard"><option value="reference">Mevcut referans tablosu</option><option value="custom">Standart / müşteri planı (manuel)</option></select>`;label.querySelector('select').value=plans[role].sampleStandard;fields.prepend(label);if(plans[role].sampleStandard==='custom'){const note=document.createElement('label');note.innerHTML=`Standart / revizyon<input data-role="${role}" data-key="sampleStandardNote" value="${esc(plans[role].sampleStandardNote)}" placeholder="Standart adı, revizyon, plan referansı">`;label.after(note);}}
     host.querySelectorAll('[data-key]').forEach(node=>{node.onchange=()=>{touched=true;plans[node.dataset.role][node.dataset.key]=node.type==='checkbox'?node.checked:node.value;const structural=['enabled','sampleMode','inspectionFrequency','sampleStandard'].includes(node.dataset.key);if(structural){const {role,key}=node.dataset;render();host.querySelector('[data-role="'+role+'"][data-key="'+key+'"]')?.focus({preventScroll:true});}else summary();};});
     host.querySelectorAll('[data-copy]').forEach(button=>button.onclick=()=>{touched=true;const from=button.dataset.copy;plans[from==='operator'?'quality':'operator']=clone(plans[from]);render();});
     const tableButton=document.createElement('button');tableButton.type='button';tableButton.className='btn';tableButton.textContent='Numune tablosu / adetleri düzenle';tableButton.onclick=()=>openSamplingTable(summary);host.querySelector('.rp-heading').append(tableButton);
     const migration=host.querySelector('[data-migrate]');if(migration)migration.onchange=()=>{touched=true;for(const role of Object.keys(roles))if(migration.value===role||migration.value==='both')plans[role]={...plans[role],enabled:true,inspectionMethod:record.inspectionMethod||'',inspectionFrequency:record.inspectionFrequency||'',frequencyInterval:record.frequencyInterval||'',frequencyNote:record.frequencyNote||''};render();};summary();
   }
   function summary(){const n=typeof lot==='function'?lot():lot;host.querySelectorAll('[data-key="sampleLevel"]').forEach(select=>{for(const option of select.options){const result=sample({...plans[select.dataset.role],sampleLevel:option.value},n,select.dataset.role);option.textContent=option.value+' - P:'+(n||'—')+' - N:'+(result.error?'—':result.count??'—');}});host.querySelectorAll('[data-sample]').forEach(node=>{const s=sample(plans[node.dataset.sample],n,node.dataset.sample);node.textContent=s.error|| (s.optional?'Numune adedi isteğe bağlı; boş bırakılabilir.':`${s.code?'Kod '+s.code+' · ':''}${s.count} numune${n?' / '+n+' adet':''} · Kontrol sıklığı ayrı uygulanır.`);});}
   if(!document.getElementById('role-plan-style')){const style=document.createElement('style');style.id='role-plan-style';style.textContent=`
   .role-plan-host{font:12px 'Segoe UI',Arial,sans-serif;grid-column:1/-1;min-width:0}
   .role-plan-host [hidden]{display:none!important}
   .role-plan-host .rp-heading{display:flex;align-items:center;justify-content:space-between;gap:8px;margin-bottom:10px;flex-wrap:wrap}
   .role-plan-host .rp-copy{display:flex;gap:5px;flex-wrap:wrap}
   .role-plan-host .rp-cards{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;align-items:start}
   .role-plan-host .rp-card{margin:0!important;min-width:0;border:1px solid #d5e1e8;border-radius:7px;padding:10px;background:#f8fafc}
   .role-plan-host .rp-enabled{background:white;border-color:#badbe2}
   .role-plan-host .rp-card legend{padding:0 4px}
   html body .role-plan-host .rp-card label{display:grid!important;justify-content:stretch!important;align-items:stretch;gap:4px;margin:0!important;font-size:11px;min-width:0;color:#4e687b}
   html body .role-plan-host .rp-card .rp-enable{display:flex!important;align-items:center;justify-content:flex-start;gap:7px;font-weight:600;color:#21495c}
   .role-plan-host .rp-enable input{width:14px!important;height:14px!important;margin:0!important;accent-color:#008d9f}
   .role-plan-host .rp-fields{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px 10px}
   html body .role-plan-host .rp-card input:not([type=checkbox]),html body .role-plan-host .rp-card select{width:100%!important;min-width:0;min-height:29px!important;height:29px;padding:4px 6px!important;border:1px solid #cbdbe5;border-radius:4px;font-size:11px;background:#fff;color:#28495c}
   .role-plan-host .rp-card output{display:block;font-size:10px;color:#607b8d;line-height:1.4;margin:8px 0}
   .role-plan-host .rp-advanced{border-top:1px solid #e2ebf0;margin-top:8px;padding-top:7px}
   .role-plan-host summary{font-size:11px;cursor:pointer;color:#527487;padding:2px 0}
   .role-plan-host .rp-advanced[open] summary{margin-bottom:8px}
   .role-plan-host .rp-advanced .rp-fields>label:last-child{grid-column:1/-1}
   .role-plan-host .rp-migration{margin-bottom:10px;padding:7px 9px;border:1px solid #e2e9ef;border-radius:5px}
   .role-plan-host .rp-migration label{display:grid;gap:5px;font-size:11px}
   .role-plan-host .rp-disabled{font-size:11px;color:#718494;margin:6px 0;line-height:1.5}
   .role-plan-host .btn{font-size:10px!important;padding:4px 7px!important;min-height:27px!important}
   .rd-plan-footer{display:flex;align-items:center;justify-content:flex-end;gap:10px;position:sticky;bottom:-14px;margin:12px -14px -14px;padding:9px 14px;background:white;border-top:1px solid #e0e9ef}
   .rd-plan-footer p{margin:0!important;flex:1;line-height:1.4}.rd-plan-footer p:empty{display:none}
   @media(max-width:650px){.role-plan-host .rp-cards{grid-template-columns:1fr}.role-plan-host .rp-copy{gap:3px}}
   `;document.head.append(style);}
   render();return{read:()=>touched?clone(plans):null,refresh:summary};
 }
 function open(app,record,onSave){const d=document.createElement('dialog');d.className='asmach-modal';d.style.cssText='width:min(840px,94vw);border:1px solid #bbd7df;border-radius:14px;padding:16px';d.innerHTML='<h3>Kalite ve operatör kontrol planı</h3><div class="modal-body" data-roles></div><p data-error role="alert"></p><div class="modal-actions"><button type="button" class="btn" data-cancel>Vazgeç</button><button type="button" class="btn primary" data-save>Uygula</button></div>';document.body.append(d);const ui=mount(d.querySelector('[data-roles]'),record,app.getMethods(),app.state.metadata?.inspectionReport?.lotSize);d.querySelector('[data-cancel]').onclick=()=>d.close();d.querySelector('[data-save]').onclick=()=>{const p=ui.read(),e=validate({rolePlans:p});if(e){d.querySelector('[data-error]').textContent=e;return;}onSave(p);d.close();};d.addEventListener('close',()=>d.remove());d.showModal();}
 root.ASMachRolePlans={roles,levels,starts,codes,sizes,blank,normalize,sample,optionalSample,samplingError,validate,mount,open,openSamplingTable};
})(window);
