(function(root){
 'use strict';let app,screen,db,queue=Promise.resolve(),wasEmpty=false;
 const database=()=>db||(db=new Promise((resolve,reject)=>{const r=indexedDB.open('asmach-recent-work',2);r.onupgradeneeded=()=>{for(const name of ['recent','saved'])if(!r.result.objectStoreNames.contains(name))r.result.createObjectStore(name,{keyPath:'id'});};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);}));
 async function entries(store='recent'){const d=await database();return new Promise((resolve,reject)=>{const r=d.transaction(store).objectStore(store).getAll();r.onsuccess=()=>resolve(r.result.sort((a,b)=>b.at-a.at));r.onerror=()=>reject(r.error);});}
 function remember(payload,options={}){if(!payload?.source?.dataUrl)return;const copy=structuredClone(payload);const operation=queue.then(async()=>{const hash=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(copy.source.dataUrl)),id=Array.from(new Uint8Array(hash),b=>b.toString(16).padStart(2,'0')).join(''),d=await database(),old=await entries();await new Promise((resolve,reject)=>{const tx=d.transaction(['recent','saved'],'readwrite'),s=tx.objectStore('recent'),previous=old.find(e=>e.id===id),record={id,name:options.name||previous?.name||copy.metadata?.projectName||copy.source.name,at:Date.now(),payload:copy};record.savedId=options.savedId||(options.saved?id+':'+record.name:previous?.savedId)||null;s.put(record);old.filter(e=>e.id!==id).slice(7).forEach(e=>s.delete(e.id));if(options.saved)tx.objectStore('saved').put({...record,id:record.savedId});tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error);});if(screen&&!screen.hidden)await refreshList();});queue=operation.catch(()=>{if(screen)screen.querySelector('[data-home-status]').textContent='Yerel proje listesi kaydedilemedi. Proje dosyanız etkilenmedi.';});return options.savedId?operation:queue;
 }
 async function refreshList(){if(!screen)return;for(const store of ['saved','recent']){const list=screen.querySelector('[data-'+store+']');list.replaceChildren();try{const records=await entries(store);if(!records.length){list.textContent=store==='saved'?'Henüz burada kaydedilmiş proje yok.':'Henüz son açılan çalışma yok.';continue;}for(const entry of records){const b=document.createElement('button');b.className='home-recent';const name=document.createElement('strong'),detail=document.createElement('span');name.textContent=entry.name||'Adsız proje';detail.textContent=new Date(entry.at).toLocaleString('tr-TR')+' · '+(entry.payload.annotations?.length||0)+' karakteristik';b.append(name,detail);b.onclick=async()=>{b.disabled=true;try{const savedId=store==='saved'?entry.id:entry.savedId;if(!await app.restoreProject(entry.payload,savedId?{id:savedId,name:entry.name}:null))return;await remember(entry.payload,{name:entry.name,savedId});sync();}catch(e){screen.querySelector('[data-home-status]').textContent='Proje açılamadı: '+e.message;}finally{b.disabled=false;}};list.append(b);}}catch{list.textContent='Liste açılamadı. Proje aç düğmesini kullanabilirsiniz.';}}}
 function sync(){const empty=!app.state.fileData;screen.hidden=!empty;document.body.classList.remove('home-empty');const recovery=document.querySelector('#projectRecovery [data-restore]');screen.querySelector('[data-home-recover]').hidden=!recovery||recovery.hidden;if(empty&&!wasEmpty)void refreshList();wasEmpty=empty;}
 function init(bridge){app=bridge;screen=document.createElement('section');screen.id='drawingHome';screen.innerHTML='<h2>Çizimle çalışmaya başlayın</h2><div class="home-actions"><button class="btn primary" data-home-drawing>＋ Yeni Proje</button><button class="btn" data-home-project>Proje aç</button><button class="btn" data-home-recover hidden>Yerel kopyayı kurtar</button></div><p class="home-hint">PDF veya görseli bu alana sürükleyebilirsiniz.</p><div class="home-lists"><section><h3>Kaydedilen projeler</h3><div data-saved></div></section><section><h3>Son açılanlar</h3><div data-recent></div></section></div><p class="home-hint">Listeler bu cihazdaki yerel kopyaları açar. Dosyada sonradan yapılan değişiklikler için Proje aç seçeneğini kullanın.</p><p data-home-status role="status"></p>';
 document.getElementById('emptyState').append(screen);screen.querySelector('[data-home-drawing]').onclick=()=>document.getElementById('openFileButton').click();screen.querySelector('[data-home-project]').onclick=()=>document.getElementById('loadProjectButton').click();screen.querySelector('[data-home-recover]').onclick=()=>document.querySelector('#projectRecovery [data-restore]')?.click();
 const css=document.createElement('style');css.textContent='#emptyState:has(#drawingHome){align-items:flex-start;overflow:auto;padding:26px;box-sizing:border-box}#emptyState #dropZone{display:none}#drawingHome{width:min(100%,1000px);margin:auto;color:#173b50;text-align:left}#drawingHome[hidden],#drawingHome [hidden]{display:none!important}#drawingHome h2{font-size:22px;margin:0 0 18px}#drawingHome h3{font-size:15px;margin:0 0 14px}.home-actions{display:flex;gap:10px;flex-wrap:wrap}.home-actions .btn{min-height:42px}.home-lists{display:grid;grid-template-columns:1fr 1fr;gap:18px;margin:24px 0}.home-lists>section{padding:20px;background:#fff;border:1px solid #d4e0e8;border-radius:10px;min-width:0}.home-lists [data-saved],.home-lists [data-recent]{max-height:310px;overflow:auto;font-size:12px;color:#61798c}.home-recent{display:flex;flex-direction:column;gap:5px;width:100%;text-align:left;border:0;border-bottom:1px solid #e3ebf0;background:white;padding:12px;color:#173b50;cursor:pointer}.home-recent:hover,.home-recent:focus-visible{background:#e9f6f8}.home-recent strong{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;max-width:100%}.home-recent span,.home-hint{font-size:11px;color:#61798c}#drawingHome [data-home-status]{font-size:12px;color:#974211}@media(max-width:850px){.home-lists{grid-template-columns:1fr}#emptyState:has(#drawingHome){padding:16px}}';document.head.append(css);setInterval(sync,250);sync();}
 root.ASMachStartScreen={init,remember,refreshList,sync:()=>{if(screen)sync();}};
})(window);
