(function(root){
 'use strict';let active='drawing',rendered='';const entries=new Map();let bar;
 const definitions=[['styles','#balloonSettingsModal.is-visible','Balon stili'],['numbering','.view-numbering-dialog[open]','Numaralandırma'],['automatic','#automaticReviewModal.open','Otomatik tespit'],['reports','#reportCenter:not(.output-window)','Çıktılar'],['production','#productionWorkspace:not(.project-info-window)','Proje / FAI'],['pdf','#pdfExportModal.is-visible','PDF ayarları'],['inspection','dialog.inspection-report-dialog[open]','Kontrol raporları'],['excel','.wf-dialog.open:has([data-mode])','Excel / FAI raporu']];
 const triggers={balloonSettingsButton:'styles',viewNumberingButton:'numbering',autoDetectButton:'automatic',productionWorkspaceButton:'production',pdfButton:'pdf',inspectionReportsButton:'inspection',excelExportButton:'excel',appSettingsButton:'settings',helpButton:'help'};
 definitions.push(['settings','#desktopSettings[open]','Ayarlar'],['about','#aboutWorkspace','Hakkında'],['help','#keyboardHelp[open]','Yardım']);
function activate(key){if(key!=='drawing'&&!entries.has(key))return;root.ASMachLicenseCenter?.close?.();if(key!=='drawing'&&root.ASMachApp?.state.mode==='box')root.ASMachApp.setMode('select');active=key;rendered=key;document.body.dataset.workspaceScreen=key;for(const [id,entry] of entries){entry.panel.classList.toggle('wt-inactive',id!==key);entry.panel.inert=id!==key;}for(const b of document.querySelectorAll('[data-workspace-trigger]'))b.setAttribute('aria-pressed',String(b.dataset.workspaceTrigger===key||(b.dataset.workspaceTrigger==='reports'&&['pdf','inspection','excel'].includes(key))));const entry=entries.get(key);if(entry)requestAnimationFrame(()=>{const field=entry.panel.querySelector('input:not([type=hidden]),select,button:not([hidden])');if(field&&field.getClientRects().length)field.focus({preventScroll:true});});}
 function flatten(id,panel){
  const header=panel.querySelector(':scope>header,:scope>.acui-head,:scope>.settings-card>.modal-head,:scope>.modal-card>.modal-head,:scope>.wf-card>.wf-head');if(!header)return;
  const target=id==='styles'?panel.querySelector('.settings-section-head'):id==='production'?panel.querySelector('nav'):panel.querySelector('.wf-tools,.wf-body,.modal-body,.acui-content,main');
  if(target){for(const button of [...header.querySelectorAll('button')]){if(button.matches('[data-close],[data-cancel],#settingsCancelButton,#pdfExportCancelButton,#wfClose'))continue;target.append(button);}for(const field of [...header.querySelectorAll('select,input')])target.append(field.closest('label')||field);}
  header.style.setProperty('display','none','important');
 }
 function init(){
  const toolbar=document.querySelector('.toolbar');bar=document.createElement('div');bar.hidden=true;
  const drawing=document.createElement('button');drawing.type='button';drawing.className='btn';drawing.textContent='Çizim';drawing.dataset.workspaceTrigger='drawing';drawing.onclick=()=>activate('drawing');toolbar.querySelector('.wl-appbar').append(drawing);
  for(const [id,key] of Object.entries(triggers)){const b=document.getElementById(id);if(b)b.dataset.workspaceTrigger=key;}const reports=document.getElementById('pdfButton')?.closest('details')?.querySelector('summary');if(reports)reports.dataset.workspaceTrigger='reports';
  const add=()=>{};
  const style=document.createElement('style');style.textContent=`html body .app{grid-template-rows:auto auto auto minmax(0,1fr)}#workspaceTabs{display:flex;align-items:center;gap:3px;padding:3px 10px;background:#e9f1f6;border-bottom:1px solid #bfdae5;z-index:3000;flex-wrap:wrap;min-width:0}#workspaceTabs .btn{font-size:11px;min-height:29px;padding:5px 12px;border:1px solid transparent;border-radius:5px 5px 0 0;background:transparent;color:#426277}#workspaceTabs .btn[aria-selected=true]{background:white;border-color:#b9d7e3;border-bottom:2px solid #008e9f;color:#007b8d;font-weight:700}html body .wt-panel.wt-inactive{display:none!important}.wt-panel>#unused{display:none}html body .wt-panel #settingsCancelButton,html body .wt-panel #pdfExportCancelButton,html body .wt-panel #wfClose,html body .wt-panel>.acui-head>[data-cancel],html body .wt-panel>header [data-close],html body .wt-panel .wf-head [data-close],html body .wt-panel .acui-foot>[data-close]{display:none!important}html body dialog.wt-panel{inset:var(--app-shell-bottom) 0 0!important;margin:0!important;width:100vw!important;height:calc(100dvh - var(--app-shell-bottom))!important;max-width:100vw!important;max-height:calc(100dvh - var(--app-shell-bottom))!important;border-radius:0!important}`;document.head.append(style);
  style.textContent+=`html body .app{grid-template-rows:auto auto minmax(0,1fr)}.toolbar [data-workspace-trigger][aria-pressed=true]{background:#dff3f6!important;border-color:#008da1!important;box-shadow:inset 0 -2px #008da1!important;color:#006c7b!important}.wt-panel .settings-section-head #settingsSaveButton{margin-left:8px}html body[data-workspace-screen]:not([data-workspace-screen=drawing]) #overlay{display:none!important}`;
  const position=()=>document.documentElement.style.setProperty('--app-shell-bottom',Math.ceil(toolbar.getBoundingClientRect().bottom)+'px');new ResizeObserver(position).observe(toolbar);root.addEventListener('resize',position);position();
  const scan=()=>{let newKey=null;for(const [id,selector,label] of definitions){const panel=document.querySelector(selector),entry=entries.get(id);if(entry&&entry.panel!==panel){entry.panel.classList.remove('wt-inactive');entry.panel.inert=false;entries.delete(id);bar.querySelector(`[data-workspace-tab="${id}"]`)?.remove();if(active===id)active='drawing';}if(panel&&!entries.has(id)){panel.classList.add('wt-panel');entries.set(id,{panel});flatten(id,panel);add(id,label);newKey=id;}}if(newKey)activate(newKey);else if(rendered!==active)activate(active);};
  let pending=false;new MutationObserver(()=>{if(!pending){pending=true;queueMicrotask(()=>{pending=false;scan();});}}).observe(document.body,{childList:true,subtree:true,attributes:true,attributeFilter:['class','open']});
document.addEventListener('click',e=>{const b=e.target.closest('button,summary');if(!b)return;if(['selectModeButton','addModeButton','boxOcrModeButton','acuiCreateManual','acuiCreateGdt','acuiCreateNote'].includes(b.id)||b.matches('.qt-choice'))activate('drawing');const key=triggers[b.id]||(b.matches('.wl-menu>summary')&&b.parentElement.querySelector('#pdfButton')?'reports':null);if(key&&entries.has(key)){e.preventDefault();e.stopImmediatePropagation();activate(key);}},true);
  scan();activate('drawing');
 }
 root.ASMachWorkspaceTabs={init,activate};
})(window);
